### ISSUE TITLE
Manually selecting an offset tab title doesnt center to selection

### ISSUE THREAD

**Issue by liorazi** [xmartlabs/XLPagerTabStrip#1]
See attached screenshot

![ios simulator screen shot jan 3 2015 7 22 20 pm](https://cloud.githubusercontent.com/assets/2930153/5603143/de74c28e-937d-11e4-8b1b-03b5edea1055.png)

**Comment by xhzengAIB** [comment]
Hi! @liorazi 

This demo use UICollectionView due with buttons bar, can try this [XHScrollMenu](https://github.com/JackTeam/XHScrollMenu)

**Comment by mtnbarreto** [comment]
Hey @liorazi , 
You can use this method ( https://github.com/xmartlabs/XLPagerTabStrip/blob/master/XLPagerTabStrip/XL/Views/XLButtonBarView.m#L65 ) to move the indicator.

I'm not sure what exactly you are trying to accomplish. Invoking this method will update the indicator and make it visible. It was intended to be used by the library, not to be invoked form custom code.

I guess you want to select a particular view controller, you can do it by invoking ( https://github.com/xmartlabs/XLPagerTabStrip/blob/master/XLPagerTabStrip/XL/Controllers/XLPagerTabStripViewController.h#L86 ).
Hope it helps!

**Comment by cyrus86** [comment]
Hi @mtnbarreto 
the links in your answer are going to 404 pages by now. could you name the actual method names please? is the second one moveToViewController?
