### ISSUE TITLE
Cell missing in the UITableView

### ISSUE THREAD

**Issue by gclsoft** [xmartlabs/XLPagerTabStrip#10]
If I don't add this line: `    [self.tableView registerClass:[UserInfoBasicCell class] forCellReuseIdentifier:kCellIdentifierBasicCell];
` 
It crashes at cellForRowAtIndexPath:  `[tableView dequeueReusableCellWithIdentifier:kCellIdentifierBasicCell forIndexPath:indexPath];`

If I add that line, I can't see the cell. The cell is not programely created, it is created in the storyboard.
How to let the cell display?

**Comment by gclsoft** [comment]
I removed XLPagerTabStrip and `[self.tableView registerClass:[UserInfoBasicCell class] forCellReuseIdentifier:kCellIdentifierBasicCell]; `, I can see the table display the cell correctly.

But I need to use XLPagerTabStrip, I don't know how to display the storyboard cell to the table correctly. Please help me. Thanks very much!

**Comment by johnqiuwan** [comment]
I have the same problem.
Cell data doesn't display when I use storyboard cell

Any help?

**Comment by gclsoft** [comment]
@johnqiuwan Have you solved it?
 I'm still searching for a solution. Is there any good alternative for this library `XLPagerTabStrip` ?

**Comment by mtnbarreto** [comment]
@gclsoft @johnqiuwan Are you still having this problem?

**Comment by mtnbarreto** [comment]
@gclsoft @johnqiuwan 
I'm sure this is not an issue of the library.

Make sure that your custom class
`-(NSArray *)childViewControllersForPagerTabStripViewController:(XLPagerTabStripViewController *)pagerTabStripViewController` implementation load the child view controller (table view controller) from the storyboard.

see bellow how i provide these view controllers:

```objc
-(NSArray *)childViewControllersForPagerTabStripViewController:(XLPagerTabStripViewController *)pagerTabStripViewController
{
    // create child view controllers that will be managed by XLPagerTabStripViewController

    // provide a child view controller defined  in the storyboard
    TableChildExampleViewController * child_1 =  [self.storyboard instantiateViewControllerWithIdentifier:@"TableChildExampleViewController"];

    ChildExampleViewController * child_2 = [[ChildExampleViewController alloc] init];
    TableChildExampleViewController * child_3 = [self.storyboard instantiateViewControllerWithIdentifier:@"TableChildExampleViewController"];
    ChildExampleViewController * child_4 = [[ChildExampleViewController alloc] init];
    return @[child_1, child_2, child_3, child_4];
```

Regards

**Comment by artemmihelson** [comment]
Hey, I had the same issue. It was solved when I started loading table view controllers from the storyboard. 

Now I have an issue when I pop to the screen with the pager tab strip from another screen.
Let's say, the scenario is the following:
1. Screen with the tabs is opened (I load child view controllers here). 
1.1 In Child view controller I retrieve data from the api server based on the date passed to this controller and render it in tableView. It renders successfully and cellForRowAtIndexPath is getting called successfully.
2. I go to the screen with calendar, select desired date and pass it back to the root pager tab strip controller.
2.1 In the same way I load child view controllers and pass updated date
2.2 Child view controller is loaded, new data is loaded from api, but cellForRowAtIndexPath is never called, thus tableView not loaded with new data.

Do you have any thoughts why this could happen?

**Comment by artemmihelson** [comment]
disregard my comment, the solution was to use reloadPagerTabStripView
