### ISSUE TITLE
Change selected tab label color swift

### ISSUE THREAD

**Issue by tiagopigatto** [xmartlabs/XLPagerTabStrip#103]
I'm trying to change the selected tab label color for the ButtonBarPagerStrip but the color simply doesn't change. I'm trying to set this on the viewDidLoad method of my class.
```swift
self.changeCurrentIndexBlock = { (oldCell : XLButtonBarViewCell!, newCell : XLButtonBarViewCell!, animated : Bool) -> Void in
            
            
            oldCell.label.textColor = UIColor(red: 125/255.0, green: 126/255.0, blue: 128/255.0, alpha: 1.0)
            newCell.label.textColor = UIColor.appRedColor()
            
            
        }
```

Any help on this?

**Comment by mtnbarreto** [comment]
@tiagopigatto Is `changeCurrentIndexBlock` being invoked?

**Comment by mtnbarreto** [comment]
library version?

**Comment by Asif1168** [comment]
how can I change the color of button bar view from child??
