### ISSUE TITLE
First entered,  Selected Image NO Highlighted?? 

### ISSUE THREAD

**Issue by Pikdays** [xmartlabs/XLPagerTabStrip#104]
![image](https://cloud.githubusercontent.com/assets/7825020/12442101/002cad74-bf88-11e5-9ef9-c008bc942558.png)
![image](https://cloud.githubusercontent.com/assets/7825020/12442113/124b152c-bf88-11e5-9b78-0fdf565c530e.png)

**Comment by Pikdays** [comment]
@mtnbarreto ？SOS

**Comment by Pikdays** [comment]
solved

**Comment by Pikdays** [comment]
solved

**Comment by mtnbarreto** [comment]
@Pikdays  could you share which how you solved the issue? So anyone can look into it if it faced the same problem.

**Comment by Pikdays** [comment]
@mtnbarreto Sorry, hurry, forget

## Solve Method:
``` Objective-C
self.changeCurrentIndexBlock = ^(XLButtonBarViewCell *oldCell, XLButtonBarViewCell *newCell, BOOL animated) {
        oldCell.imageView.highlighted = NO;
        newCell.imageView.highlighted = YES;
        
        oldCell.label.textColor = [UIColor colorWithHexString:@"141414"];
        newCell.label.textColor = [UIColor colorWithHexString:@"52c001"];
    };
```
