### ISSUE TITLE
A problem with using XLButtonBarPagerTabStripViewController programmatically

### ISSUE THREAD

**Issue by gzncland** [xmartlabs/XLPagerTabStrip#105]
When I create a `ViewController` extend `XLButtonBarPagerTabStripViewController` in my project with programmatically,
```
Assertion failure in -[XLButtonBarView _dequeueReusableViewOfKind:withIdentifier:forIndexPath:viewCategory:], 
/BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKit/UIKit-3512.30.14/UICollectionView.m:3690
```
And I see the issue#33 ,add code 
```
 UINib *nib = [UINib nibWithNibName:@"ButtonCell" bundle:nil] ;
 [self.buttonBarView registerNib:nib forCellWithReuseIdentifier:@"Cell"];
```
and add file `ButtonCell.xib` (in Demo project's) to my project.
Now app terminating at 
```
UICollectionViewLayoutAttributes *attributes = [self layoutAttributesForItemAtIndexPath:index]; 
```
`XLButtonBarView.m` ,line 122, EXC_BAD_ACCESS

But,if I change `XLButtonBarPagerTabStripViewController` to `XLSegmentedPagerTabStripViewController` or `XLTwitterPagerTabStripViewController`,my code is work.How to fix this?

**Comment by AhmedDroid** [comment]
there's a bug in the source code of this library unfortunately :( I've tried to implemented and faced the same issue

**Comment by mtnbarreto** [comment]
@gzncland @AhmedDroid Please chack that you are using version 3.0.0 which is the last one. https://github.com/xmartlabs/XLPagerTabStrip/releases

**Comment by gzncland** [comment]
@mtnbarreto I checked my code,It's using 3.0.0
I set the `self.subController.buttonBarView` in `[self.navigationItem setTitleView: ]` before `[self.subController viewDidLoad]` has called.I think it's my code's problem. Thanks : ]

**Comment by mtnbarreto** [comment]
:+1:

**Comment by pankajfoodpanda** [comment]
At my end I just register the cell XLButtonBarViewCell in viewDidLoad function.

    `[_buttonBarView registerClass:[XLButtonBarViewCell class] forCellWithReuseIdentifier:@"XLButtonBarViewCell"];`

and then change the cell identifier from "Cell" to "XLButtonBarViewCell" in cellForItemAtIndexPath method

    `XLButtonBarViewCell * cell = [collectionView dequeueReusableCellWithReuseIdentifier:@"XLButtonBarViewCell" forIndexPath:indexPath];`

And code is working fine now.

**Comment by iossolutions** [comment]
At my end I just register the cell XLButtonBarViewCell in viewDidLoad function.

`[_buttonBarView registerClass:[XLButtonBarViewCell class] forCellWithReuseIdentifier:@"XLButtonBarViewCell"];`
and then change the cell identifier from "Cell" to "XLButtonBarViewCell" in cellForItemAtIndexPath method

`XLButtonBarViewCell * cell = [collectionView dequeueReusableCellWithReuseIdentifier:@"XLButtonBarViewCell" forIndexPath:indexPath];`
And code is working fine now.
