### ISSUE TITLE
How to change the width of selectedBar?

### ISSUE THREAD

**Issue by linlin5910** [xmartlabs/XLPagerTabStrip#108]
Is there a way to change the width of selectedBar?  The width of selectedBar is always the same to XLButtonBarViewCell. I want it would be shorter.
    selectedBarFrame.size.width = selectedCellFrame.size.width;
    selectedBarFrame.origin.x = selectedCellFrame.origin.x;

**Comment by m-revetria** [comment]
In order to support this natively we need to change the definition of `selectedBarHeight` to be `open` instead of internal.
