### ISSUE TITLE
Cell data doesn't display if use storyboard to build cell

### ISSUE THREAD

**Issue by johnqiuwan** [xmartlabs/XLPagerTabStrip#11]
I found that the cell data is not displayed when I use storyboard to build cell.

However, tableview:(uitableview *)tableview cellforrowatindexpath:(nsindexpath *)indexpath is called.
Also, there is extra space on the top of the child view. 

Any solution to solve the problem?

Thank you!

**Comment by mtnbarreto** [comment]
@johnqiuwan  I have tested this scenario and it works. 

See my comments here: https://github.com/xmartlabs/XLPagerTabStrip/issues/10
Regards
