### ISSUE TITLE
"Receiver has no segue with identifiier" error when didselectrowatIndexPath

### ISSUE THREAD

**Issue by pmendiburu** [xmartlabs/XLPagerTabStrip#110]
I got this error when I clicked in a cell and the segue already exits.

Any idea what is the problem?

I would be very grateful if you can give any help.

Thank you for everything.

**Comment by mtnbarreto** [comment]
IT seems in not something related with the library since i understand the cell you mentioned is part of a child view controller, right?

@pmendiburu Could you please follow this contributing guide https://github.com/xmartlabs/XLPagerTabStrip/blob/swift/CONTRIBUTING.md to ask for help.
