### ISSUE TITLE
ButtonBarPagerTabStripViewController crash

### ISSUE THREAD

**Issue by tailec** [xmartlabs/XLPagerTabStrip#113]
`ButtonBarPagerTabStripViewController` crashes sometimes when I click on `buttonBarView`.

It crashes in `ButtonBarPagerTabStripViewController` at 
```
let oldCell = buttonBarView.cellForItemAtIndexPath(NSIndexPath(forItem: currentIndex, inSection: 0)) as! ButtonBarViewCell
```
with `Optional null exception`.

I fixed that by replacing `as! ButtonBarViewCell` with `as? ButtonBarViewCell` but I'm not sure if it's not affecting something else.

**Comment by mtnbarreto** [comment]
@tailec Can you show me step by step how you are setting up the buttonBarView?

**Comment by tailec** [comment]
@mtnbarreto I created sample project here: https://github.com/tailec/XLPagerTabStripTestProject

If you're on the first tab, try to tap on the last one. It crashes :)

**Comment by mtnbarreto** [comment]
@tailec Thanks for the sample project, it was very useful. As you said there is a bug when the oldCell is no longer visible in the `buttonBarView` collectionView,  in this particular case `buttonBarView.cellForItemAtIndexPath(NSIndexPath(forItem: currentIndex, inSection: 0))` returns nil and `as!` makes the app crash.

Do you want to fix it with the change you proposed initially?

**Comment by tailec** [comment]
Yeah sure, I'll make PR this evening as soon as I get back home

**Comment by mtnbarreto** [comment]
:+1:  thanks!
