### ISSUE TITLE
Auto Layout still required after sending -viewDidLayoutSubviews to the view controller.

### ISSUE THREAD

**Issue by starkite** [xmartlabs/XLPagerTabStrip#12]
Why i always crash in ios7
 
Auto Layout still required after sending -viewDidLayoutSubviews to the view controller.

thanks!

**Comment by loydkim** [comment]
override func viewDidLayoutSubviews() {
        self.view.layoutSubviews()
    }

**Comment by loydkim** [comment]
override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        self.view.layoutSubviews()
    }

**Comment by mtnbarreto** [comment]
@starkite  @starkite I have tested the master branch in ios 7.1 and it works properly. Could you point me how to reproduce the error?

**Comment by mtnbarreto** [comment]
@starkite @loydkim i could reproduce the issue. should be fixed in master branch. Thanks for reporting it.

**Comment by PratikHyperlink** [comment]
why get random crash in ios7.
