### ISSUE TITLE
Can not see any content

### ISSUE THREAD

**Issue by camel113** [xmartlabs/XLPagerTabStrip#123]
I followed your README. My ButtonBarPagerTabStripViewController works correctly. I can see the button bar and swipe between my child controllers. However I can not see any content in my child controllers. I have also an error if I use a tableview controller as a child controller

> Assertion failure in -[UITableView dequeueReusableCellWithIdentifier:forIndexPath:]

> Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'unable to dequeue a cell with identifier MyNewTableViewCell - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'

As you can see I use the storyboard to configure my views and tableviews.

**Comment by mtnbarreto** [comment]
@camel113 Which library version are you using? Could you please upload a repo to reproducing the issue so i can look into it?

**Comment by camel113** [comment]
@mtnbarreto Initially I tried to add your lib inside a big project. But I made a special project to explain my bug. The url of the repo https://github.com/camel113/testXLPagerTabStrip.

**Comment by mtnbarreto** [comment]
Hey @camel113 , there are some little issues in your project.

1. TableView cell identifier is not properly set up. Please check it. According to your code it should be `reuseIdentifier`. 
2. You are instantiating programatically the `SecontViewController` and then expecting to dequeue the table view cell in this line:  `let cell = tableView.dequeueReusableCellWithIdentifier("reuseIdentifier", forIndexPath: indexPath)`

> I've not reviewed the first view controller. 

It will probably work if you fix these issues. 

Best

**Comment by camel113** [comment]
@mtnbarreto Sorry I forgot to add correct identifier for the tableview. Now my table view controller (secondViewController) works correctly . If I set this controller as initial controller it works! But if I try to use it from the PagerTabStripController it still does not work. If you notice, I also have some special content inside my firstViewcontroller and it is not showed if I use it from your pager.

Please @mtnbarreto can you check again?

Thanks in advance.

**Comment by mtnbarreto** [comment]
@camel113 

After looking into this line https://github.com/camel113/testXLPagerTabStrip/blob/master/testPagerNavigation/ViewController.swift#L25 it seems to me you should instantiate the child view controllers using your storyboard otherwise no view will appear.

Something like: `storyboard.instantiateViewControllerWithIdentifier("someViewController")`

**Comment by camel113** [comment]
Ok thank you. It seems that is a terrible mistake :-( I am a beginner in iOS developement ! Thank you for your support

**Comment by Balmurugan96** [comment]
i am having two views in an tab bar if i press first tab it will show first view controller ..but if i click second view controller their is an white space is created on the left side of the second view controller..how to resolve this issue...
