### ISSUE TITLE
App becomes unresponsive after randomly tapping the tabs quickly

### ISSUE THREAD

**Issue by victor-gabana** [xmartlabs/XLPagerTabStrip#124]
When tapping quickly the tabs the app eventually gets blocked as the methods "moveToViewControllerAtIndex:" and "scrollViewDidEndScrollingAnimation:" compete for the userInteractionEnabled of the views. This will eventually lead to set the userInteractionEnabled to NO and never unlocking it. In this scenario the user will have to kill the app as it becomes completely unresponsive.

**Comment by victor-gabana** [comment]
I have raised a pull request for this issue.

https://github.com/xmartlabs/XLPagerTabStrip/pull/125

Cheers!

**Comment by ftvs** [comment]
@mtnbarreto, who is authorised to merge this? I would merge it if I could.

**Comment by ftvs** [comment]
This has been merged in #125. Cheers.
