### ISSUE TITLE
How to creat a subclass of BaseButtonBarPagerTabStripViewController like the YoutubeExampleViewController in Demo

### ISSUE THREAD

**Issue by zsmzhu** [xmartlabs/XLPagerTabStrip#129]
When I try to creat subclass of BaseButtonBarPagerTabStripViewController like the YoutubeExampleViewController, I found that I can not use it. The application crash and the error is "Unknown class in Interface Builder file". But the YoutubeExampleViewController in Demo is OK. When I try to copy the code of YoutubeExampleViewController to another project, it crash too and error is same. I'm confuse. Could you tell me how to deal with it? thank you very much!

**Comment by zsmzhu** [comment]
I have to give up to find this issue. And the error is ' this class is not key value coding-compliant for the key buttonBarView.'

**Comment by HumidBrains** [comment]
Same issue. After a long struggle I had to give up.

**Comment by mtnbarreto** [comment]
Sorry for the delay in the response. Similar to #141
