### ISSUE TITLE
Android Version

### ISSUE THREAD

**Issue by boatengfrankenstein** [xmartlabs/XLPagerTabStrip#13]
Do you have an android version for the XLPagerTabStrip. My main concern is switching page with onclick on the action bar menu. How do you implement a similar one in android like you did in this example? Thanks.

**Comment by mtnbarreto** [comment]
@boatengfrankenstein 
There is a Android implementation :  https://github.com/astuetz/PagerSlidingTabStrip 

Regards

**Comment by boatengfrankenstein** [comment]
Thank you
