### ISSUE TITLE
Use an Existing View Controller in Storyboard layout rather than XIB file for controller

### ISSUE THREAD

**Issue by Jakkawad** [xmartlabs/XLPagerTabStrip#132]
Use an Existing View Controller in Storyboard layout rather than XIB file for controller

thank you

**Comment by sabinbajracharya** [comment]
To use storyboard view controller set the storyboard id and use it to access the viewcontroller;
Example:
YourViewController * child_1 = [self.storyboard instantiateViewControllerWithIdentifier:@"yourstoryboardid"];

**Comment by myflokk** [comment]
When using an existing view controller via storyboard the view shifts the container view down when transitioning between screens. Any ideas on how to fix this?

**Comment by sujithv28** [comment]
I get an error "init(coder:) has not been implemented" when I try to use my own view controller. I have implemented the proper init methods.

**Comment by dpineda64** [comment]
@sujithv28 , i have the same problem here my solution

on YourViewController
`
required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
}
`
this 
`YourViewController * child_1 = [self.storyboard instantiateViewControllerWithIdentifier:@"yourstoryboardid"];`

gave me this error

`Cannot convert value of type '[UIViewController?]' to expected element type 'UIViewController'`


i changed for this
`UIStoryboard(name: "YourStoryboard", bundle: nil).instantiateViewControllerWithIdentifier("YourViewController")
`

**Comment by kittipongint** [comment]
If you get an error "init(coder:) has not been implemented" just add below code to your view controller

required init(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)!
}

**Comment by joemaia89** [comment]
When using an existing view controller via storyboard the view shifts the container view down when transitioning between screens. Any ideas on how to fix this?

I have the same problems anyone have fix this?

**Comment by santiagofm** [comment]
In https://github.com/xmartlabs/XLPagerTabStrip/issues/290 there are different ways to fix this issue.
Cheers

**Comment by keason** [comment]
When I create a new controller in StoryBoard, Why I cannot find the YoutubeExampleViewController.swift ? Thanks much for help?

**Comment by santiagofm** [comment]
Hi @keason !
Because `YoutubeExampleViewController` uses generics the storyboard isn't able to *find* it, you just type the name anyway and then load the class into the objC runtime sometime **before** the storyboard tries to instantiate it([i.e `AppDelegate` or somewhere else](https://github.com/xmartlabs/XLPagerTabStrip/issues/141#issuecomment-195567544)).

`YoutubeExampleViewController.load()`

Cheers
