### ISSUE TITLE
ViewControllers created in IB are not showing up?

### ISSUE THREAD

**Issue by JPROFFICIAL** [xmartlabs/XLPagerTabStrip#133]
(Using ButtonBarPagerTab) Everything is as it should be, I have connected the storyboards to load as they should and Ive even used print lines to make sure the files are loading when I switch to the VC(s) (which they are). 

For some reason, the content is not showing up at all. I have even set the background color of my scroll view to see if they are showing up, and the background color of the scrollView shows but no view controllers. They are full size regular viewControllers I am loading, with content created in the IB. Do the viewControllers being loaded need to be the size of my containerView? Or will they scale automatically? My scrollView is not the same size as my viewControllers but I figured that would not be an issue since it is meant for content bigger than it. Any help would be greatly appreciated. Feel free to ask if you need more information from me.

![screen shot 2016-02-25 at 3 21 31 pm](https://cloud.githubusercontent.com/assets/14960440/13334824/801885be-dbd3-11e5-903c-3c32e29bd52f.png)
![screen shot 2016-02-25 at 3 21 17 pm](https://cloud.githubusercontent.com/assets/14960440/13334825/801ed1d0-dbd3-11e5-9252-6c7d611d0b16.png)

**Comment by townsendeb** [comment]
How did you solve this issue?
