### ISSUE TITLE
Using XLButtonBarView labelFont Doesn't Seem to Work

### ISSUE THREAD

**Issue by OliverPearmain** [xmartlabs/XLPagerTabStrip#134]
I'm using a XLPagerTabStripViewController programically (without a XIB or storyboard) however am I unable to change the font of the XLButtonBarView, 

There is a labelFont property on XLButtonBarView but setting this doesn't seem to have the desired effect.  The font displayed is always the font thats defined in the XIB.

**Comment by OliverPearmain** [comment]
Address in pull request #135

**Comment by mtnbarreto** [comment]
@OliverPearmain pull request was already merged! thanks for contributing!
