### ISSUE TITLE
Set settings.style before viewDidLoad

### ISSUE THREAD

**Issue by mrcly** [xmartlabs/XLPagerTabStrip#137]
I have to set the style for the selected bar in my `ButtonBarPagerTabStripViewController` before i call `super.viewDidLoad()`.

Example:
```swift
override func viewDidLoad() {
   // this will work
   self.settings.style.selectedBarHeight = 2
   self.settings.style.selectedBarBackgroundColor = UIColor.whiteColor()
        
   super.viewDidLoad()

   // this wont work
   self.settings.style.selectedBarHeight = 2
   self.settings.style.selectedBarBackgroundColor = UIColor.whiteColor()
}
```

**Comment by mtnbarreto** [comment]
@mrcly Actually this isnot a issue. Settings should be configured before `viewDidLoad` is called. Could you please document it in the readme?

**Comment by muescha** [comment]
since `buttonBarView` is a public var maybe you can set it additional to the settings direct this property: `buttonBarView.selectedBar.backgroundColor = UIColor.whiteColor()` if you need it?

**Comment by hechukwu** [comment]
@muescha `buttonBarView.selectedBar.backgroundColor = UIColor.whiteColor()` doesn't work for me

**Comment by AkilaMurugaiah** [comment]
_**buttonBarView.selectedBar.backgroundColor = UIColor(.violet)**_

or

        buttonBarView.selectedBar.backgroundColor = UIColor.yellow
