### ISSUE TITLE
Issue installing with Cocopods Swift

### ISSUE THREAD

**Issue by myflokk** [xmartlabs/XLPagerTabStrip#138]
Hi,

Im trying to import your podfile to my project but I keep getting the error of 

`Analyzing dependencies
Downloading dependencies
Using Stripe (6.0.1)
Using XLPagerTabStrip (4.0.1)
[!] Pods written in Swift can only be integrated as frameworks; add `use_frameworks!` to your Podfile or target to opt into using it. The Swift Pod being used is: XLPagerTabStrip`

Could you help me fix this issue. Here is my podfile

`# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

pod 'Stripe'

target 'Flokk' do

pod 'XLPagerTabStrip'

end

target 'FlokkTests' do

end
`

**Comment by HumidBrains** [comment]
Your pod file should look something like this for it to work.

platform :ios, '8.0'
use_frameworks!

target 'Flokk' do
pod 'Stripe'
pod 'XLPagerTabStrip'
end

target 'FlokkTests' do
end

**Comment by mtnbarreto** [comment]
As @HumidBrains said, minimum supported deployment target is iOS 8.0.
