### ISSUE TITLE
Add headerview to ButtonBarPagerTab

### ISSUE THREAD

**Issue by sairamkotha** [xmartlabs/XLPagerTabStrip#143]
how to add headerview to containerView top of buttonBarView?

**Comment by santiagofm** [comment]
If you are using a Storyboard this is trivial to do, just lay out the views however you want but don't forget to set the `containerView` and `ButtonBarView` outlets.

If you are using the framework programmatically, you can lay out the views however you want **before** calling `super.viewDidLoad()` that is where the default `containerView` and `segmentedControl/ButtonBarView/...` are created and laid out.

Cheers
