### ISSUE TITLE
Button in XIB file not responding

### ISSUE THREAD

**Issue by Mazorati** [xmartlabs/XLPagerTabStrip#149]
Hello!

I am using an Example of latest release this library. I add a UIButton in Helpers/PostCell.xib file 
above all the other layers. This button does not responds. Am i do something wrong?

iOS 9.3

Thanks.

**Comment by santiagofm** [comment]
Hi @Mazorati ! 
This issue has nothing to do with the framework and i would like you to post in stackoverflow.
Cheers

**Comment by susuLiang** [comment]
I have the same issue, does anyone fixed this problem?
