### ISSUE TITLE
Hi! I have some question

### ISSUE THREAD

**Issue by xhzengAIB** [xmartlabs/XLPagerTabStrip#15]
@enrigalmig 
1.0.0 support 7.0 or later .
why 1.0.1 support 7.1 later?

**Comment by Samverylazy** [comment]
Is there any way to make 1.1.0 working with IOS 7.0? I also would like to know...

**Comment by mtnbarreto** [comment]
@xhzengAIB @Samverylazy  
`XLPagerTabStrip` seems to work properly in iOS 7.0. I released a new pod version which has "support" for ios 7.0. 

Thanks
