### ISSUE TITLE
Simple Example Help.

### ISSUE THREAD

**Issue by htarwara6245** [xmartlabs/XLPagerTabStrip#152]
First of all,Thanks for offering us such a beautiful best library.

This is not necessary,but,i really do need help with your sample project.And I don't know how to get my target becasue there are many example at Example project.
So,what i want is this,

![tabbar with page menu](https://cloud.githubusercontent.com/assets/10526402/14098147/e1ac2e72-f59e-11e5-85cd-817bac2c873d.gif)

If you don't mind or have some free time to help,can you help me with my requirement with only one example which i posted.I mean sample project?Please?Because i want to create app like Google Plus which is currently updated.Any Help?

**Comment by tjnet** [comment]
I think what you want is this.

https://github.com/xmartlabs/XLPagerTabStrip/blob/master/Example/Example/ButtonBarExampleViewController.swift
