### ISSUE TITLE
View Controller Stretched

### ISSUE THREAD

**Issue by joaohkfaria** [xmartlabs/XLPagerTabStrip#153]
Anyone is experiencing view controllers being stretched? When I select the a tab for the first time, the view is stretched, but if I click in something (like search bar), the view controller becomes normal.

PS: This don't happen with the first view controller (first item on tab) for some reason...

 **Stretched width:**
<img src="https://cloud.githubusercontent.com/assets/1427347/14156173/6560188a-f69b-11e5-99f1-9a859f8bb67c.png" width="200" >

**When I click on search bar, for example, the width becomes normal:**
<img src="https://cloud.githubusercontent.com/assets/1427347/14156172/65400414-f69b-11e5-98e3-0916b3931c41.png" width="200" >

**Comment by cacoroto** [comment]
I believe I am facing the same issue.

When first loading the viewController or when changing pages by scrolling horizontally I get this:
![screen shot 2016-04-07 at 9 06 30 pm](https://cloud.githubusercontent.com/assets/2833370/14365270/ac009020-fd04-11e5-9bfb-0dc60aec0810.png)


Then, If I click in one of the buttons from the buttonBar, the scrollview suddenly gets the correct behavior:

![screen shot 2016-04-07 at 9 09 00 pm](https://cloud.githubusercontent.com/assets/2833370/14365325/ff23e7fc-fd04-11e5-9340-c201108d00d0.png)


Using the latest version of ButtonBarPagerTabStripViewController.

My implementation mimics exactly what was done on NavButtonBarExampleViewController from the Example project (including constraints)

**Comment by mrigdon** [comment]
Experiencing same issue as @cacoroto and I believe it's when you embed the `ButtonBarPagerTabStripViewController` in a `UINavigationController`.

Here's what it looks like when I open the app (notice the gap between the button bar and the view):

![gap](https://cloud.githubusercontent.com/assets/7377110/14481982/abb7fbd0-00ec-11e6-8bcb-8e0171e96e54.png)

and then when i press on the second item on the button bar, and then back to the first, the issue fixes:

![no_gap](https://cloud.githubusercontent.com/assets/7377110/14481997/cebf3ea4-00ec-11e6-9179-8029058b99ea.PNG)

**Comment by mrigdon** [comment]
@cacoroto You didn't happen to find a fix for this did you?

**Comment by mrigdon** [comment]
Also found that it seems to be a scrolling issue. When I click on the button, the views are correct, but when I swipe, the gap returns.

**Comment by mrigdon** [comment]
@joaohkfaria not sure what's causing your problem, but @cacoroto I found the solution to our problem. Turns out this was solved by #69 .

Try changing the following lines in PagerTabStripViewController.swift to the following:

```swift
// line 57
let containerView = UIScrollView(frame: CGRectMake(0, self.containerView.layer.bounds.origin.y, CGRectGetWidth(self.view.bounds), CGRectGetHeight(self.view.bounds)))
// line 138
containerView.setContentOffset(CGPointMake(pageOffsetForChildIndex(index: fromIndex), self.containerView.layer.bounds.origin.y), animated: false)
// line 140
containerView.setContentOffset(CGPointMake(pageOffsetForChildIndex(index: index), self.containerView.layer.bounds.origin.y), animated: true)
// line 143
containerView.setContentOffset(CGPointMake(pageOffsetForChildIndex(index: index), self.containerView.layer.bounds.origin.y), animated: animated)
// line 218
childController.view.frame = CGRectMake(offsetForChildIndex(index), self.containerView.layer.bounds.origin.y, CGRectGetWidth(view.bounds), CGRectGetHeight(containerView.bounds))
// line 224
childController.view.frame = CGRectMake(offsetForChildIndex(index), self.containerView.layer.bounds.origin.y, CGRectGetWidth(view.bounds), CGRectGetHeight(containerView.bounds))
```

**Comment by cacoroto** [comment]
I got it working last night. I first tried to set it up from scratch in a brand new project to see if I could identify what the issue was but I got the same wrong results.

I then decided to copy the NavButtonBarExampleView from the Example's Dashboard and made it the root of the navigation controller I already had in my project and it worked.

The only thing I copied from the Example was the NavButtonBarExampleView, which makes me believe that I probably set the auto constraints incorrectly

**Comment by cacoroto** [comment]
thanks @mrigdon ! that is exactly the case

**Comment by stevejcox** [comment]
@joaohkfaria did you ever find a fix to this issue? I've come across the same thing.

**Comment by stevejcox** [comment]
Ok @joaohkfaria and anyone else like myself that bumped into this one, found the issue and a fix for me, at least.

Make sure the view within each view controller you will be using has Preserve Superview Margins unchecked and any constraints you have set up NOT set up to the margins.

**Comment by joaohkfaria** [comment]
@stevejcox I gave up trying. I will close this issue because I think you guys managed to solved! :)

**Comment by MarkPolivchuk** [comment]
@stevejcox can you elaborate on what you mean by your solution? 

I would also like to reopen this so we can get an official fix @joaohkfaria

**Comment by stevejcox** [comment]
@MarkPolivchuk sure thing. So in my case I had to uncheck 'Preserve Superview Margins' for both the main view in a view controller to be show in the contentView and for views that sit within that view. I also made sure to use auto-layout constraints set to the superview but not the superview margins.

Between those fixes it fixed everything up perfectly. Again, not sure why this was necessary -  but it worked.

**Comment by MarkPolivchuk** [comment]
@stevejcox thanks for the extra details. That fixed the stretched controllers, but unfortunately breaks some "readable width" properties which are dependent on margins. Better problem to have than clipped view controllers so I'll live but if @mtnbarreto could look into the root cause it would be fantastic

**Comment by sutthichai** [comment]
thanks @mrigdon your solution it work.

**Comment by OEASLAN** [comment]
@mrigdon your solution works thank you for that solution. @joaohkfaria I guess you can fix the problem with changing these codes instead of original codes. If you don't we can create pull request for that. I started to create new fresh controller but I have same issue and @mrigdon 's codes solve the problem. Kind Regards.

**Comment by ibrahimyilmaz7** [comment]
Is there any official fix for this issue? I got same stretching bug, and can't solve it.

**Comment by Saleh-At** [comment]
Hey there
you can correct this prob:
Simple Introduction:
1. click on the **UIScrollView** (as Container)
2. uncheck **Autoresize Subviews** option.

**Comment by AhmedSamir213** [comment]
same issue here

**Comment by AhmedSamir213** [comment]
I found the Solution 
Very Simple 
Just uncheck this in the parent view controller 
![2017-03-12-004](https://user-images.githubusercontent.com/28837248/38611456-fd97dfda-3d83-11e8-8ffd-db9a91e3dc54.png)

**Comment by mmatiush** [comment]
I had the UIScrollView (container) inside another view. I removed the view, so the scroll view was located just in the view of the view controller. It fixed the issue
