### ISSUE TITLE
Error upon installation

### ISSUE THREAD

**Issue by mrigdon** [xmartlabs/XLPagerTabStrip#155]
segmentedControl.addTarget(self, action:, #selector(SegmentedPagerTabStripViewController.segmentedControlChanged(_:)), forControlEvents: .ValueChanged)

The previous line in SegmentedPagerTabStripViewController.swift causes a build failure right off the bat

**Comment by tjnet** [comment]
please try following lines of code

```
                segmentedControl.addTarget(self, action: #selector(SegmentedPagerTabStripViewController.segmentedControlChanged(_:)), forControlEvents: UIControlEvents.ValueChanged)
```

**Comment by mrigdon** [comment]
I ended up switching to 4.0.2 and it works great
