### ISSUE TITLE
How to replace UISegmentedControl with XLButtonBarView in XLSegmentedPagerTabStripViewController

### ISSUE THREAD

**Issue by shuijinliuxi** [xmartlabs/XLPagerTabStrip#16]
I want to set the buttonBarView as navigationItem title by  [self.navigationItem setTitleView:self.buttonBarView]; But it only display the buttonBarView on navigation without text. How can make it?

**Comment by mtnbarreto** [comment]
@shuijinliuxi Please take a look at the example app. Now It contains what you want to accomplish.
Regards

**Comment by shuijinliuxi** [comment]
tks. I have already achieved this. The problem is too much detail was set in the storyboard between I achieved this.  It is fine if the project is all achieved by code and not in storyboard.
