### ISSUE TITLE
How to use attributed string (NSAttributedString) for button bar view cells?

### ISSUE THREAD

**Issue by ftvs** [xmartlabs/XLPagerTabStrip#160]
First, this is a great library. Thanks to all contributors.

As for the topic, is using NSAttributedString for the cell labels a supported feature? The source code appears to suggest otherwise. If not, is it a suitable feature for this library?

Thanks.

EDIT: Can be done in changeCurrentIndexProgressiveBlock or changeCurrentIndexBlock. Scroll down for example code.

**Comment by shinise** [comment]
Good suggestion! I need that featured too so I researched but there isn't for now.
But I think it's not difficult to add feature that using attributed string for button bar label.

**Comment by ftvs** [comment]
This can be done in changeCurrentIndexProgressiveBlock or changeCurrentIndexBlock like so:

`
    buttonBarPagerTabStripViewController.changeCurrentIndexProgressiveBlock = ^(XLButtonBarViewCell *oldCell, XLButtonBarViewCell *newCell, CGFloat progressPercentage, BOOL indexWasChanged, BOOL fromCellRowAtIndex) {
        NSNumber *trackingAmount = @(.5f);
        
        oldCell.label.attributedText
            = (oldCell) ? [[NSAttributedString alloc] initWithString:oldCell.label.text
                                              attributes:@{NSKernAttributeName: trackingAmount,
                                                           NSForegroundColorAttributeName: [UIColor }] : nil;
        newCell.label.attributedText
            = (newCell) ? [[NSAttributedString alloc] initWithString:newCell.label.text
                                              attributes:@{NSKernAttributeName: trackingAmount}] : nil;
    };`
