### ISSUE TITLE
Is it possible to pass data to child view controllers?

### ISSUE THREAD

**Issue by kakubei** [xmartlabs/XLPagerTabStrip#161]
Question: How can I pass data between the child view controllers? 

Thanks.

**Comment by christstuart** [comment]
Also need to know this to.

**Comment by cihanozturk19** [comment]
I made it like this :
**First step:**
Make a variable in class which is inhereted BaseButtonBarPagerTabStripViewController  as below example:
class YourViewController : BaseButtonBarPagerTabStripViewController {
    var yourVariable:String 
// your code
}
**Second step**
class YourFirstChildViewController {
      let parentVC = self.parentViewController as! YourViewController 
      parentVC.yourVariable = "test"
}

class YourSecondChildViewController {
     var secondVariable:String
     let parentVC = self.parentViewController as! YourViewController 
     secondVariable = parentVC.yourVariable
     print(secondVariable) // "test"
}

I hope it works for you
