### ISSUE TITLE
Button Bar weird behavior? XIB vs Storyboard

### ISSUE THREAD

**Issue by dtran808** [xmartlabs/XLPagerTabStrip#162]
Trying to use ButtonBarPagerTabStripViewController in an XIB-based way and not storyboard (in example project). It works perfectly UNTIL I connect the outlets. When I connect the button bar outlet, the selected bar no longer appears. ~~Furthermore, when I connect the container outlet, a top offset appears. I constrained the container to be at a certain Y-position, but it looks like the container gets pushed down another +20pts.~~

My VC code is identical to InstagramExampleViewController.swift. However, I am using an XIB rather than a storyboard.

![screen shot 2016-04-26 at 10 08 59 am](https://cloud.githubusercontent.com/assets/6016629/14827388/f3812a18-0b96-11e6-9df0-1b5506c0a4af.png)

1. I can navigate thru the tabs just fine. However, the selected bar under the selected tabs does not show :(
2. ~~That black bar shouldn't be there. It seems the scroll view container has an offset? Without outlet connected, the scroll view has no offset.~~

Any suggestions?

I also get an output (below) that doesn't show up in the example (which uses storyboard). Maybe it will help :)

- Environment: XLPagerTabStrip 5.0, Xcode 7.3 and iOS 9.3
- Output:

> 2016-04-26 09:40:13.391 app[58223:1180820] the behavior of the UICollectionViewFlowLayout is not defined because:
> 2016-04-26 09:40:13.391 app[58223:1180820] the item height must be less than the height of the UICollectionView minus the section insets top and bottom values, minus the content insets top and bottom values.
> 2016-04-26 09:40:13.391 app[58223:1180820] The relevant UICollectionViewFlowLayout instance is <UICollectionViewFlowLayout: 0x7ffa61e1b420>, and it is attached to <XLPagerTabStrip.ButtonBarView: 0x7ffa64817600; baseClass = UICollectionView; frame = (0 60; 414 50); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x7ffa61e1a190>; layer = <CALayer: 0x7ffa61e179a0>; contentOffset: {0, 0}; contentSize: {240, 128}> collection view layout: <UICollectionViewFlowLayout: 0x7ffa61e1b420>.
> 2016-04-26 09:40:13.391 app[58223:1180820] Make a symbolic breakpoint at UICollectionViewFlowLayoutBreakForInvalidSizes to catch this in the debugger.

**Comment by atraneighty8** [comment]
Note: The black bar appears to only manifest when I use the UINavigationController.

**Comment by dtran808** [comment]
The black bar issue goes away when I don't use the UINavigationController. While using the UINavigationController, I can make it go away when I click on the actual tab buttons. However, when I swipe, it comes back. Hope that helps.

**Comment by dtran808** [comment]
Turns out the black bar is from the infamous UINavigationController gap. Fixed that issue via [this solution](http://stackoverflow.com/questions/31682720/uinavigationcontroller-as-a-child-of-uitabbarcontroller-leaves-a-gap). The missing selected bar is still an issue, though.

**Comment by dtran808** [comment]
Figured it out :)

I set the buttonBarView's height before the super.viewDidLoad() call and worked like a charm.

    override func viewDidLoad() {
        
        buttonBarView.frame.size.height = 50 // <---- THIS RIGHT HERE
        
        settings.style.buttonBarBackgroundColor = .clearColor()
        settings.style.buttonBarItemBackgroundColor = .clearColor()
        settings.style.selectedBarBackgroundColor = UIColor.headerForeground()
        ...
        
        super.viewDidLoad()
    }

In the README, it said to set `settings.style.buttonBarHeight`, but maybe it meant buttonBarView?
