### ISSUE TITLE
Is it possible to change style.selectedBarBackgroundColor in changeCurrentIndexProgressive?

### ISSUE THREAD

**Issue by felixchan** [xmartlabs/XLPagerTabStrip#167]
I can't seem to find the appropriate attribute name.

**Comment by muescha** [comment]
see #137

**Comment by muescha** [comment]
since `buttonBarView` is a public var maybe you can set it additional to the settings direct this property: `buttonBarView.selectedBar.backgroundColor = UIColor.whiteColor()` if you need it?
