### ISSUE TITLE
Collectionview inside XLPagerTabStrip

### ISSUE THREAD

**Issue by kike0kike** [xmartlabs/XLPagerTabStrip#171]
I have a CollectionView that runs, and a XLPagerTabStrip than also run, but when I integrate my CollectionView inside XLPagerTabStrip in the IndicatorInfoProvider I have this error...
 The error is in:
collectionView.delegate = self
collectionView.dataSource = sel.
Error: Thread 1: EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subcode=0x0)
Error in console: fatal error: unexpectedly found nil while unwrapping an Optional value
![captura de pantalla 2016-05-23 a las 8 31 33](https://cloud.githubusercontent.com/assets/4818973/15468799/80094ede-20e6-11e6-83d9-143ab0293fc0.png)
- Environment: Xcode (7.3), iOS (9.3), XLPagerTabStrip (5.0.0)

**Comment by kansaraprateek** [comment]
hi kike0kike,

Your collectionView might not have been initialised.
Can you provide more detail regarding your issue?

**Comment by santiagofm** [comment]
Hi @kike0kike, as @kansaraprateek said this seems to be an issue with the `collectionView` not being initialized, probably an outlet that hasn't been connected.

Cheers

**Comment by SaoudSalih** [comment]
UICollectionView must be initialized with a non-nil layout parameter..What should be the error ? Can anyone help me to sort out this issue..It is okay, perfectly working with uitableview..But with collectionview , it came with this error.
