### ISSUE TITLE
viewDidAppear called twice

### ISSUE THREAD

**Issue by frandelarosa** [xmartlabs/XLPagerTabStrip#172]
I have this scenario:

```swift
- (NSArray *)childViewControllersForPagerTabStripViewController:(XLPagerTabStripViewController *)pagerTabStripViewController{

    UIViewController *viewController1 = [[UIViewController alloc] init];

    UIViewController *viewController2 = [[UIViewController alloc] init];

    return @[viewController1, viewController2];

}
```

When XLPagerTabStrip is loaded, the viewDidAppear method is called twice in viewController1. This only happen with the first controller.

Any reasons?

Thanks in advance.

**Comment by kansaraprateek** [comment]
Hi frandelarosa,

I am having the same issue. I fixed it by commenting two lines in PagerTabStripViewController.swift .

224 -> childController.beginAppearanceTransition(true, animated : false)
229 -> childController.endAppearanceTransition()

**Comment by frandelarosa** [comment]
ok, now it works! thanks @kansaraprateek.

@mats-claassen we can get an official fix for this issue?
