### ISSUE TITLE
Segmented Controller not affect when sliding between view controllers

### ISSUE THREAD

**Issue by 1Market** [xmartlabs/XLPagerTabStrip#173]
I use a segmented controller, ScrollView and 2 view controllers, ScrollView is set as containerView and segmentedController IBOutlet.

When I press segmented controller buttons the tabs changes correctly but when I change the tabs by sliding the scrollview , Segmented Controller selected button not got changed.

**Comment by james-ff** [comment]
I'm seeing the same with 4 tableviews

**Comment by santiagofm** [comment]
This issue is fixed on the latest release

**Comment by rvishal1991** [comment]
It is the same issue, we are facing on latest release 8.0.1.
