### ISSUE TITLE
run example, there some errors.

### ISSUE THREAD

**Issue by arden** [xmartlabs/XLPagerTabStrip#174]
2016-05-25 11:48:00.886 Example[17062:155286] **\* Terminating app due to uncaught exception 'NSRangeException', reason: 'Cannot remove an observer <Example.TwitterExampleViewController 0x7fbe037e6b50> for the key path "frame" from <UIView 0x7fbe034610c0> because it is not registered as an observer.'
**\* First throw call stack:
(
    0   CoreFoundation                      0x000000010ae3cd85 **exceptionPreprocess + 165
    1   libobjc.A.dylib                     0x000000010d2a8deb objc_exception_throw + 48
    2   CoreFoundation                      0x000000010ae3ccbd +[NSException raise:format:] + 205
    3   Foundation                          0x000000010b8f748e -[NSObject(NSKeyValueObserverRegistration) _removeObserver:forProperty:] + 504
    4   Foundation                          0x000000010b8f71fa -[NSObject(NSKeyValueObserverRegistration) removeObserver:forKeyPath:] + 84
    5   XLPagerTabStrip                     0x000000010ac38944 _TFC15XLPagerTabStrip34TwitterPagerTabStripViewControllerD + 132
    6   XLPagerTabStrip                     0x000000010ac38a82 _TToFC15XLPagerTabStrip34TwitterPagerTabStripViewControllerD + 34
    7   CoreFoundation                      0x000000010ad1a98d -[__NSArrayM dealloc] + 157
    8   libobjc.A.dylib                     0x000000010d2bcafe _ZN11objc_object17sidetable_releaseEb + 232
    9   UIKit                               0x000000010bec4782 -[UIViewController dealloc] + 1909
    10  UIKit                               0x000000010bef7f22 -[UINavigationController dealloc] + 438
    11  CoreFoundation                      0x000000010ad1a98d -[__NSArrayM dealloc] + 157
    12  libobjc.A.dylib                     0x000000010d2bcafe _ZN11objc_object17sidetable_releaseEb + 232
    13  UIKit                               0x000000010bec4782 -[UIViewController dealloc] + 1909
    14  UIKit                               0x000000010bf1f623 -[UITabBarController dealloc] + 667
    15  UIKit                               0x000000010bea01ba -[UIPresentationController .cxx_destruct] + 262
    16  libobjc.A.dylib                     0x000000010d2a77bb _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 127
    17  libobjc.A.dylib                     0x000000010d2b2332 objc_destructInstance + 93
    18  libobjc.A.dylib                     0x000000010d2b2365 object_dispose + 22
    19  UIKit                               0x000000010be9bb8c -[UIPresentationController dealloc] + 56
    20  UIKit                               0x000000010c69253e -[_UIFullscreenPresentationController dealloc] + 56
    21  libobjc.A.dylib                     0x000000010d2bcafe _ZN11objc_object17sidetable_releaseEb + 232
    22  UIKit                               0x000000010be9b93d __destroy_helper_block_411 + 24
    23  libsystem_blocks.dylib              0x000000010eb376b1 _Block_release + 128
    24  UIKit                               0x000000010c75b07b -[_UIViewControllerTransitionContext .cxx_destruct] + 94
    25  libobjc.A.dylib                     0x000000010d2a77bb _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 127
    26  libobjc.A.dylib                     0x000000010d2b2332 objc_destructInstance + 93
    27  libobjc.A.dylib                     0x000000010d2b2365 object_dispose + 22
    28  UIKit                               0x000000010c759b04 -[_UIViewControllerTransitionContext dealloc] + 56
    29  UIKit                               0x000000010c75b130 -[_UIViewControllerOneToOneTransitionContext dealloc] + 79
    30  libobjc.A.dylib                     0x000000010d2bcafe _ZN11objc_object17sidetable_releaseEb + 232
    31  libobjc.A.dylib                     0x000000010d2a77bb _ZL27object_cxxDestructFromClassP11objc_objectP10objc_class + 127
    32  libobjc.A.dylib                     0x000000010d2b2332 objc_destructInstance + 93
    33  libobjc.A.dylib                     0x000000010d2b2365 object_dispose + 22
    34  libobjc.A.dylib                     0x000000010d2bcafe _ZN11objc_object17sidetable_releaseEb + 232
    35  UIKit                               0x000000010be94d73 -[UITransitionView _didCompleteTransition:] + 1579
    36  UIKit                               0x000000010be973f4 -[UITransitionView _transitionDidStop:finished:] + 104
    37  UIKit                               0x000000010bdba7ff -[UIViewAnimationState sendDelegateAnimationDidStop:finished:] + 241
    38  UIKit                               0x000000010bdbabae -[UIViewAnimationState animationDidStop:finished:] + 80
    39  QuartzCore                          0x0000000110e2e3c8 _ZN2CA5Layer23run_animation_callbacksEPv + 308
    40  libdispatch.dylib                   0x000000010eac03eb _dispatch_client_callout + 8
    41  libdispatch.dylib                   0x000000010eaa81ef _dispatch_main_queue_callback_4CF + 1738
    42  CoreFoundation                      0x000000010ad960f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE** + 9
    43  CoreFoundation                      0x000000010ad57b99 __CFRunLoopRun + 2073
    44  CoreFoundation                      0x000000010ad570f8 CFRunLoopRunSpecific + 488
    45  GraphicsServices                    0x00000001108e2ad2 GSEventRunModal + 161
    46  UIKit                               0x000000010bd2cf09 UIApplicationMain + 171
    47  Example                             0x000000010ab37ea2 main + 114
    48  libdyld.dylib                       0x000000010eaf492d start + 1
    49  ???                                 0x0000000000000001 0x0 + 1
)
libc++abi.dylib: terminating with uncaught exception of type NSException
(lldb)

**Comment by mtnbarreto** [comment]
That issue is already fixed in version 6.0
