### ISSUE TITLE
referencing outlet not showing up in storyboard

### ISSUE THREAD

**Issue by iVanPan** [xmartlabs/XLPagerTabStrip#175]
- Environment: XLPagerTabStrip 5.0 with Carthage , Xcode 7.3.1 and iOS 9.3.2.

i can't find outlet in storyBoard!
![2016-06-01 15 14 05](https://cloud.githubusercontent.com/assets/1687276/15701288/de81bc5e-280b-11e6-9607-86f8fd65eabb.png)
![2016-06-01 15 14 55](https://cloud.githubusercontent.com/assets/1687276/15701292/e3da2830-280b-11e6-8200-5e79388165db.png)
![2016-06-01 15 15 17](https://cloud.githubusercontent.com/assets/1687276/15701296/eb02bd16-280b-11e6-8826-ffcb953d560c.png)

**Comment by sprint84** [comment]
@iVanPan I can't find it either, how did you solve it?

**Comment by iVanPan** [comment]
@sprint84  use source code， not carthage or cocoapods

**Comment by chiulam** [comment]
Same here with Carthage
But if switch to Cocoapods, the outlet will come back
<img width="308" alt="screen shot 2016-08-24 at 1 52 43 am" src="https://cloud.githubusercontent.com/assets/11757496/17903267/7e192fae-699d-11e6-9946-77622edf1460.png">

Should be a problem of carthage config
