### ISSUE TITLE
Space padding and scroll setup

### ISSUE THREAD

**Issue by hryamzik** [xmartlabs/XLPagerTabStrip#177]
How can I set space padding between tabs to zero? I'd like tabs to fill the bar and avoid gaps, without scrolling. And to have the same width if possible.

I'm using the 3.0 (objective c) version from pods. 

![image](https://cloud.githubusercontent.com/assets/1643962/15763252/52fa5710-292b-11e6-8648-f4b129bc8890.png)

**Comment by santiagofm** [comment]
You can do `buttonBarView .shouldCellsFillAvailableWidth = YES`

Cheers
