### ISSUE TITLE
How to know which tab are you on to at any instance?

### ISSUE THREAD

**Issue by niennonno** [xmartlabs/XLPagerTabStrip#179]
How do I see which child view controller is in the focus and change the navigation items for the parent view controller accordingly.

**Comment by DylanModesitt** [comment]
the `currentIndex` property is public. You could get your parent PagerTabStripController from a child and check the index like this:

        ```
let pageViewController = self.parentViewController as? YourCustomPagerTabController
        let index = pageViewController = pageViewController.currentIndex
```

**Comment by santiagofm** [comment]
As said by @DylanModesitt , use `currentIndex` property to get the index of the current `childViewController`.

Cheers
