### ISSUE TITLE
EXC_BAD_ACCESS on dealloc

### ISSUE THREAD

**Issue by anton-g** [xmartlabs/XLPagerTabStrip#18]
There seems to be a issue when using XLSegmentedPagerTabStripViewController (and probably the other classes as well) in a UINavigationController. When pressing the 'Back'-button it crashes with an EXC_BAD_ACCESS-error. The problem seems to be that `scrollViewDidScroll:` is sent to `containerView` after it is deallocated. I have solved it by setting the containerView.delegate to nil in my subclass, but it should probably be implemented in the superclasses as well:
```
- (void)dealloc {
    self.containerView.delegate = nil;
}
```
I might submit a PR myself if i find the time and no one else does.

**Comment by mtnbarreto** [comment]
@anton-g It would be great if you could do it and make the PR.
Thanks
