### ISSUE TITLE
UIScrollView not displaying child view controller using XLPagerTabStrip

### ISSUE THREAD

**Issue by RyanHop3** [xmartlabs/XLPagerTabStrip#182]
I am implementing the ButtonBarPagerTabStripViewController and have followed the steps exactly, but the UIScrollView is not displaying the child view controllers.

code within the tabbed view controller:

    import UIKit import XLPagerTabStrip

    class MenuTabStrip: ButtonBarPagerTabStripViewController {

    override func viewDidLoad() {

    self.settings.style.selectedBarHeight = 5.0
    self.settings.style.selectedBarBackgroundColor = UIColor.blueColor()

    super.viewDidLoad()

    // Do any additional setup after loading the view.
    }
    override func didReceiveMemoryWarning() {
    super.didReceiveMemoryWarning()
    // Dispose of any resources that can be recreated.
    }

    override func viewControllersForPagerTabStrip(pagerTabStripController: PagerTabStripViewController) -> [UIViewController]{

    return [Reminders(), testbobViewController()]
    }

example code in one of the child view controllers:

    import UIKit import XLPagerTabStrip

    class testbobViewController: UIViewController, IndicatorInfoProvider {

    override func viewDidLoad() {
    super.viewDidLoad()
 
    // Do any additional setup after loading the view.
    }
 
    override func didReceiveMemoryWarning() {
    super.didReceiveMemoryWarning()
    // Dispose of any resources that can be recreated.
    }

    func indicatorInfoForPagerTabStrip(pagerTabStripController: PagerTabStripViewController) ->   IndicatorInfo {
    return IndicatorInfo(title: "test bob")
    }

here is an image showing the connections within the button bar view controller: http://i.stack.imgur.com/DVCnW.png

**Comment by townsendeb** [comment]
How did you solve this? None of my View Controllers are showing
