### ISSUE TITLE
How to add badgeValue to Buttons on menu?

### ISSUE THREAD

**Issue by buiminhhuy** [xmartlabs/XLPagerTabStrip#187]
How to add badgeValue to Buttons on menu?
Example: 
- like as in TabarController of IOS Framework.
- Or can custom IndicatorInfo?

**Comment by DylanModesitt** [comment]
It does not look like there is badge support. You could simply make the indicator info have a number in parenthesis and update the indicators when the badge changes. Alternatively you could see <a href="http://stackoverflow.com/questions/29316177/uicollectionviewcell-adding-badge"> about adding badges to UICollectionViews (that is what the ButtonBarView is) and you could modify the class to have badges. Maybe @xsmartlabs will add it later...

**Comment by santiagofm** [comment]
You should be able to do this by creating a custom cell, please take a look to https://github.com/xmartlabs/XLPagerTabStrip/issues/331#issuecomment-299292215.

Cheers

**Comment by RohanJain70** [comment]
@DylanModesitt May i know how can i update the indicators when the badge value changes. 

In my case, I do have 2 tabs in which for only second tab i need to update the badge value. 

Which is the method i need to use to change the Indicator info appropriately which i get from web API response.

**Comment by RohanJain70** [comment]
I tried in this way from a childviewcontroller to update its own Tab header
`                    if let pagerTabStrip = self?.parent as? PagerTabStripViewController {
                        self?.itemInfo.title = "New Requests \(response.count)"
                        self?.indicatorInfo(for: pagerTabStrip)
                    }` 
But still its not updating the title in the tab

**Comment by buiminhhuy** [comment]
@RohanJain70 Ro
You should use method below, it call at parent which contain tabs:
DispatchQueue.main.async {
            self.buttonBarView.reloadData()
        }

**Comment by junweimah** [comment]
@RohanJain70 
Did you get it to work? 
How do you change the badge number programmatically? 
I couldn't do it with the codes above

**Comment by Bo-Bogdan** [comment]
```
if let pagerTabStrip = self?.parent as? ButtonBarPagerTabStripViewController { pagerTabStrip.buttonBarView.reloadData()
}
```
