### ISSUE TITLE
ViewDidAppear Called Twice - verified with Demo Version

### ISSUE THREAD

**Issue by Sydney-o9** [xmartlabs/XLPagerTabStrip#189]
Hi Team,

I have noticed that the first time the Pager loads, ViewDidAppear is called twice on the same instance.

To reproduce, is really straight-forward from the demo version:

1 -  Add ViewDidAppear to TableChildExampleViewController

<img width="591" alt="screen shot 2016-07-06 at 4 13 11 pm" src="https://cloud.githubusercontent.com/assets/1480617/16609154/f2af5a34-4394-11e6-80a3-3e40d0d66523.png">

2 - Build

<img width="372" alt="screen shot 2016-07-06 at 4 15 12 pm" src="https://cloud.githubusercontent.com/assets/1480617/16609156/fd9d3e84-4394-11e6-93ec-a35d16364699.png">

3 - Look terminal

<img width="668" alt="screen shot 2016-07-06 at 4 15 22 pm" src="https://cloud.githubusercontent.com/assets/1480617/16609159/0010e490-4395-11e6-85d1-f9d07cd02669.png">

**Comment by kansaraprateek** [comment]
Hi Sydney-o9,

I was having the same issue. You can  fixed it by commenting/removing two lines in PagerTabStripViewController.swift .

224 -> childController.beginAppearanceTransition(true, animated : false)
229 -> childController.endAppearanceTransition()

**Comment by kvukusic1** [comment]
I have fixed this problem in my project overriding the `shouldAutomaticallyForwardAppearanceMethods` method.
See [documentation](https://developer.apple.com/reference/uikit/uiviewcontroller/1621389-shouldautomaticallyforwardappear?language=objc) for more info.
