### ISSUE TITLE
Question: Why you deprecated using minimumInteritemSpacing in ButtonBarPagerTabStripViewController ?

### ISSUE THREAD

**Issue by OEA** [xmartlabs/XLPagerTabStrip#191]
Hello folks,

I was wondering the question that why minimumInterItemSpacing is deprecated in ButtonBarPagerTabStripViewController ?

Cause' I'm using XLPagerTabStrip as dynamically, I mean I should change the style dynamically and sometimes I have to use minimumInteritemSpacing. So I fixed the problem changing 

from `flowLayout.minimumInteritemSpacing = 0`  to `flowLayout.minimumInteritemSpacing = settings.style.buttonBarMinimumInteritemSpacing ?? flowLayout.minimumInteritemSpacing` and it can change dynamically. If it brokes or changes something about dynamics of UI I must know.

If there is no any problem, could you update the repo according this bug(?).

Kind Regards.

**Comment by ataibarkai** [comment]
+1 wondering why this has been deprecated

**Comment by fotiDim** [comment]
@OEA @ataibarkai you can still have access to `minimumInterItemSpacing ` using:

```
let flow = self.buttonBarView.collectionViewLayout as! UICollectionViewFlowLayout
flow.minimumInteritemSpacing = 20;
```

**Comment by santiagofm** [comment]
Closing because this is fixed on the master branch already.
