### ISSUE TITLE
IBOutlet cannot connect 

### ISSUE THREAD

**Issue by Shannon-Yang** [xmartlabs/XLPagerTabStrip#193]
Xcode：v7.3.1 ，     XLPagerTabStrip：v5.0  ，    Carthage：v0.16.2

I met a problem，I have inherited SegmentedPagerTabStripViewController viewController,like this:

<img width="811" alt="2016-07-14 10 41 58" src="https://cloud.githubusercontent.com/assets/9735368/16826414/aac5bc92-49af-11e6-9960-f27f05131de0.png">

I created a xib for this view controller，add a UISegmentedControl and UIScrollView，but When I related segment through xib, can not connect，

<img width="757" alt="11879cfa-2eeb-46f1-88af-e1ac220604c7" src="https://cloud.githubusercontent.com/assets/9735368/16826574/f85f57dc-49b0-11e6-9059-8a0948a83c12.png">

who can help me ，what should I do ？

**Comment by serhatsezer** [comment]
You can connect IBOutlets from top ViewController icon. But this framework is not helpful enough. I decide to use another frameworks.

**Comment by elsurudo** [comment]
Same issue – I couldn't connect the IBOutlets. I think the code is outdated for the current version of Swift/Xcode

**Comment by ThoseGuysInTown** [comment]
@serhatsezer what framework did you use? It's causing a lot of problems for me too.

**Comment by elsurudo** [comment]
@ThoseGuysInTown for what it's worth, I ended up going with https://github.com/maxep/MXSegmentedPager

**Comment by AkramIsmail** [comment]
Did anyone find a solution about this issue??
