### ISSUE TITLE
TwitterPagerTabStripSettings() titleColor does not work. 

### ISSUE THREAD

**Issue by JorgeAGomez** [xmartlabs/XLPagerTabStrip#195]
Using Version 7.3.1 (7D1014)
I am implementing the TwitterPagerTabStrip. 

I am trying to change the color of the title and the dots but it does not work. The app does not crash or anything it just does not do anything. 

Any comments or suggestions? Thanks in advance. 

Here is a screenshot of the code: 

<img width="713" alt="screenshot 2016-07-26 13 19 16" src="https://cloud.githubusercontent.com/assets/6026875/17152116/b9ee7578-5333-11e6-8b1e-2bf705c9d9c0.png">

**Comment by DylanModesitt** [comment]
You need to set settings before `super.viewDidLoad()`

**Comment by pluckq** [comment]
same issue, even with viewDidLoad() in the end

**Comment by pluckq** [comment]
Need to implement 
`       changeCurrentIndexProgressive = {(oldCell: ButtonBarViewCell?, newCell: ButtonBarViewCell?, progressPercentage: CGFloat, changeCurrentIndex: Bool, animated: Bool) -> Void in
            guard changeCurrentIndex == true else { return }
            oldCell?.label.textColor = UIColor.blackColor()
            newCell?.label.textColor = UIColor.blackColor()
        }`

**Comment by DylanModesitt** [comment]
What is the source of the crash if you step through it?

**Comment by fedeojeda95** [comment]
Hi @JorgeAGomez 

As it was mentioned before, all the styles must be set before the call to `super.viewDidLoad()` or they won't be set. 

Hope it helps! Regards,
