### ISSUE TITLE
Swift 3

### ISSUE THREAD

**Issue by nschucky** [xmartlabs/XLPagerTabStrip#196]
it'd be cool to have a swift 3 version, if you have any interest to create a branch i would like to help with that.

**Comment by KelvinJin** [comment]
This is a working version. https://github.com/KelvinJin/XLPagerTabStrip/tree/swift3_alex

**Comment by kevinonik** [comment]
Too many errors in library

**Comment by kevinonik** [comment]
![screen shot 2016-09-11 at 11 33 44 am](https://cloud.githubusercontent.com/assets/10392416/18415662/b06eb9a4-7813-11e6-9473-cc9e03c7db4a.png)

**Comment by grizzly** [comment]
Any news on that? Is this project still alive?

**Comment by kevinonik** [comment]
Its basically going to work on xcode 8. I had xcode 7.3.1

**Comment by grizzly** [comment]
@kevinonik you mean the swift 3 branch?

**Comment by kevinonik** [comment]
yes

**Comment by onthebeachh** [comment]
pod 'XLPagerTabStrip', :git => 'https://github.com/KelvinJin/XLPagerTabStrip', :branch => 'swift3'

it works for me, thanks!

**Comment by chandanch** [comment]
Hello try it in Xcode 8 it works.
