### ISSUE TITLE
Error on ios8

### ISSUE THREAD

**Issue by mkaya93** [xmartlabs/XLPagerTabStrip#197]
Hi,

This is working perfect on ios 9 but I'm getting this error on ios 8 devices.

`fatal error: use of unimplemented initializer 'init(nibName:bundle:)' for class`

```

init(style: UITableViewStyle, itemInfo: IndicatorInfo) {
        self.itemInfo = itemInfo
        super.init(style: style)
    }
```

**Comment by mkaya93** [comment]
anything ? @xmartlabs

**Comment by mkaya93** [comment]
It's still happening

**Comment by abcde1499** [comment]
Same here

**Comment by santiagofm** [comment]
Could reproduce this issue in the Example project with `TableChildExampleViewController`, seems iOS 8 calls that init because reasons. To fix it just implement the init:

```swift
override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
    super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
}
```

Cheers
