### ISSUE TITLE
How can change from one view controller to another one programmatically?

### ISSUE THREAD

**Issue by JorgeAGomez** [xmartlabs/XLPagerTabStrip#201]
I want to add a button in the navigation bar, and then once they click the button, it would go to the next view controller. (I want to be able to swipe left or right to change view controllers but also be able to pressed the button and change view controllers.

**Comment by Urkman** [comment]
moveToViewController(at: x)

**Comment by AashishSapkota** [comment]
Should we need to confirm some delegates? Or, Can you provide us with a little more codes please.. Getting error with unidentified identifiers.

**Comment by happiehappie** [comment]
I receive Unbalanced calls to begin/end appearance transitions for in my console. Was wondering if anyone has a proper solution?

**Comment by santiagofm** [comment]
Hi!
The proper way to do this is using `moveToViewController(at: index)`, the `unbalanced calls to begin/end appearance transitions` error is fixed on the master branch.

Cheers
