### ISSUE TITLE
Segues 

### ISSUE THREAD

**Issue by asafall** [xmartlabs/XLPagerTabStrip#203]
I would like if you do a UIStoryboardSegue between the ButtonBarPagerTabStripViewController
and the ChildExampleViewControllers like the UITabbarViewController.

**Comment by santiagofm** [comment]
Relationships segues are handled by the interface builder and cannot be created manually if the viewcontroller isn't a `UITabbarViewController`, `UINavigationController`, etc. 

A workaround would be to make the `PagerTabStripViewControler` a *dummy* `UITabbarViewController` just to have that ability.

I'll add this as a feature request to our backlog.

Cheers
