### ISSUE TITLE
I got an error in PagerTabStripViewController.swift

### ISSUE THREAD

**Issue by ElaneirzGard** [xmartlabs/XLPagerTabStrip#205]
When I run project, I got an error like this.
fatal error: Every view controller provided by PagerTabStripDataSource's viewControllersForPagerTabStrip method must conform to  InfoProvider: file /Users/elaneirz/Documents/FileXcode/XLPagerTabStrip2/Pods/XLPagerTabStrip/Sources/PagerTabStripViewController.swift, line 363
(lldb) 

that is this method >
viewControllers.forEach { if !($0 is IndicatorInfoProvider) { fatalError("Every view controller provided by PagerTabStripDataSource's viewControllersForPagerTabStrip method must conform to  InfoProvider") }}

How to fix them?

thankyou

**Comment by ryantan** [comment]
The view controllers you return in your `viewControllersForPagerTabStrip` must implement the `IndicatorInfoProvider` protocol, e.g.

    extension YourViewController: IndicatorInfoProvider {
        func indicatorInfoForPagerTabStrip(pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
            return itemInfo
        }
    }

**Comment by nhatlee** [comment]
@ryantan : how to implement `itemInfo `?

**Comment by ryantan** [comment]
@nhatlee here's an example for a simple text based one:  `var itemInfo = IndicatorInfo(title: "Your tab title here")`

**Comment by x-hovo-x** [comment]
@ryantan got the same error after migration to swift 3. BUT runtime not compile.
Before migration swift 2.3 works

Podfile
pod 'XLPagerTabStrip', '~> 6.0'

Any idea?

**Comment by rockarloz** [comment]
The same error .
Some update?

**Comment by nahouto** [comment]
same error on 5.1.0

**Comment by fedeojeda95** [comment]
Hi,

As it was previously mentioned, the childViewController (the ones returned in the method `override func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController]`) MUST implement the `IndicatorInfoProvider` protocol. This is the way that each tab can know its title or icon. 

The method it must implement is `func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo`. This returns an `IndicatorInfo` which has several `inits`. See the documentation or the code for further information about it. 

Hope it helps! Regards,

**Comment by ntminh2712** [comment]
Hi i'm newbie ,
I have a button, how do I press this button to switch to another screen while keeping the menu?

**Comment by YairFitness360** [comment]
Hey. did you manage to solve this problem? same prob in my project.

**Comment by dmitrysenkovich** [comment]
Make it helps somebody: I managed to fix the issue the following way (in my case only, of course):
1. go to storyboard
2. choose every child view controller
3. go to the tab you're setting custom class for it
4. verify the 'inherit module from target' checkbox is checked

**Comment by bhejhedayah** [comment]
> When I run project, I got an error like this.
> fatal error: Every view controller provided by PagerTabStripDataSource's viewControllersForPagerTabStrip method must conform to InfoProvider: file /Users/elaneirz/Documents/FileXcode/XLPagerTabStrip2/Pods/XLPagerTabStrip/Sources/PagerTabStripViewController.swift, line 363
> (lldb)
> 
> that is this method >
> viewControllers.forEach { if !($0 is IndicatorInfoProvider) { fatalError("Every view controller provided by PagerTabStripDataSource's viewControllersForPagerTabStrip method must conform to InfoProvider") }}
> 
> How to fix them?
> 
> thankyou

same error how to fix this??

**Comment by Nagendra-nagy** [comment]
Add it to the checklist: 

- Cross-check whether you set the StoryBoard ID or not.

If you don't set the StoryBoard ID, it throws the same error as listed above.
