### ISSUE TITLE
Set initially visible ViewController

### ISSUE THREAD

**Issue by Urkman** [xmartlabs/XLPagerTabStrip#206]
After adding a lift of ViewController to the pager now can I set the visible ViewController?
Currently always the first one is shown...

**Comment by Urkman** [comment]
"moveToViewController(at: x)" in viewDidLoad did it :)

**Comment by happiehappie** [comment]
Sorry just to clarify, do you add this to the "main" vc?

**Comment by happiehappie** [comment]
Cause I receive Unbalanced calls to begin/end appearance transitions for (insert ProjectName.ControllerName here)" in my console

**Comment by darrenbrooke** [comment]
You can actually call moveToViewController in the viewControllers method.   PagerTabStrip has code to allow this - all it does is set the currentIndex which is used to layout the controllers.  This stops the unbalanced calls warning.

**Comment by musbaalbaki** [comment]
moveToViewController(at: x) using the ButtonBarPagerTabStripViewController is not working for me
