### ISSUE TITLE
How can i change the color of separator

### ISSUE THREAD

**Issue by iAviatorJose** [xmartlabs/XLPagerTabStrip#211]
Xcode 7.3.1, 
Min. Deployment Target: iOS 8.0

PFB the Below Image for clear description of the Problem. i see orange color seperator

![simulator screen shot 22-aug-2016 3 20 34 pm](https://cloud.githubusercontent.com/assets/8208627/17850774/6242cfc8-687c-11e6-86ab-6c49413f7dc1.png)

**Comment by BenJamesMartin** [comment]
@iAviatorJose I was having the same issue. If you're setting style attributes in `viewDidLoad` (like the documentation does), make sure to call `super.viewDidLoad()` **after** you set the style attributes, not before. That fixed it for me.
