### ISSUE TITLE
Can't segue using performSegueWithIdentifier() 

### ISSUE THREAD

**Issue by JorgeAGomez** [xmartlabs/XLPagerTabStrip#213]
I am using TwitterPagerTabStripViewController. I created 9 children. ( 9 UITableViewControllers).

I have a UIBarButton that is only visible in the last child, child 9. When this button is clicked it should run performSegueWithIdentifier(). However, It apparently does not recognize the identifier. I set the segue on the storyboard with Identifier "gogo" and then in my code performSegueWithIdentifier("gogo", sender: self).

I always get this error: 

2016-08-22 09:40:14.472 onboarding[52751:2638030] **\* Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: 'Receiver (<onboarding.QuestionnarieVC: 0x7f9a3401fc00>) has no segue with identifier 'gogo''

<img width="964" alt="screenshot 2016-08-22 08 48 52" src="https://cloud.githubusercontent.com/assets/6026875/17861150/2cfbaf94-684d-11e6-9140-537c1a136202.png">
<img width="576" alt="screenshot 2016-08-22 08 50 30" src="https://cloud.githubusercontent.com/assets/6026875/17861165/35a2577e-684d-11e6-9d49-f398cdc674a3.png">

**Comment by JorgeAGomez** [comment]
![screenshot 2016-08-22 09 46 57](https://cloud.githubusercontent.com/assets/6026875/17861234/71c15a5c-684d-11e6-83f0-163fbaba35fe.png)

**Comment by JorgeAGomez** [comment]
![screenshot 2016-08-22 09 49 29](https://cloud.githubusercontent.com/assets/6026875/17861306/bf777402-684d-11e6-9094-e3c39a6ca311.png)

**Comment by JorgeAGomez** [comment]
Also, if I use showViewController() or pushViewController it returns a black screen. 
<img width="573" alt="screenshot 2016-08-22 15 56 28" src="https://cloud.githubusercontent.com/assets/6026875/17873134/0620879e-6881-11e6-9638-1dc2a1d6d799.png">

**Comment by ThoseGuysInTown** [comment]
Did you ever figure this out?

**Comment by JorgeAGomez** [comment]
No. I ended up using a different framework.

**Comment by ThoseGuysInTown** [comment]
I see, what did you use?

**Comment by iamsonumalik** [comment]
Hello @JorgeAGomez ,  Can you please tell me which framework you are using now?
