### ISSUE TITLE
Unknown class ButtonBarView in Interface Builder file.

### ISSUE THREAD

**Issue by andrewabdalla** [xmartlabs/XLPagerTabStrip#218]
I followed all the steps correctly and my project is building successfully but I continue to receive this error right before the view loads.

"Unknown class ButtonBarView in Interface Builder file."

What am I missing?

Thanks!

**Comment by anafinotti** [comment]
Do you have a solution?

**Comment by AntiPavel** [comment]
Why this closed?
I have the same problem:
Unknown class ButtonBarView in Interface Builder file.

**Comment by anafinotti** [comment]
You have to set a cell identifier - "Cell"
And set the module to the ButtonBarView - XLPagerTabStrip
![screen shot 2016-09-16 at 10 35 16 am](https://cloud.githubusercontent.com/assets/5528817/18591720/60bf89e4-7bf9-11e6-8fb6-788c714938de.png)
![screen shot 2016-09-16 at 10 35 31 am](https://cloud.githubusercontent.com/assets/5528817/18591721/60bf7bf2-7bf9-11e6-8add-7bf7f951c8a4.png)
![screen shot 2016-09-16 at 10 35 36 am](https://cloud.githubusercontent.com/assets/5528817/18591722/60c578ae-7bf9-11e6-89c4-aaca4bb22a0b.png)

**Comment by AntiPavel** [comment]
Thank you!
I already did it 5 hours ago)

**Comment by nguyenkhiemit** [comment]
@anafinotti : I do same you say but It error still happen. "Unknown class ButtonBarView in Interface Builder file.". How to fix it ??

**Comment by VimalDas** [comment]
do not delete the cell.

give the cell class as ButtonBarViewCell and identifier as Cell and module as XLPagerTabStrip

collectionview will have class as ButtonBarView and module as XLPagerTabStrip

connect the outlet of collectionview (as in tutorial).
