### ISSUE TITLE
Cascading pager tab strip

### ISSUE THREAD

**Issue by bkatgithub** [xmartlabs/XLPagerTabStrip#219]
Hi,

I just downloaded the latest version of XLPagerTabStrip and am experimenting with it by tweaking existing examples.  I added an extra tab and the corresponding child view controller class and the view controller in my storyboard.  When I run it it shows content as expected but it also shows the second tab strip (shown below).  What am I doing wrong here?  Thanks for any pointers.

My child view controller class looks like this.  I just copy/pasted from ChildExampleViewController.swift class in the example and modified the viewDidLoad func to get the view controller from storyboard.

```swift
import Foundation
import XLPagerTabStrip

class NameViewController: UIViewController, IndicatorInfoProvider {

    var itemInfo: IndicatorInfo = "Name"

    init(itemInfo: IndicatorInfo) {
        self.itemInfo = itemInfo
        super.init(nibName: nil, bundle: nil)
    }

    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }

    override func viewDidLoad() {
        super.viewDidLoad()

        let vc = UIStoryboard(name: "Storyboard", bundle: nil).instantiateViewControllerWithIdentifier("nameView")
        addChildViewController(vc)
        view.addSubview(vc.view)
    }

    func indicatorInfoForPagerTabStrip(pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        return itemInfo
    }
}
```

And I get the child view controller like this

```swift
    override func viewControllersForPagerTabStrip(pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {
        let child_1 = NameViewController(itemInfo: "Name")      // <-- call to child view controller I created
        let child_2 = TableChildExampleViewController(style: .Plain, itemInfo: "Simpsons")
        let child_3 = TableChildExampleViewController(style: .Grouped, itemInfo: "Table View 2")
        let child_4 = ChildExampleViewController(itemInfo: "View 2")
        let child_5 = TableChildExampleViewController(style: .Plain, itemInfo: "Table View 3")
        let child_6 = ChildExampleViewController(itemInfo: "View 3")
        let child_7 = TableChildExampleViewController(style: .Grouped, itemInfo: "Table View 4")
        let child_8 = ChildExampleViewController(itemInfo: "View 4")

       ...
```

When I run it it shows the second tab strip as shown in this screen capture.  If I scroll over to other tabs, 'Simpsons' for example then it shows correctly.  It's only when I go to the 'Name' tab that the second tab strip shows.

![screen shot 2016-09-10 at 1 04 41 pm](https://cloud.githubusercontent.com/assets/5351139/18412383/c95f42c6-775a-11e6-951d-2ad1c90b4298.png)

**Comment by santiagofm** [comment]
Hey @bkatgithub ! The issue is a bit weird but is probably related to the code in your `viewDidLoad()` that instantiates a `nameView` and then adds it as a child. If you have your viewController in a storyboard why aren't you instantiating it using the storyboard in `viewControllersForPagerTabStrip(...)` ?

Cheers
