### ISSUE TITLE
moveToViewControllerAtIndex: in viewDidLoad or viewWillAppear is not reflected in buttonBarView

### ISSUE THREAD

**Issue by kevincador** [xmartlabs/XLPagerTabStrip#22]
I need to load on a specific page. For that, I tried to call moveToViewControllerAtIndex: in viewDidLoad and in viewWillAppear but the buttonBarView doesn't scroll on the right menu item.
Doing it in viewDidAppear works but is animated and perceivable. I need to load the view on the right tab without animation/glitch.
Thanks for your help.

**Comment by mtnbarreto** [comment]
@kevincador now it should work! Check master branch out!
