### ISSUE TITLE
BaseButtonBarPagerTabStripViewController not letting me connect iboutlets

### ISSUE THREAD

**Issue by kevinonik** [xmartlabs/XLPagerTabStrip#220]
Hello,

I have been trying to replicate the youtubeexampleviewcontroller  example.
But whenever i make a subclass of BaseButtonBarPagerTabStripViewController the storyboard doesnt let me conncet iboutlests of barbutton and containerview.

any solution?

**Comment by narlei** [comment]
Any solution>

**Comment by DilyanaTodorova** [comment]
I have the same problems. It seems like the storyboards doesn't look very well with generic view controllers.
