### ISSUE TITLE
How to add a fixed view above the pager tab? 

### ISSUE THREAD

**Issue by anafinotti** [xmartlabs/XLPagerTabStrip#221]
![screen shot 2016-09-12 at 10 09 40 pm](https://cloud.githubusercontent.com/assets/5528817/18460268/a95534cc-7935-11e6-8c31-178bd025b79e.png)

Can you guys help me? Thanks!

**Comment by Emasoft** [comment]
I need to do this too. Is there a "SetHeaderView" method?

**Comment by mtnbarreto** [comment]
There is no such SetHeaderView property. 
A solution could be adding a containerView to hold the XLTabBarStrip controller, I mean using container views.

For more information take a look at apple doc: https://developer.apple.com/library/content/featuredarticles/ViewControllerPGforiPhoneOS/ImplementingaContainerViewController.html
