### ISSUE TITLE
Changing color of header and refreshing pager header

### ISSUE THREAD

**Issue by aferrerb** [xmartlabs/XLPagerTabStrip#233]

**Comment by aferrerb** [comment]
Hello,
I am using the latest version of XLPagerTab Strip for Xcode - not swift! 
I want to be able to refresh the header banner in the container view from a view controller. The user has an option in one of the the children VC to change the "Theme", this means changing the color of the container's header.
But I can't get the header to change when the user selects a new theme. All I want is that the container header is re-drawn, but I am not able to do it. 
Would you be able to help?
Thanks very much.

**Comment by santiagofm** [comment]
Hi @aferrerb !
I don't quite understand the issue and what are you trying to achieve. Could you be more specific and perhaps post some code ?

Cheers

**Comment by psarakism** [comment]
Hello I have the same "issue" . I want from a child ViewController to change the settings.style.buttonBarBackgroundColor for example. Is this possible ?
