### ISSUE TITLE
Wrong selectedBar

### ISSUE THREAD

**Issue by mrxprt** [xmartlabs/XLPagerTabStrip#234]
Hey all , 

  I got a very strange Bug with the **selectedBar** Check the video below : 
https://www.dropbox.com/s/e1wdc07ttotkjbx/XLPagerTabStrip-Bug.m4v?dl=0

**Bug Description :** 

The problem is that when I used the Scrollview to slide  right/left there is no problem , but when touch on the headers it will go wrong if you do this scenario : 
- Click on Tab 3
- Click on Tab 1
- the  **selectedBar** will be shown under Tab 2 and not Tab 1 

**Code & views  :** 

I'm calling configureButtonBarPagerTabStripViewController() on  viewDidLoad() 

```
func configureButtonBarPagerTabStripViewController ( ) {

        // change selected bar color
        settings.style.buttonBarBackgroundColor = ChartColorTemplates.colorFromString(COLOR_PURPLE_LIGHT)
        settings.style.buttonBarItemBackgroundColor = UIColor.clearColor()
        settings.style.selectedBarBackgroundColor = ChartColorTemplates.colorFromString(COLOR_PINK)
        settings.style.buttonBarItemFont = UIFont(name: "HelveticaNeue-Light", size:14) ?? UIFont.systemFontOfSize(14)
        settings.style.selectedBarHeight = 3.0
        settings.style.buttonBarMinimumLineSpacing = 0
        settings.style.buttonBarItemTitleColor = .whiteColor()
        settings.style.buttonBarItemsShouldFillAvailiableWidth = true

        settings.style.buttonBarLeftContentInset = 10
        settings.style.buttonBarRightContentInset = 10

        changeCurrentIndexProgressive = { (oldCell: ButtonBarViewCell?, newCell: ButtonBarViewCell?, progressPercentage: CGFloat, changeCurrentIndex: Bool, animated: Bool) -> Void in
            guard changeCurrentIndex == true else { return }
            oldCell?.label.textColor = ChartColorTemplates.colorFromString(COLOR_UNSELECTED_TEXT)
            newCell?.label.textColor = .whiteColor()
        }
    } 
```
- ButtonBarView : 

![screen shot 2016-09-26 at 3 18 35 pm](https://cloud.githubusercontent.com/assets/639276/18834069/9c87f302-83fc-11e6-85eb-50d90ee9eba7.png)
- UIScrollView :

![screen shot 2016-09-26 at 3 16 34 pm](https://cloud.githubusercontent.com/assets/639276/18834068/9c87e088-83fc-11e6-8f8b-10c54f89cfa1.png)

Additional Data : 
- XLPagerTabStrip Version : 5.0
- Xcode version :  7.3.1 . 
- iOS version : >8 

Thanks a lot

**Comment by dighechinmay** [comment]
Hi guys,

I am still getting this issue. Just to make sure  I am using : 

XlPagerTabStrip v 7.0
Xcode version : 8.3.2
IOS > 9

It is strange that the example code just works fine, but if I try to do it in my app it doesn't work.help will be appreciated.

![image](https://cloud.githubusercontent.com/assets/11444231/26524932/afc9159a-4314-11e7-840e-b4468864141d.png)

**Comment by santiagofm** [comment]
hey @dighechinmay ! Would you mind uploading a sample project to reproduce the issue ?
Cheers

**Comment by dighechinmay** [comment]
Hi @santiagofm ,

Thanks for this idea of creating a new project. Infact this helped find a bug in my code. I was overriding viewDidAppear all the time which was causing this error. Like this : 

`
override func viewDidAppear(_ animated: Bool) {
        
        
        UIApplication.shared.statusBarStyle = .lightContent
        
        
    }
`

I  didn't notice that the ViewController File was inheriting from ButtonBarPagerTabStripViewController and not usual UIViewController. SO solution : 

`
override func viewDidAppear(_ animated: Bool) {
        
        super.viewDidAppear(animated)
        UIApplication.shared.statusBarStyle = .lightContent
        
        
    }
`


Best
Chinmay

**Comment by AppiMuqtadir** [comment]
Above solution didn't work for me. Is there any other place I need to make changes at?

**Comment by hermancoma** [comment]
Thanks @dighechinmay it worked like a charm!
