### ISSUE TITLE
Odd space between Pager and child view controller

### ISSUE THREAD

**Issue by richardblakeneywilliams** [xmartlabs/XLPagerTabStrip#237]
Can't work out whats causing this. It is clearly preventing me from using a container view below it. Has anyone come accross this before? I think it is related to contraints. 

I'm getting this error in the console.

The relevant UICollectionViewFlowLayout instance is <UICollectionViewFlowLayout: 0x7fa70b8420f0>, and it is attached to <UICollectionView: 0x7fa7030dee00; frame = (0 0; 375 115); clipsToBounds = YES; autoresize = RM+BM; gestureRecognizers = <NSArray: 0x7fa70b8411a0>; layer = <CALayer: 0x7fa70b83f1d0>; contentOffset: {0, 0}; contentSize: {0, 211}> collection view layout: <UICollectionViewFlowLayout: 0x7fa70b8420f0>.

![weirderror](https://cloud.githubusercontent.com/assets/8590263/18906778/6ed7a23e-85c5-11e6-8e7e-ce07f212bd20.gif)

- Environment: Xcode 8/Xcode 7.3.1 (got two branches for Swift 2.2/3), happening on both.

**Comment by mkaya93** [comment]
@richardblakeneywilliams how did you solve it ? I have a same issue.

**Comment by richardblakeneywilliams** [comment]
@mkaya93 I just copied and pasted the relevant IB part from the example to my storyboard, made sure code was the same as the example. Honestly have no idea what was causing this.
