### ISSUE TITLE
How to change the height of selectedBa.

### ISSUE THREAD

**Issue by Samverylazy** [xmartlabs/XLPagerTabStrip#24]
Hi, I can change the selectedBar color by [self.buttonBarView.selectedBar setBackgroundColor:[UIColor redColor]],  but is there a way to change the height of selectedBar?

Thanks a lot.

**Comment by alexcosmin** [comment]
I would like to change the height as well.
Seems like it's hardcoded in **XLButtonBarView** to 5.
```obj-c
-(UIView *)selectedBar
{
    if (_selectedBar) return _selectedBar;
    _selectedBar = [[UIView alloc] initWithFrame:CGRectMake(0, self.frame.size.height - 5, self.frame.size.width, 5)];
    _selectedBar.layer.zPosition = 9999;
    _selectedBar.backgroundColor = [UIColor blackColor];
    return _selectedBar;
}
```

**Comment by Samverylazy** [comment]
Thanks, Alex

**Comment by gizmoboy7** [comment]
It doesn't work, any idea why ?
