### ISSUE TITLE
ButtonBarView was transparent

### ISSUE THREAD

**Issue by tannt275** [xmartlabs/XLPagerTabStrip#241]
I use a ViewController as MyViewController: ButtonBarPagerTabStripViewController.
When i navigate to MyViewController via self.navigationController.pushNavigation, the ButtonBarView appear but it becomes Transparent (so i can not see every tab i add to child ViewController).
Who can help me pls?

**Comment by alvatech** [comment]
I'm facing the same issue.  @tannt275  Did you able to figure out the fix ?

**Comment by fedeojeda95** [comment]
Hi @tannt275 

Could you provide as a picture and some code to be able to further see into the problem? I can't think of something that could lead into this problem.

Cheers,
