### ISSUE TITLE
Using the pod in objc project [setValue:forUndefinedKey]

### ISSUE THREAD

**Issue by Yoloabdo** [xmartlabs/XLPagerTabStrip#247]
I'm trying to add the youtube button style to my hybrid objc-swift project, I'm trying to initiate the class before the storyboard as i've found in previous questions in my appdelegate in objc 

```
MainUserProfileViewController * = [[MainUserProfileViewController alloc]
                                             initWithNibName:nil bundle:nil];
```

but the compiler is complaining and doesn't recognize the class at all, any other class working fine, any thoughts?

**Comment by santiagofm** [comment]
Hi @Yoloabdo, are you still experiencing this issue ?

Cheers
