### ISSUE TITLE
Cannot find the Framework when installed via cocoa pods .

### ISSUE THREAD

**Issue by MarcSteven** [xmartlabs/XLPagerTabStrip#248]
The version of my Xcode is the latest (8.0).I installed the library via cocoa pods .The XLPagerTabStrip is 5.0.When I installed it ,it cannot import the related file into my custom swift files.Any advices to solve it ...

**Comment by brunodeandrade** [comment]
I have this problem too.

**Comment by santiagofm** [comment]
Hey guys !

Have you had the same issue using our latest release ?

Cheers

**Comment by santiagofm** [comment]
Closing due to lack of response
