### ISSUE TITLE
Adding Header

### ISSUE THREAD

**Issue by cerupcat** [xmartlabs/XLPagerTabStrip#25]
I'm curious if it's possible to add a header above the tab and make it so the pager remains sticky at the top once scrolled up.

**Comment by mtnbarreto** [comment]
@cerupcat You can add any XLPagerTabStripViewController as a childViewController using storyboards.    
In fact the example project storyboard does that.
regards

**Comment by zxy198717** [comment]
@mtnbarreto 
I think @cerupcat wants the feature like this [https://github.com/noties/Scrollable], is it possible?
