### ISSUE TITLE
Child tabs are not positioned properly Using swift 2.3 Xcode 8 [Solved]

### ISSUE THREAD

**Issue by mohammadghk** [xmartlabs/XLPagerTabStrip#253]
Im using Xcode 8 and swift 2.3
I had the same problem to #252 when I was not using `buttonBarView` Outlet (it works fine without navigation bar)
but when I used a `collectionView` and connected the buttonBarView Outlet it fixed the navigation bar issue but when the view appears tabs are not positioned properly

finally I found the **solution**
at first it needs to use  a collection view on top of your containerView and then set it's class property to ButtonBarView and set the module to `XLPagertabStrip` then connect the `buttonBarView` Outlet

after that go to your pods section in the project and inside of XLPagerTabStrip find the `PagerTabStripViewController.swift` and insert this line of code : 
`containerView.contentOffset.y = 0`

at the first line of `scrollPercentage()` method

It solved my problem :)

**Comment by Saruul-Ulzii** [comment]
Oh nice, its fixed. Thank you so much.

**Comment by MahmoudTarek** [comment]
Thank you dude

**Comment by ThoseGuysInTown** [comment]
Thank you so much! That bug was really annoying me.
