### ISSUE TITLE
How hide buttons bar

### ISSUE THREAD

**Issue by dkononenko** [xmartlabs/XLPagerTabStrip#254]
Hello! My logic has one or two tabs.
When one tab, I need hide the panel with buttons. How to do it correctly?

Thanks

**Comment by SamiYousef** [comment]
i have the same problem

**Comment by santiagofm** [comment]
Hey guys !

It depends a bit on the variation of the pager you are using, but you could just set the `isHidden` property of the _panel with buttons_ to true.
For example, when using a `SegmentedPagerTabStripViewController`, you just `segmentedControl.isHidden = true`.

Cheers

**Comment by iad24** [comment]
Im using ButtonBarPagerTabStripViewController. 
If I use: 
`buttonBarView.isHidden = true`
 the view still there but just hidden. You will notice an empty.

If I use:
`buttonBarView.frame = CGRect(origin: buttonBarView.frame.origin, size: CGSize(width: 0.0, height: 0.0))`
Still there will be an empty space, cos the container of the view controllers wont snap to the top.

Better to have a property to properly hide this one like setting the height constraint to 0.
There will be a use case where we don't need the tab bars and just want to the use this as a pager for our view controllers.

Great lib here btw.

**Comment by deepmode** [comment]
Hello, I am looking for the solution on doing this as well (using the "ButtonBarPagerTabStripViewController") .  Is there is a way to hide the buttonBarView completely and at the same time, the container of the view controllers can move to top accordingly.

Cheers.

**Comment by deepmode** [comment]
@iad24 
This is not the best solution and but seem too work by modifying the frame size for "buttonBarView" and  "containerView".

let buttonBarViewHeight = self.buttonBarView.frame.size.height
        buttonBarView.frame = CGRect(origin: buttonBarView.frame.origin, size: CGSize(width: 0.0, height: 0.0))
        
        var containerViewRect = self.containerView.frame
        containerViewRect.origin = buttonBarView.frame.origin
        containerViewRect.size.height = containerViewRect.size.height + buttonBarViewHeight
        self.containerView.frame = containerViewRect

**Comment by andela-hchukwu** [comment]
Has anybody got a better solution??

**Comment by evenckus** [comment]
For buttonBarView, the best solution I found was to put all content and buttonBarView to StackView and then just change buttonBarView.isHidden value, StackView then takes care of that unused space when hiding buttonBarView.

**Comment by denizmersinlioglu** [comment]
Based on @deepmode's answer this kind of extension works for me
```
extension ButtonBarPagerTabStripViewController {
    
    var buttonBarViewHeight: CGFloat { 44 }
    
    func hideButtonBarView() {
        let size = buttonBarView.frame.size
        buttonBarView.frame = CGRect(
            origin: buttonBarView.frame.origin,
            size: .init(width: size.width, height: 0)
        )
        
        var containerViewRect = containerView.frame
        containerViewRect.origin = buttonBarView.frame.origin
        containerViewRect.size.height = containerViewRect.size.height + buttonBarViewHeight
        containerView.frame = containerViewRect
    }
    
    func showButtonBarView() {
        let size = buttonBarView.frame.size
        buttonBarView.frame = CGRect(
            origin: buttonBarView.frame.origin,
            size: .init(width: size.width, height: buttonBarViewHeight)
        )
        
        var containerViewRect = containerView.frame
        let containerViewOrigin = containerViewRect.origin
        containerViewRect.origin = CGPoint(
            x: containerViewOrigin.x,
            y: containerViewOrigin.y + buttonBarViewHeight
        )
        containerViewRect.size.height = containerViewRect.size.height - buttonBarViewHeight
        containerView.frame = containerViewRect
    }
    
}
```

**Comment by League2EB** [comment]
@deepmode @denizmersinlioglu @dkononenko 
I am not sure if anyone is still using this warehouse.
In response to this issue, my proposed solution is as follows.

```swift
extension ButtonBarPagerTabStripViewController {

    var buttonBarViewHeight: CGFloat { 44 }

    private var buttonBarHeightConstraint: NSLayoutConstraint? {
        return buttonBarView.constraints.first { $0.firstAttribute == .height }
    }

    func hideButtonBarView() {
        guard !buttonBarView.isHidden else { return }

        buttonBarView.isHidden = true
        if let constraint = buttonBarHeightConstraint {
            constraint.constant = 0
        }

        // Expand containerView to fill the parent view's bounds
        var containerFrame = containerView.frame
        containerFrame.origin.y = 0
        containerFrame.size.height += buttonBarViewHeight
        containerView.frame = containerFrame
    }

    func showButtonBarView() {
        guard buttonBarView.isHidden else { return }

        buttonBarView.isHidden = false
        if let constraint = buttonBarHeightConstraint {
            constraint.constant = buttonBarViewHeight
        }

        // Shrink containerView and move it down
        var containerFrame = containerView.frame
        containerFrame.origin.y = buttonBarViewHeight
        containerFrame.size.height -= buttonBarViewHeight
        containerView.frame = containerFrame
    }
}
```
