### ISSUE TITLE
Is version 6.0 updated?

### ISSUE THREAD

**Issue by albertml** [xmartlabs/XLPagerTabStrip#255]
I downloaded this whole file. Run the example and working fine in Xcode 8. But when I create new project using Xcode 8 and this is my pods (pod 'XLPagerTabStrip', '~> 6.0'). After opening the .xcworkspace file it says it contains swift 2.3 and ask to convert to latest or not... If I used convert it has a lot of errors and if not, theres only 1 error. I fixed it by setting the Use legacy code in build settings to NO.. Thanks in advanced!!!

**Comment by Dev-Marjun** [comment]
Ask for conversion gone by updating my cocoa pods to the latest version.

**Comment by albertml** [comment]
Fixed by updating my cocoa pods version to latest...
