### ISSUE TITLE
how to disable left, right swipe in last page

### ISSUE THREAD

**Issue by JayHan-K** [xmartlabs/XLPagerTabStrip#258]
Hi. Every One.

how can i disable left,right swipe in last page?

plz tell me your tip!

**Comment by DanielBalsalobre** [comment]
Put this into your parent view

`override func scrollViewDidScroll(_ scrollView: UIScrollView) {
        scrollView.bounces = false
        super.scrollViewDidScroll(scrollView)
    }`

**Comment by m-revetria** [comment]
Hi @JayHan-K,

You can disable bounces in your custom pager view controller's `viewDidLoad` function:

```
class SpotifyExampleViewController: ButtonBarPagerTabStripViewController {
  override func viewDidLoad() {
    super.viewDidLoad()
    containerView.bounces = false
  }
}
```
