### ISSUE TITLE
[Feature] Contextual Toolbar 

### ISSUE THREAD

**Issue by AnthonyMDev** [xmartlabs/XLPagerTabStrip#26]
I'm implementing a `UIToolbar` that sits at the bottom of my tab strip that changes its items based upon which child page is displayed.

If I created a pull request to add this to the repository, would it get accepted?

**Comment by michaelEllisUy** [comment]
Hey Anthony, 
 You could send us your implementation and we could add it to the documentation as an example. XLPagerTabStrip wasn't originally intended to support this.

**Comment by AnthonyMDev** [comment]
My current implementation actually has an issue that would be solved by #38.

I'm going to try and make a PR that closes #38 and after that, I'll send you an example of my implementation for the toolbar!

Thanks!

**Comment by AnthonyMDev** [comment]
I've made PR #53 which will close #38 and allow me to finish my toolbar implementation. Then I will be happy to send you a demo of the implementation.
