### ISSUE TITLE
Child UITableViewController's scrollview can not scroll to bottom

### ISSUE THREAD

**Issue by imadeit** [xmartlabs/XLPagerTabStrip#260]
Thanks for such a great library!

I had a problem that when I use library with UITableViewController embedded with UINavigationBar controller, first of all I had the same issue as #252 
Then I adjust the frame of buttonBarView as follows
```swift
let originFrame = buttonBarView.frame
var offset: CGFloat = 0
let statusBarHeight = UIApplication.sharedApplication().statusBarFrame.height
offset += statusBarHeight
if let navBarHeight = self.navigationController?.navigationBar.frame.size.height {
    offset += navBarHeight
}
buttonBarView.frame = CGRectMake(0, offset, originFrame.width, originFrame.height)
```
The button bar is visible but the bottom part of UITableView can never be reached with scrolling.
I found the frame of containerView seems exceeds beyond the border that the scrollbar is going beyond the lower part of screen.
Hope someone can help me to solve this problem.

Thanks!

**Comment by santiagofm** [comment]
Hey @imadeit ! It's been some time but are you connecting the `buttonBarView` outlet ?
Regarding the scrolling issue, you didn't said if you are using the framework with storyboard or programmatically so can you provide a sample project to reproduce the issue ?

**Comment by santiagofm** [comment]
Closing due to lack of response

**Comment by anupamkgit** [comment]
@santiagofm Hi, I am facing same issue container scroll view is not moving up. please suggest how can I make container view scroll vertically as well  so that I can see my all subviews of child controller by scrolling please suggest.

**Comment by 240987** [comment]
I too have same issue, I am using through storyboard.
