### ISSUE TITLE
Cannot use Storyboard with Child ViewControllers (used for the tabs)

### ISSUE THREAD

**Issue by tkallioras** [xmartlabs/XLPagerTabStrip#261]
I have XCode 8, I am using Swift 3 and I have version 6 of XLPagerTabStrip.

I am creating a couple of UIViewControllers on my Storyboard, in order to use them as Child ViewControllers.

I am placing some test UILabels, which I successfully connect to the corresponding classes (I have connected the ViewControllers on the Storyboard with their classes).

1. When I move to the tabs no Label is visible.

2. When I try to change the text programmatically it says it finds a nil value when I run it.

Has anyone else faced the same issue before?

**Comment by indrajitsinh** [comment]
@tkallioras  since you are creating ViewController in storyboard you have to do following  , assign identifier to your child view controllers and instantiate view Controller following way 

```swift
    override func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {
        let child_1 : UIViewController = (self.storyboard?.instantiateViewController(withIdentifier: "firstVC"))!
        let child_2 : UIViewController = (self.storyboard?.instantiateViewController(withIdentifier: "secondVC"))!
        let array :  [UIViewController] = [child_1,child_2]
        return array
        
    }
```

**Comment by yosuke1985** [comment]
That doesnt work for me,
need to insert String Object to  itemInfo?
if you know, plz let me answer

**Comment by yosuke1985** [comment]
```
    var child_1 : HomeViewController{
        let storyboard = UIStoryboard(name: "Main", bundle: nil)
        let child_1 = storyboard.instantiateViewController(withIdentifier: String(describing: "HomeViewController")) as! HomeViewController
        child_1.itemInfo = "Home"
        return child_1
    }


 override func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {

        let array :  [UIViewController] = [child_1]
        return array

    }
```

I write the code like this

**Comment by yosuke1985** [comment]
This topic is already closed, so I wil make new topic
