### ISSUE TITLE
ButtonBarPagerTabStripViewController selectedBarBackgroundColor won't change

### ISSUE THREAD

**Issue by MahmoudTarek** [xmartlabs/XLPagerTabStrip#262]
Hello, 
Here's my code: 
`
override func viewDidLoad() {
        buttonBarView.backgroundColor = .white
        settings.style.buttonBarBackgroundColor = .white
        settings.style.buttonBarItemBackgroundColor = .white
        settings.style.buttonBarItemTitleColor = UIColor(netHex: 0x8c8c8c)
        settings.style.selectedBarBackgroundColor = UIColor.black
        settings.style.selectedBarHeight = 5
        super.viewDidLoad()
    }

`

Every option of these is working fine apart from selectedBarBackgroundColor which won't get applied as you see here, I've created the buttonBarView as explained in issue #253 
![simulator screen shot oct 23 2016 1 46 46 pm](https://cloud.githubusercontent.com/assets/8833188/19625973/3c2246a8-9927-11e6-84f5-9d3252e3e273.png)
Not sure if I'm doing something wrong, any help would be appreciated. Thanks in advance.

**Comment by MahmoudTarek** [comment]
It's not working in the example as well.

**Comment by JayHan-K** [comment]
I think you need some space for selectedbar.

In my case, I have space with buttonbarview and container view 

like this,

![image](https://cloud.githubusercontent.com/assets/22685399/19643427/37161b90-9a25-11e6-84aa-9fabd0ac1629.png)


If i want to help

**Comment by MahmoudTarek** [comment]
Thanks for your help, unfortunately this did not make the selected bar appear.

**Comment by JayHan-K** [comment]
if i can see your code and storyboard,
i can more help to you.

**Comment by MahmoudTarek** [comment]
![screen shot 2016-10-24 at 3 12 26 pm](https://cloud.githubusercontent.com/assets/8833188/19647039/9a69cd78-99fc-11e6-887a-0d5f2464456e.png)
![screen shot 2016-10-24 at 3 12 41 pm](https://cloud.githubusercontent.com/assets/8833188/19647040/9a949aee-99fc-11e6-9501-bf8b5109b18b.png)
![screen shot 2016-10-24 at 3 13 01 pm](https://cloud.githubusercontent.com/assets/8833188/19647042/9acb78b6-99fc-11e6-8748-cf5183e52f54.png)
![screen shot 2016-10-24 at 3 13 07 pm](https://cloud.githubusercontent.com/assets/8833188/19647044/9aff1ac2-99fc-11e6-915e-1febae33cf0f.png)

Here's everything, thanks for your interest.

**Comment by JayHan-K** [comment]
I think you need more space for selectedbar
and it seem to use the constraints.
have a control the space! ^^

**Comment by MahmoudTarek** [comment]
I added enough space between buttonBarView and containerView (around 100px) and it still changed nothing.

**Comment by JayHan-K** [comment]
can you make new git??
if you make new git project and sharing to me.
i can check the problem

**Comment by MahmoudTarek** [comment]
If you'd share your code for this controller and screenshots of the storyboard that'd be easier, thanks man.

**Comment by andrewabdalla** [comment]
I am also facing the same issue. Creating a constraint of Empty space in between the buttonBarView and my Container did not ending up showing the selected bar.

**Comment by MahmoudTarek** [comment]
@mats-claassen would you please help?

**Comment by MahmoudTarek** [comment]
UPDATE
selectedBar appears if you clear the controller's constrains (keep it without constrains) 
Waiting for a fix.

**Comment by elementsrtyte** [comment]
If you want to use autolayout, see this issue:
https://github.com/xmartlabs/XLPagerTabStrip/issues/229

The last solution posted worked for me.

**Comment by MahmoudTarek** [comment]
Worked fine, thank you so much.
