### ISSUE TITLE
Upgrade to Xcode 8.1，get an error

### ISSUE THREAD

**Issue by Shannon-Yang** [xmartlabs/XLPagerTabStrip#264]
When I upgraded to Xcode8.1，get an error like this 

<img width="836" alt="f313299e-271e-4f51-b6e7-ee19cfd1f4b7" src="https://cloud.githubusercontent.com/assets/9735368/19953989/b44cb034-a1ae-11e6-9e7e-8957cf4803b9.png">

this error seems to need to be updated to swift3.0.1 ?

**Comment by marcadam** [comment]
Pretty sure that just means you need to rebuild the module.

**Comment by kansaraprateek** [comment]
Did you find a solution @Shannon-Yang . I am also facing the same issue after the update.

**Comment by mtnbarreto** [comment]
you should compile it using swift 3.0.1 as error indicates..
