### ISSUE TITLE
App becomes non responsive and does not load

### ISSUE THREAD

**Issue by Ankish** [xmartlabs/XLPagerTabStrip#265]
The first viewcontroller does not appear . Only when scrollview is touched it becomes visible abruptly. Using pod XLPagerTabStrip latest with swift 3.0.

**Comment by Ankish** [comment]
I was using scrollview inside stackview , and only on touch on scrollview it showed up. Removed from stackview. With normal constraints works fine now.

**Comment by mtnbarreto** [comment]
@Ankish Have you solved the issue

**Comment by santiagofm** [comment]
Closing due to lack of response
