### ISSUE TITLE
Can I use this programmatically. I am trying to create a ButtonBarPagerTabStripViewController all programmatically and I wasn't to find something about how to do so. 

### ISSUE THREAD

**Issue by namuthan** [xmartlabs/XLPagerTabStrip#266]

**Comment by fedeojeda95** [comment]
Hi @namuthan 

Yes, of course you can! If you create a viewController that inherits from `PagerTabStripViewController`, the `containerView` and the `buttonBarView` will be programatically created with default sizes. You can update the frames afterwards if needed, of course. 

Also, if you want, you can programmatically create a `ButtonBarView` and a `UIScrollView` and set them to the corresponding variables.

Hope it helps! Regards,

**Comment by ro22e0** [comment]
Hello,

Where ButtonBarView and UIScrollView should be created?

**Comment by artemchen** [comment]
This approach works for me, I'm not sure if that's the right way:

import UIKit
import XLPagerTabStrip

```
class GeneralViewPagerViewController: BaseButtonBarPagerTabStripViewController<YourCustomCell> {
    
    weak var barView: ButtonBarView!
    weak var ownContainerView: UIScrollView!
    var controllerArray = [UIViewController]()
    
    override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        buttonBarItemSpec = .nibFile(nibName: "YourCustomCell", bundle: Bundle(for: YourCustomCell.self), width: { [weak self] (childItemInfo) -> CGFloat in
            let label = RoundedCornersLabel()
            label.translatesAutoresizingMaskIntoConstraints = false
            label.font = self?.settings.style.buttonBarItemFont
            label.text = childItemInfo.title
            let labelSize = label.intrinsicContentSize
            return labelSize.width + (self?.settings.style.buttonBarItemLeftRightMargin ?? 8) * 2
        })
    }
    
    
    override func viewDidLoad() {
        settings.style.buttonBarBackgroundColor = .white
        settings.style.buttonBarItemBackgroundColor = .white
        settings.style.selectedBarBackgroundColor = Colors.selectedViewPager
        settings.style.buttonBarMinimumLineSpacing = 0
        settings.style.buttonBarItemsShouldFillAvailableWidth = true
        settings.style.buttonBarLeftContentInset = 0
        settings.style.buttonBarRightContentInset = 0
        settings.style.selectedBarHeight = 0

        let barView = ButtonBarView(frame: CGRect(x: 0.0, y: 0.0, width: self.view.bounds.width, height: 50.0), collectionViewLayout: UICollectionViewFlowLayout())
        self.barView = barView
        let separatorLine = UIView(frame: CGRect(x: 0.0, y: 50.0, width: self.view.bounds.width, height: 1.0))
        separatorLine.backgroundColor = Colors.grey
        let containerView = UIScrollView(frame: CGRect(x: 0, y: 51.0, width: self.view.bounds.width, height: self.view.bounds.height - 50.0 - 66.0))
        self.ownContainerView = containerView
        self.view.addSubview(barView)
        self.view.addSubview(separatorLine)
        self.view.addSubview(ownContainerView)
        self.buttonBarView = self.barView
        self.containerView = self.ownContainerView
        
        super.viewDidLoad()

        changeCurrentIndexProgressive = { (oldCell: YourCustomCell?, newCell: YourCustomCell?, progressPercentage: CGFloat, changeCurrentIndex: Bool, animated: Bool) -> Void in
            guard changeCurrentIndex == true else { return }
            oldCell?.pagerTitle.backgroundColor = Colors.unselectedViewPager
            oldCell?.pagerTitle.font = UIFont.systemFont(ofSize: 15.0, weight: UIFontWeightMedium)
            
            newCell?.pagerTitle.backgroundColor = Colors.selectedViewPager
            newCell?.pagerTitle.font = UIFont.systemFont(ofSize: 15.0, weight: UIFontWeightSemibold)
        }
    }
    
    override func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {
        if controllerArray.isEmpty {
            let dummyViewController = DummyViewController()
            dummyViewController.itemInfo = IndicatorInfo(title: "Dummy")
            return [dummyViewController]
        } else {
            return controllerArray
        }
    }
    
    override func configure(cell: YourCustomCell, for indicatorInfo: IndicatorInfo) {
        cell.pagerTitle.text = indicatorInfo.title
    }
    
    override func updateIndicator(for viewController: PagerTabStripViewController, fromIndex: Int, toIndex: Int, withProgressPercentage progressPercentage: CGFloat, indexWasChanged: Bool) {
        super.updateIndicator(for: viewController, fromIndex: fromIndex, toIndex: toIndex, withProgressPercentage: progressPercentage, indexWasChanged: indexWasChanged)
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
    }
    
}
```

**Comment by CoderJisan** [comment]
I am a very beginner iOS developer, Just started to learn, how can I add SegmentedPagerTabStripViewController Programmatically.. please help, add can anybody please let me know the steps in details to add this PagerTabViewController to my apps. 

THANKS IN ADVANCE :) 
Hasibul Haque

**Comment by ibrahimzak** [comment]
> This approach works for me, I'm not sure if that's the right way:
> 
> import UIKit
> import XLPagerTabStrip
> 
> ```
> class GeneralViewPagerViewController: BaseButtonBarPagerTabStripViewController<YourCustomCell> {
>     
>     weak var barView: ButtonBarView!
>     weak var ownContainerView: UIScrollView!
>     var controllerArray = [UIViewController]()
>     
>     override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
>         super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
>     }
>     
>     required init?(coder aDecoder: NSCoder) {
>         super.init(coder: aDecoder)
>         buttonBarItemSpec = .nibFile(nibName: "YourCustomCell", bundle: Bundle(for: YourCustomCell.self), width: { [weak self] (childItemInfo) -> CGFloat in
>             let label = RoundedCornersLabel()
>             label.translatesAutoresizingMaskIntoConstraints = false
>             label.font = self?.settings.style.buttonBarItemFont
>             label.text = childItemInfo.title
>             let labelSize = label.intrinsicContentSize
>             return labelSize.width + (self?.settings.style.buttonBarItemLeftRightMargin ?? 8) * 2
>         })
>     }
>     
>     
>     override func viewDidLoad() {
>         settings.style.buttonBarBackgroundColor = .white
>         settings.style.buttonBarItemBackgroundColor = .white
>         settings.style.selectedBarBackgroundColor = Colors.selectedViewPager
>         settings.style.buttonBarMinimumLineSpacing = 0
>         settings.style.buttonBarItemsShouldFillAvailableWidth = true
>         settings.style.buttonBarLeftContentInset = 0
>         settings.style.buttonBarRightContentInset = 0
>         settings.style.selectedBarHeight = 0
> 
>         let barView = ButtonBarView(frame: CGRect(x: 0.0, y: 0.0, width: self.view.bounds.width, height: 50.0), collectionViewLayout: UICollectionViewFlowLayout())
>         self.barView = barView
>         let separatorLine = UIView(frame: CGRect(x: 0.0, y: 50.0, width: self.view.bounds.width, height: 1.0))
>         separatorLine.backgroundColor = Colors.grey
>         let containerView = UIScrollView(frame: CGRect(x: 0, y: 51.0, width: self.view.bounds.width, height: self.view.bounds.height - 50.0 - 66.0))
>         self.ownContainerView = containerView
>         self.view.addSubview(barView)
>         self.view.addSubview(separatorLine)
>         self.view.addSubview(ownContainerView)
>         self.buttonBarView = self.barView
>         self.containerView = self.ownContainerView
>         
>         super.viewDidLoad()
> 
>         changeCurrentIndexProgressive = { (oldCell: YourCustomCell?, newCell: YourCustomCell?, progressPercentage: CGFloat, changeCurrentIndex: Bool, animated: Bool) -> Void in
>             guard changeCurrentIndex == true else { return }
>             oldCell?.pagerTitle.backgroundColor = Colors.unselectedViewPager
>             oldCell?.pagerTitle.font = UIFont.systemFont(ofSize: 15.0, weight: UIFontWeightMedium)
>             
>             newCell?.pagerTitle.backgroundColor = Colors.selectedViewPager
>             newCell?.pagerTitle.font = UIFont.systemFont(ofSize: 15.0, weight: UIFontWeightSemibold)
>         }
>     }
>     
>     override func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {
>         if controllerArray.isEmpty {
>             let dummyViewController = DummyViewController()
>             dummyViewController.itemInfo = IndicatorInfo(title: "Dummy")
>             return [dummyViewController]
>         } else {
>             return controllerArray
>         }
>     }
>     
>     override func configure(cell: YourCustomCell, for indicatorInfo: IndicatorInfo) {
>         cell.pagerTitle.text = indicatorInfo.title
>     }
>     
>     override func updateIndicator(for viewController: PagerTabStripViewController, fromIndex: Int, toIndex: Int, withProgressPercentage progressPercentage: CGFloat, indexWasChanged: Bool) {
>         super.updateIndicator(for: viewController, fromIndex: fromIndex, toIndex: toIndex, withProgressPercentage: progressPercentage, indexWasChanged: indexWasChanged)
>     }
>     
>     override func didReceiveMemoryWarning() {
>         super.didReceiveMemoryWarning()
>     }
>     
> }
> ```
@artemchen 
could you please put the 'YourCustomCell' code example here

Thanks

**Comment by rafattouqir** [comment]
Just came here to show other's regarding how to add it programmatically:

`class MyMusicViewController: ButtonBarPagerTabStripViewController {
    
    let containerScrollView: UIScrollView = {
        let view = UIScrollView()
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()
    let topBarView: ButtonBarView = {
        let view = ButtonBarView(frame: .zero, collectionViewLayout: UICollectionViewFlowLayout())
        view.translatesAutoresizingMaskIntoConstraints = false
        return view
    }()
    
    override func viewDidLoad() {
        setupSlidingTab()
        super.viewDidLoad()
        
        self.title = "Rafat"
        self.navigationController?.navigationBar.prefersLargeTitles = true
        
    }
    
    // MARK: - PagerTabStrip View Setup
    private func setupSlidingTab(){
        self.containerView = self.containerScrollView
        self.buttonBarView = self.topBarView
        
        self.view.addSubview(self.topBarView)
        self.view.addSubview(self.containerScrollView)
        NSLayoutConstraint.activate([
            self.topBarView.heightAnchor.constraint(equalToConstant: 44),
            self.topBarView.safeLeadingAnchor.constraint(equalTo: self.view.safeLeadingAnchor, constant: 0),
            self.view.safeTrailingAnchor.constraint(equalTo: self.topBarView.safeTrailingAnchor, constant: 0),
            self.containerScrollView.safeLeadingAnchor.constraint(equalTo: self.view.safeLeadingAnchor, constant: 0),
            self.view.safeTrailingAnchor.constraint(equalTo: self.containerScrollView.safeTrailingAnchor, constant: 0),
            self.topBarView.topAnchor.constraint(equalTo: self.view.safeTopAnchor, constant: 0),
            self.containerScrollView.topAnchor.constraint(equalTo: self.topBarView.bottomAnchor, constant: 0),
            self.view.safeBottomAnchor.constraint(equalTo: self.containerScrollView.safeBottomAnchor, constant: 0)
        ])
        
        /// change sliding tab color, doesn't support dynamic theme
        // TODO: - Need to add workout for theme support
        settings.style.buttonBarBackgroundColor = .white
        settings.style.buttonBarItemBackgroundColor = .white
        settings.style.selectedBarBackgroundColor =.customColor
        changeCurrentIndexProgressive = { (oldCell: ButtonBarViewCell?, newCell: ButtonBarViewCell?, progressPercentage: CGFloat, changeCurrentIndex: Bool, animated: Bool) -> Void in
            guard changeCurrentIndex == true else { return }
            oldCell?.label.textColor = .charcoalLighter
            newCell?.label.textColor = .charcoal
        }
        settings.style.buttonBarItemFont = .customFont
        settings.style.selectedBarHeight = 3.0
        settings.style.buttonBarMinimumLineSpacing = 0
        settings.style.buttonBarItemTitleColor = .red
        settings.style.buttonBarItemsShouldFillAvailableWidth = true
        
    }
    
    // MARK: - PagerTabStripDataSource
    override func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {
        let vc1 = CustomViewController(itemInfo: IndicatorInfo(title: "VC1"))
        vc1.view.backgroundColor = .lightGray
        let vc2 = CustomViewController(itemInfo: IndicatorInfo(title: "VC2"))
        vc2.view.backgroundColor = .lightGray
        return [vc1, vc2]
    }
}

`
