### ISSUE TITLE
No tabBar indicator...

### ISSUE THREAD

**Issue by albertml** [xmartlabs/XLPagerTabStrip#268]
I used this code:

override func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {
        
        let storyBoard = UIStoryboard(name: "Main", bundle: nil)
        let summerVC = storyBoard.instantiateViewController(withIdentifier: "summerVc") as! WinterViewController
        summerVC.blackTheme = true
        summerVC.itemInfo = IndicatorInfo(title: "Summer")
        
        let winterVC = storyBoard.instantiateViewController(withIdentifier: "winterVc") as! WinterViewController
        winterVC.itemInfo = IndicatorInfo(title: "Winter")
        winterVC.blackTheme = true

        
        return [animeVC, mangaVC]
}

I want the line indicator under the selected tab... I used storyboard.. I want to have a result same as spotify example

**Comment by kimimsc** [comment]
I am working on the same thing right now and what I've done is that I'ce added a UIView in the storyboard with a Leading constraint to 0 and when user swaps or presses a button I change the Leading constraint.

You need to override the following method:
```
func updateIndicator(for viewController: PagerTabStripViewController, fromIndex: Int, toIndex: Int, withProgressPercentage progressPercentage: CGFloat, indexWasChanged: Bool)
```

But there seems to be a problem with this as on left navigation (swap or button press) the fromIndex and toIndex are inverted. (https://github.com/xmartlabs/XLPagerTabStrip/issues/269)

**Comment by santiagofm** [comment]
Hey @albertml !

You can go over the Example project and see how the spotify example is implemented.

Cheers
