### ISSUE TITLE
In updateIndicator function, fromIndex and toIndex are inverted on left swap

### ISSUE THREAD

**Issue by mouchegmouradian** [xmartlabs/XLPagerTabStrip#269]
In the following method, called when we swap or press one of the bar buttons, when we navigate to the left the 'fromIndex' and 'toIndex' are inverted ...

```
override func updateIndicator(for viewController: PagerTabStripViewController, fromIndex: Int, toIndex: Int, withProgressPercentage progressPercentage: CGFloat, indexWasChanged: Bool)
```

For example, if we have 3 ViewControllers [V1][V2][V3], and we are on [V3] and either swap to [V1] or press the button in the button bar we will have {fromIndex = 1 : toIndex = 2} then {fromIndex = 0 : toIndex = 1}

**Comment by santiagofm** [comment]
Closing, this issue is fixed in the current version.
