### ISSUE TITLE
Wanna use StoryBoard as tab of child viewcontrollers

### ISSUE THREAD

**Issue by yosuke1985** [xmartlabs/XLPagerTabStrip#270]
Now I asking in StackOverFlow also.
The Link is here.
[http://stackoverflow.com/questions/40571016/wanna-use-storyboard-as-tab-of-child-viewcontrollers-xlpagertabstrip](http://stackoverflow.com/questions/40571016/wanna-use-storyboard-as-tab-of-child-viewcontrollers-xlpagertabstrip)

plz check this method: override func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController]

this methods return the UIViewController to show the tab's viewControllers, I can render, and this library example shows how to put programatically but not with StoryBoard

```
var child_1 : HomeViewController{
    let storyboard = UIStoryboard(name: "Main", bundle: nil)
    let child_1 = storyboard.instantiateViewController(withIdentifier: String(describing: "HomeViewController")) as! HomeViewController
    child_1.itemInfo = "Home"
    return child_1
}


override func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {

    let child_2 = TableChildExampleViewController(style: .plain, itemInfo: "Beef")
    let array :  [UIViewController] = [child_1, child_2]
    return array
}
```
for child_1 , I wrote code like this, doest work (try to use StoryBoard) for child_2, this works fine but thats only programatically.

this code's problems is tha, when instantite this Instance, cannot init "child_1.itemInfo"

Plz give me advice

**Comment by ThoseGuysInTown** [comment]
Also would like to know this

**Comment by SebastianBO** [comment]
Been trying for the past 4 hours without success...

**Comment by ThoseGuysInTown** [comment]
It seems to only work for me if the child view controllers are tableviewcontrollers otherwise the iboulets don't initialize properly.

**Comment by mtnbarreto** [comment]
@yosuke1985 could you please share the error, stack trace or whatever that is going wring? 

Every pager child view controller must conform to `IndicatorInfoProvider` protocol as readme points out.

**Comment by yosuke1985** [comment]
yes, problem comes from IndicatorInfoProvider protocol,
cannot comform with storyboard, Thats is the problem.

**Comment by mtnbarreto** [comment]
Basically you should create a new child view controller class, let's say you call it ChildViewController which should  extends from any UIViewController. Then you should  make ChildViewController conforms IndicatorInfoProvider. Finally connect the storyboard view controller with ChildViewController class. 

Are you doing that?

**Comment by yosuke1985** [comment]
Yes, plus, need to call `storyboard.instantiateViewController` to use Storyboard.
I try to use thie method to instantiate Storyboard and conform to `IndicatorInfoProvider`.
If you could, plz show me the sample code.

**Comment by carloscrono** [comment]
@yosuke1985 

In main controller:

**Comment by carloscrono** [comment]
@yosuke1985 

In main controller:

`override func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {
let fromStoryboard : UITableViewController = (self.storyboard?.instantiateViewController(withIdentifier: "StoryBoardIdentifier"))! as! YourTableViewClassController

let child_2 = OtherClassController(style: .grouped, itemInfo: IndicatorInfo(title: "Información", image: UIImage(named: "step_01_bg_unselected_02")))
    
    return [fromStoryboard, child_2]
}`

Then in your child controller:

`var itemInfo = IndicatorInfo(title: "YourTitle", image: UIImage(named: "imageForCustomCell"))
  
  func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
    return itemInfo
  }`

delete all init funds and you are done!

**Comment by yosuke1985** [comment]
sorry, the fromStoryboard doest not work because that doesnt apply to IndicatorInfo.
If you say this work, if possible would you please upload the code?

**Comment by santiagofm** [comment]
Hey @yosuke1985 ! I don't quite get what you mean with *that doesn't apply to IndicatorInfo*, but you have to make the children conform to `IndicatorInfoProvider` and you can do that with the second portion of code posted by @carloscrono.
I'd rather you post the code you have written and we help you correct it!
Cheers
