### ISSUE TITLE
Second button bar item

### ISSUE THREAD

**Issue by IVANKRUPSKI** [xmartlabs/XLPagerTabStrip#271]
Possible to implement second bar item (image) with slightly different scrolling?

The problem I have is that there are quite a lot of item names and they are long, so navigation might be confusing for a user.

![image](https://cloud.githubusercontent.com/assets/16180201/20385229/f7d9db5c-acb6-11e6-94c3-4c0059de6994.png)

So I was thinking to add an ico (image) for each item to make navigation simpler, BUT
- I need those icos scroll slightly differently so that most of them fit the screen.
- Same time this (icos) scrolling should be linked to the titles scrolling and vice versa.
- In terms of scrolling and touches icos (images) should act same as button bar items act now.
- I would also appreciate to have different title and image sizes for  selected and not selected items. You have implemented this in Navigation Bar option but no in the other ones.

Thank you in advance

**Comment by mtnbarreto** [comment]
I got your idea. 
Options you have available are: show short titles, show only images, show image and title but scrolling at the same velocity. 

Seems to me this is edge case scenario and it's not worth integrating to the library.
