### ISSUE TITLE
Spelling mistake: buttonBarItemsShouldFillAvailiableWidth should be buttonBarItemsShouldFillAvailableWidth

### ISSUE THREAD

**Issue by johnnysay** [xmartlabs/XLPagerTabStrip#274]
Spelling mistake: buttonBarItemsShouldFillAvailiableWidth should be buttonBarItemsShouldFillAvailableWidth

**Comment by mtnbarreto** [comment]
@johnnysay thanks for pointing this out!

**Comment by kajensen** [comment]
how is this not in the latest release..
