### ISSUE TITLE
indicator not showing 

### ISSUE THREAD

**Issue by royatv** [xmartlabs/XLPagerTabStrip#277]
The indicator not showing i'm useing storyboard 

<img width="318" alt="screen shot 2016-11-27 at 12 17 13 pm" src="https://cloud.githubusercontent.com/assets/22446192/20647365/79cb668a-b49b-11e6-9793-5395793ca8f3.png">

any one face this problem ??!!!

**Comment by vaibhav-varshaaweblabs** [comment]
Yeah, I faced the same issue with the latest release

**Comment by royatv** [comment]
did u find the solution ?

**Comment by vaibhav-varshaaweblabs** [comment]
@royatv Nope

**Comment by mohshin-shah** [comment]
I am also facing the same issue.Please resolve this bug.
Not working if you have set the BarButton view except then the aligned with top layout guide.
Please help !

**Comment by mohshin-shah** [comment]
I am also facing the same issue.Please resolve this bug.
Not working if you have set the BarButton view except then the aligned with top layout guide.
Please help !

**Comment by mohshin-shah** [comment]
I am also facing the same issue.Please resolve this bug.
Not working if you have set the BarButton view except then the aligned with top layout guide.
Please help !

**Comment by mohshin-shah** [comment]
I am also facing the same issue.Please resolve this bug.
Not working if you have set the BarButton view except then the aligned with top layout guide.
Please help !

**Comment by mohshin-shah** [comment]
I am also facing the same issue.Please resolve this bug.
Not working if you have set the BarButton view except then the aligned with top layout guide.
Please help !

**Comment by mohshin-shah** [comment]
I am also facing the same issue.Please resolve this bug.
Not working if you have set the BarButton view except then the aligned with top layout guide.
Please help !

**Comment by mohshin-shah** [comment]
I am also facing the same issue.Please resolve this bug.
Not working if you have set the BarButton view except then the aligned with top layout guide.
Please help !

**Comment by mohshin-shah** [comment]
I am also facing the same issue.Please resolve this bug.
Not working if you have set the BarButton view except then the aligned with top layout guide.
Please help !

**Comment by mohshin-shah** [comment]
I am also facing the same issue.Please resolve this bug.
Not working if you have set the BarButton view except then the aligned with top layout guide.
Please help !

**Comment by mohshin-shah** [comment]
I am also facing the same issue.Please resolve this bug.
Not working if you have set the BarButton view except then the aligned with top layout guide.
Please help !

**Comment by mohshin-shah** [comment]
I am also facing the same issue.Please resolve this bug.
Not working if you have set the BarButton view except then the aligned with top layout guide.
Please help !

**Comment by mohshin-shah** [comment]
I am also facing the same issue.Please resolve this bug.
Not working if you have set the BarButton view except then the aligned with top layout guide.
Please help !

**Comment by mohshin-shah** [comment]
I am also facing the same issue.Please resolve this bug.
Not working if you have set the BarButton view except then the aligned with top layout guide.
Please help !

**Comment by SebastianBO** [comment]
Same here.

**Comment by mandyedi** [comment]
Same here. The interesting thing is that if I build with my mac it works fine, but the autobuild version is missing the _selectedBar.
When selectedBar is initialized, the frame width and height value is 1000.
Another info that might help:
My xcode version is 8.1, but the autobuilder has 8.0.
I use the obj-c branch.

**Comment by mandyedi** [comment]
I found a solution based on this SO answer: http://stackoverflow.com/a/39222046
I update the frame in layoutSubviews() in XLButtonBarView.m
```
- (void)layoutSubviews() {
    [super layoutSubviews];
    [self.selectedBar setFrame:CGRectMake(0, self.frame.size.height - _selectedBarHeight, 0, _selectedBarHeight)];
}
```

**Comment by vaibhav-varshaaweblabs** [comment]
@royatv try this [solution](http://stackoverflow.com/a/40925208/2223492) from StackOverflow

**Comment by royatv** [comment]
@vaibhav-varshaaweblabs  thank u it's work 👏🏼

**Comment by mtnbarreto** [comment]
Guys could you provide more info about how you are specifying the buttonBarView, in particular its position?
