### ISSUE TITLE
Use the sliding tab bar only

### ISSUE THREAD

**Issue by iad24** [xmartlabs/XLPagerTabStrip#279]
Is it possible to only use the sliding tab bar view part?
I dont have any UIViewController to show.
I just want the selection of my list to be in a sliding tab bar.

thanks

**Comment by mtnbarreto** [comment]
You can use it but much of its behaviour, in particular delegate and data source of the collection view, is implemented in `BaseButtonBarPagerTabStripViewController`. So to make it work you will have to implement the delegate and datadource, also take a look how `BaseButtonBarPagerTabStripViewController` initialises it.
