### ISSUE TITLE
Why third tableview top padding is different from from first tableview when run demo?

### ISSUE THREAD

**Issue by javaliker** [xmartlabs/XLPagerTabStrip#28]

**Comment by javaliker** [comment]
I  update all table with initWithStyle:UITableViewStylePlain style.  I run demo find third tableview top padding is different from from first tableview.
TableChildExampleViewController * child_1 = [[TableChildExampleViewController alloc] initWithStyle:UITableViewStylePlain];
    ChildExampleViewController * child_2 = [[ChildExampleViewController alloc] init];
    TableChildExampleViewController * child_3 = [[TableChildExampleViewController alloc] initWithStyle:UITableViewStylePlain];

**Comment by anoadragon453** [comment]
Also seeing this behavior. Doesn't look too good.

**Comment by michaelEllisUy** [comment]
Hey javaliker,

 we fixed this issue. Please check demo again. It works fine now :+1: 

Check out #56 

Cheers!
