### ISSUE TITLE
Is it possible and how, if yes, one can have different width for selected and non-selected cell?

### ISSUE THREAD

**Issue by IVANKRUPSKI** [xmartlabs/XLPagerTabStrip#281]
Is it possible and how, if yes, one can have different width for selected and non-selected cell?
Maybe somehow using different xibs?

**Comment by chandanch** [comment]
Use `cell.selectionStyle = UITableViewCellSelectionStyleGray;`

**Comment by IVANKRUPSKI** [comment]
Apparently that wasn't clear.

I meant here collectionViewCell in the pagingMenu itself.
So that cell (buttonBarItem) that is currently selected has different width from all other cells/ buttonBarItems.

**Comment by mtnbarreto** [comment]
It's not possible at least i can't figure out a easy way.
