### ISSUE TITLE
User interaction is disabled calling moveToViewController two times

### ISSUE THREAD

**Issue by dpu83** [xmartlabs/XLPagerTabStrip#284]
When I call `moveToViewController(at: Int, animated: Bool)` or `moveTo(viewController: UIViewController, animated: Bool)` two consecutive times on the same index/ViewController the User interaction is disabled and the user is forced to close and reopen the app.

So I have to check each time that the index is not the same as the one currently displayed.

I suggest to edit `moveToViewController(at: Int, animated: Bool)` inside `PagerTabStripViewController.swift` adding **`currentIndex != index`** in the guard this way:

```Swift
  open func moveToViewController(at index: Int, animated: Bool = true) {
        guard isViewLoaded && view.window != nil && currentIndex != index else {
            currentIndex = index
            return
        }
        if animated && pagerBehaviour.skipIntermediateViewControllers && abs(currentIndex - index) > 1 {
            var tmpViewControllers = viewControllers
            let currentChildVC = viewControllers[currentIndex]
            let fromIndex = currentIndex < index ? index - 1 : index + 1
            let fromChildVC = viewControllers[fromIndex]
            tmpViewControllers[currentIndex] = fromChildVC
            tmpViewControllers[fromIndex] = currentChildVC
            pagerTabStripChildViewControllersForScrolling = tmpViewControllers
            containerView.setContentOffset(CGPoint(x: pageOffsetForChild(at: fromIndex), y: 0), animated: false)
            (navigationController?.view ?? view).isUserInteractionEnabled = false
            containerView.setContentOffset(CGPoint(x: pageOffsetForChild(at: index), y: 0), animated: true)
        } else {
            (navigationController?.view ?? view).isUserInteractionEnabled = false
            containerView.setContentOffset(CGPoint(x: pageOffsetForChild(at: index), y: 0), animated: animated)
        }
    }
```

**Comment by Maqix** [comment]
+1

**Comment by Flox06** [comment]
+1

**Comment by carloscrono** [comment]
I think your fix didn't worked for me. When I call that method, the app stays frozen with no errors.

**Comment by pepejeria** [comment]
Using XLPagerTabStrip 7.0.0 and I am also getting the UI freeze. Anybody knows what is going on?

**Comment by pepejeria** [comment]
Had to override moveToViewController to solve this issue
`open override func moveToViewController(at index: Int, animated: Bool = true) {
        containerView.setContentOffset(CGPoint(x: pageOffsetForChild(at: index), y: 0), animated: animated)
    }`
