### ISSUE TITLE
Pagerstrip only shows navigationbar when it has it's own navigationcontroller

### ISSUE THREAD

**Issue by thomascsorbamedia** [xmartlabs/XLPagerTabStrip#288]
Hi,

I can't seem to figure out why but the navigationbar is gone when using pagerstrip I navigation controller in the root of my app and some segues following it. The last view (pagerstripview) only shows the navigationbar when I embed a second navigationcontroller in front of the pagerstripview.

I hope someone can help me out.

Thanks in advance,

Thomas

**Comment by mtnbarreto** [comment]
@thomascsorbamedia
 please share a project reproducing the issue so i look into it.

**Comment by santiagofm** [comment]
Closing due to lack of response.
