### ISSUE TITLE
UISegmentedControl stops responding after switching segment

### ISSUE THREAD

**Issue by saltwat5r** [xmartlabs/XLPagerTabStrip#29]
When I switch segment with swipe, it's ok, but when I switch segment on segmented control, then it stops responding and not changing at all.

EDIT:
Ok, I found a solution, but I don't know why it was the reason.
Problem disappeared when I removed these method:
- (void)moveToViewControllerAtIndex:(NSUInteger)index

**Comment by michaelEllisUy** [comment]
Issue is now solved!
