### ISSUE TITLE
so many old methods error

### ISSUE THREAD

**Issue by longxianlin** [xmartlabs/XLPagerTabStrip#291]
using latest xcode8.2, swift3

**Comment by andy1247008998** [comment]
Same issue here.

We may need to convert it from Swift2.3 to Swift3.
I found a test.swft in the project which indicates the author tried to convert it but not finished.

**Comment by saschagordner** [comment]
Try `pod 'XLPagerTabStrip', '~> 6.0'` instead of 5.0 (which is deprecated in the readme).
