### ISSUE TITLE
Pager Tab Strip in Nav Bar?

### ISSUE THREAD

**Issue by ThoseGuysInTown** [xmartlabs/XLPagerTabStrip#293]
I was wondering if you could make it so that the pager tab strip can be added to the nav bar of a view controller. Similar to how you have it for the twitter clone in this library. 

Thanks!

**Comment by mtnbarreto** [comment]
there are some examples showing a tab bar added to nav bar in the example project. Please look at it.

**Comment by ThoseGuysInTown** [comment]
Is this a recent update? The only ones that I saw that were actually part of the nav bar controller were the Twitter one and the segmented one.
