### ISSUE TITLE
Uppercased titles with diatrics are clipped

### ISSUE THREAD

**Issue by bphenriques** [xmartlabs/XLPagerTabStrip#297]
**Environment:** 
Last version of XLPagerTabStrip, Xcode and the issue spans every iOS version

------

Hey! Great work with this!

However, I am having an issue: I want my titles to be uppercases but they are chopped. As you can see in the screenshot, the titles seem to be "AEIOA" but they are, in fact "ÁÉÍÓÃ"

Feedback would be greatly appreciated!

Thank you.
<img width="314" alt="screen shot 2017-01-15 at 21 22 00" src="https://cloud.githubusercontent.com/assets/4727729/21966291/ba5c6340-db68-11e6-8b2c-2a1c89eb0bd6.png">

The configuration:
```swift
    override func viewDidLoad() {
        setupPagesVisuals()
        super.viewDidLoad()
    }

    func setupPagesVisuals() {
        settings.style.buttonBarItemLeftRightMargin = leftRightTitlePadding
        settings.style.selectedBarHeight = barHeight
        settings.style.buttonBarItemFont = CategoriesViewController.normalFont
        settings.style.buttonBarBackgroundColor = barColor
        settings.style.buttonBarLeftContentInset = leftRightContentOffset
        settings.style.buttonBarRightContentInset = leftRightContentOffset
        settings.style.buttonBarItemBackgroundColor = barColor
        settings.style.selectedBarBackgroundColor = selectedIndicatorColor

        //add bold effect to selected cell
        changeCurrentIndexProgressive = { (oldCell: ButtonBarViewCell?, newCell: ButtonBarViewCell?, progressPercentage: CGFloat,
            changeCurrentIndex: Bool, animated: Bool) -> Void in
            guard changeCurrentIndex == true else { return }
            oldCell?.label.font = CategoriesViewController.normalFont
            newCell?.label.font = CategoriesViewController.selectedFont
        }
    }
```

**Comment by mtnbarreto** [comment]
@bphenriques Have you tried with `settings.style.barHeight = ...` ?

**Comment by mtnbarreto** [comment]
this only works if you are not using interface builder to create the barView.

**Comment by bphenriques** [comment]
Hey! Just figured out one hour ago! If any person stumbles into this check
your fonts' ascender property. In my case I had to rise it a bit so it
could render properly diatrics on iOS. I used a third party program for it
but I think it is possible to do on a command line.

Thank you!

**Comment by mtnbarreto** [comment]
cool! thanks for sharing the trick!
