### ISSUE TITLE
custom Layout is not working  when Push 

### ISSUE THREAD

**Issue by sam961** [xmartlabs/XLPagerTabStrip#299]
I have a minview controller and i want to push to another view controller,
when pushing, the tab bar will be at top while in storyboard i put it in the middle of the view.
Knowing that if the view was a root view controller the layout works but if it comes from a push, it doesnt. Any solution ?

**Comment by mtnbarreto** [comment]
@sam961  Have you set up all containts using interface builder?

**Comment by Huralnyk** [comment]
@sam961 @mtnbarreto I have same issue. Have you guys found the solution? Appreciate any help.

**Comment by mtnbarreto** [comment]
I have tested it and it seems to work fine. 
Take into account that I added the ButtonBarView and the container view using interface builder (storyboards) and connect the necessary outlets and set up its constraints. 

See the changes over here: https://github.com/xmartlabs/XLPagerTabStrip/tree/issue/299/example

if it still doesn't work, please add another example reproducing the issue...

**Comment by johndpope** [comment]
I threw up some test files at gist below.
 When pushing the view programmatically - it all goes pear shaped. 
https://gist.github.com/johndpope/9b9205f0bcc2a7835753aa70b948f2e2

**Comment by johndpope** [comment]
not ideal - but get out of jail card hack    

```

 override func viewWillDisappear(_ animated: Bool) {
        super.viewWillDisappear(animated)
        Logger.verbose("viewWillDisappear")
        buttonBarView.isHidden = true
        buttonBarView.isUserInteractionEnabled = false
        self.title = ""
    }
    
    override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        Logger.verbose("viewWillAppear")
        buttonBarView.isHidden = false
        buttonBarView.isUserInteractionEnabled = true
        self.title = ""
    }
```
