### ISSUE TITLE
Setting initial tab

### ISSUE THREAD

**Issue by dmdque** [xmartlabs/XLPagerTabStrip#300]
Is there a built-in way to set the initial tab to something other than the first?

I was able to do it by modifying [currentIndex](https://github.com/xmartlabs/XLPagerTabStrip/blob/d18a24304522a40bdcb81e75c6a150ab9f876a9d/Sources/PagerTabStripViewController.swift#L64) to not be private, and setting it in `viewDidLoad()`.

**Comment by dmdque** [comment]
`moveToViewController(at: 1)` works.

**Comment by happiehappie** [comment]
Sorry but did you not receive 

> Unbalanced calls to begin/end appearance transitions for

 warning?
