### ISSUE TITLE
How to use XLPagerTabStip ?

### ISSUE THREAD

**Issue by Mohammed-Eliass** [xmartlabs/XLPagerTabStrip#307]
Drag into the storyboard a UIViewController and set up its class with your pager controller (MyPagerTabStripName). Drag a UIScrollView into your view controller view and connect PagerTabStripViewController containerView outlet with the scroll view.

how to make this ?

Could you please take this into consideration :
What about video tutorial how to do this and save our time ?

**Comment by samirthebti** [comment]
hi @Mohammed-Eliass hope this link help you 
[https://medium.com/michaeladeyeri/how-to-implement-android-like-tab-layouts-in-ios-using-swift-3-578516c3aa9#.9v1is9pol](https://medium.com/michaeladeyeri/how-to-implement-android-like-tab-layouts-in-ios-using-swift-3-578516c3aa9#.9v1is9pol)

**Comment by Mohammed-Eliass** [comment]
Thanks a lot bro @samirthebti this help me a lot.
Finally something visual.

**Comment by samirthebti** [comment]
لا شكر على واجب اخي @Mohammed-Eliass 👍

**Comment by Mohammed-Eliass** [comment]
جزاك الله خيراّ
