### ISSUE TITLE
abnormal behavior auto layout in Xcode 8.2.1 and swift 3  !

### ISSUE THREAD

**Issue by Mohammed-Eliass** [xmartlabs/XLPagerTabStrip#308]
after adding XLPagerTabStrip to my project and following the examples:
when the project is running I got behavior of swiping gesture different from tapping of titles
in this screenshot I got space between the names and table view cells and this is when view loaded
![screen shot 2017-01-26 at 11 04 28 am](https://cloud.githubusercontent.com/assets/18654470/22324106/de908ec2-e3af-11e6-83a7-cf2c34bc76ca.png)
if I continue in swiping with gesture I got the same layout (the space stay as is)
if I tapped in the title of some table view title the space is gone as this screenshot 
![screen shot 2017-01-26 at 11 04 42 am](https://cloud.githubusercontent.com/assets/18654470/22324184/6a07c416-e3b0-11e6-9f1b-c1120da21ac9.png)

if tried to swipe using gesture again we return to the first screenshot with space

forget about the bold black color underneath the buttonBarView.

any suggestions ?!

**Comment by Mohammed-Eliass** [comment]
when I added this lines of code everything worked perfectly 💯 

    guard isReload else {
            return [child_1, child_2, child_3, child_4, child_5, child_6, child_7, child_8]
        }
        
        var childViewControllers = [child_1, child_2, child_3, child_4, child_6, child_7, child_8]
        
        for (index, _) in childViewControllers.enumerated(){
            let nElements = childViewControllers.count - index
            let n = (Int(arc4random()) % nElements) + index
            if n != index{
                swap(&childViewControllers[index], &childViewControllers[n])
            }
        }
        let nItems = 1 + (arc4random() % 8)
        return Array(childViewControllers.prefix(Int(nItems)))
    }
    
    override func reloadPagerTabStripView() {
        isReload = true
        if arc4random() % 2 == 0 {
            pagerBehaviour = .progressive(skipIntermediateViewControllers: arc4random() % 2 == 0, elasticIndicatorLimit: arc4random() % 2 == 0 )
        }
        else {
            pagerBehaviour = .common(skipIntermediateViewControllers: arc4random() % 2 == 0)
        }
        super.reloadPagerTabStripView()
    }

**Comment by nickcastel50** [comment]
Just wanted to comment and say I'm getting this exact same behavior. Above fix didn't help. On iPhone 7 Swift 4 latest build.
