### ISSUE TITLE
iOS 9 crash after layout update

### ISSUE THREAD

**Issue by tomassliz** [xmartlabs/XLPagerTabStrip#309]
I'm calling the `view.layoutIfNeeded()` in the `ButtonBarPagerTabStripViewController` child. It crashes on iOS 9 in `PagerTabStripViewController.virtualPageFor(contentOffset: CGFloat) -> Int` because the pageWidth is 0. On iOS 10 is the layout not updated and the `ButtonBarPagerTabStripViewController.viewDidLayoutSubviews()` is not called - no crash.

I'm using version 6.0.0

![screen shot 2017-01-26 at 16 07 48](https://cloud.githubusercontent.com/assets/3275022/22364439/e09a4a06-e471-11e6-8004-ee05b1e0eb6c.png)

**Comment by nickcastel50** [comment]
I have the same issue. In my case, I have an XLPagerTabStrip on the first UIViewController inside my TabBarController (index 0). The issue only appears when I present a UIViewController (also using XLPagerTabStrip) and then dismiss it and attempt to open another tab on my tab bar controller. The pageWidth also becomes 0 for me in that case. Also on iOS 9.

**Comment by tomassliz** [comment]
Solution is to override the `virtualPageFor(contentOffset:)` method:
```swift
public override func virtualPageFor(contentOffset: CGFloat) -> Int {
    if self.pageWidth == 0 {
        return 0
    } else {
        return super.virtualPageFor(contentOffset: contentOffset)
    }
}
```

**Comment by santiagofm** [comment]
Hey guys!

Can you provide a sample project to reproduce this issue ? I tried to reproduce it with the Example project but wasn't able to.

Cheers

**Comment by santiagofm** [comment]
Closing due to lack of response
