### ISSUE TITLE
XLPagerTabStrip update indicator image

### ISSUE THREAD

**Issue by Metman** [xmartlabs/XLPagerTabStrip#313]
Hello. I use ButtonBarPagerTabStripViewController. How do I update indicator image? I need to update the image when I receive notification

**Comment by santiagofm** [comment]
Hey @Metman !

I think this issue is related to #325, can you confirm that ? That issue is addressed in #368 & will soon be merged into the master branch

Cheers

**Comment by santiagofm** [comment]
Closing due to lack of response.
