### ISSUE TITLE
UITableView goes under UITabBar in "NavButton" option

### ISSUE THREAD

**Issue by andresinaka** [xmartlabs/XLPagerTabStrip#32]
Any idea why is this happening? I'm trying to use this in a project and is great but I'm having this problem and I couldn't figure out why this is happening.

![screenshot](http://i.imgur.com/Gu7oavt.png?1)

**Comment by michaelEllisUy** [comment]
:+1: 
Hey Andres,

 We fixed the demo. It was a demo error, not actually from the XLPagerTabStrip source code. We disabled the attribute "Extende Edges -> Under Top Bars", for the Nav Button Bar Example View Controller from the storyboard.

 Now Demo works well!

 Cheers!

**Comment by michaelEllisUy** [comment]
take a look the changes done here #56
