### ISSUE TITLE
Button Bar Paging Issue in the Selected Line

### ISSUE THREAD

**Issue by dynames356** [xmartlabs/XLPagerTabStrip#321]
Dear all,

I'm new to this Library and I have an issue, that when I select the third of the pager. The line below the selected bar will sometimes not follow the selected bar one, as shown below.

![capture](https://cloud.githubusercontent.com/assets/25767153/22925388/8409b5f8-f2e3-11e6-8c4b-9a4fa83eb5ef.png)

This happened when I was playing around with clicking the button bar actually.
Here are the code settings that I have setup.

```
        settings.style.buttonBarBackgroundColor = Utilities.DarkBlueColor
        settings.style.buttonBarItemBackgroundColor = Utilities.DarkBlueColor
        settings.style.selectedBarBackgroundColor = Utilities.YellowColor
        buttonBarView.selectedBar.backgroundColor = Utilities.YellowColor
        settings.style.buttonBarItemFont = .boldSystemFont(ofSize: 14)
        settings.style.selectedBarHeight = 2.0
        settings.style.buttonBarMinimumLineSpacing = 0
        settings.style.buttonBarItemsShouldFillAvailiableWidth = true
        settings.style.buttonBarLeftContentInset = 0
        settings.style.buttonBarRightContentInset = 0
        
        
        changeCurrentIndexProgressive = { (oldCell: ButtonBarViewCell?, newCell: ButtonBarViewCell?, progressPercentage: CGFloat, changeCurrentIndex: Bool, animated: Bool) -> Void in
            guard changeCurrentIndex == true else { return }
            oldCell?.label.textColor = .white
            newCell?.label.textColor = Utilities.YellowColor
        }
```

Appreciate it if you could help me how to solve the above issue.

Thank you.

**Comment by santiagofm** [comment]
Hey @dynames356 !

Are you still experiencing this issue with the latest release ? If so, could you provide a sample project to reproduce this issue ?

Cheers

**Comment by dynames356** [comment]
Dear santiagofm,

Ah yes, however apparently it only happens on the Simulator Device. When installed on Real Device, it is worked as intended. You may close this issue.

Best Regards

**Comment by 3r1k83** [comment]
In the obj-c version i have the same issue on the device. 
You should reopen this issue.

**Comment by muhizia** [comment]
the same case with me it still don't work as intended on real device
