### ISSUE TITLE
Weird menu animation

### ISSUE THREAD

**Issue by fotiDim** [xmartlabs/XLPagerTabStrip#322]
I am experiencing this weird animation behavior on some of the tab transitions. It appears that the menu bar lags behind the swipe gesture for some tabs. Notice the issue on transition between "Alle Aktionen" and "Damen".

![2017-02-22 12_15_29](https://cloud.githubusercontent.com/assets/2326415/23209298/fe8a2a9a-f8f8-11e6-871c-ede005bdb41a.gif)

My settings are like this:

```
settings.style.buttonBarItemFont = UIFont.systemFont(ofSize: 13, weight: UIFontWeightSemibold)
settings.style.selectedBarHeight = 1.5
settings.style.buttonBarLeftContentInset = UIScreen.main.bounds.width/2 - 52
self.containerView.bounces = false
```

- Environment: XLPagerTabStrip 7.0.0, Xcode 8.2.1 and iOS 10.2

**Comment by fotiDim** [comment]
On deeper investigation, this seems to be affected by:
- Speed of the swipe (faster swipes seem to trigger it)
- The width difference of the menu items involved in the transition

**Comment by fotiDim** [comment]
I also found out that on an iPhone 6s the issue doesn't happen but it does happen on the iPhone 6s simulator.

**Comment by santiagofm** [comment]
Hey @fotiDim !

Can you provide a small sample project to reproduce this issue ?

Cheers

**Comment by alexwillrock** [comment]
managed to reproduce this with sample project if i swipe full screen (edge to edge)
[demo_button.zip](https://github.com/xmartlabs/XLPagerTabStrip/files/989812/demo_button.zip)

**Comment by santiagofm** [comment]
Thanks @alexwillrock !

The issue is triggered when the contentOffset of the [buttonBar is set animated](https://github.com/xmartlabs/XLPagerTabStrip/blob/master/Sources/ButtonBarView.swift#L115-L116), UIKit does this in a constant velocity instead of immediately and lags behind.
We'll take a look and fix it.

Cheers

**Comment by alexwillrock** [comment]
Thanks @santiagofm 
It's work perfectly )

Best regards
