### ISSUE TITLE
missing imageView in ButtonCell.xib

### ISSUE THREAD

**Issue by andy1247008998** [xmartlabs/XLPagerTabStrip#325]
Please add the missing imageView in ButtonCell.xib

**Comment by santiagofm** [comment]
Hey @andy1247008998 !

There should be no image missing in the `ButtonCell` nib, in fact there's not even an `UIImageView` there so that can't be possible.

Cheers

**Comment by andy1247008998** [comment]
@santiagofm That's interesting. Sine there's no UIImageView in ButtonCell.nib, then how can you set an image as title icon in IndicatorInfoProvider?

**Comment by santiagofm** [comment]
@andy1247008998 Actually you are right, my bad ! 
The `ButtonBarViewCell` has a `imageView` property that is configured via the `IndicatorInfoProvider` but the nib doesn't have the corresponding imageview.
Thanks for reporting this !

**Comment by Mina-R-Meshriky** [comment]
Sorry but why is this issue closed, I can't find the imageView in the ButtonCell.xib

**Comment by santiagofm** [comment]
hey @Mina-R-Meshriky !

The issue is fixed on the master branch, until we release a new version please use that.

Cheers

**Comment by Mina-R-Meshriky** [comment]
yes thanks, I notice now that the ButtonCell.xib has the image view on the master branch ... but curiously it is "in front of" the label, which indicates that I could have a label only or a picture only. What if i want to have both a picture and a label above each other which is a very common scenario. How can i achieve that?

Second Question relating to issue #313, when I have an image and I specified for it a highlighted version in the function `IndicatorInfo(title: String, image: UIImage?, highlightedImage: UIImage?)` will it update automatically? if not then how to set this behavior

**Comment by santiagofm** [comment]
@Mina-R-Meshriky until we decide how the layout will be(probably an `UIImageView` with a `UILabel` below, like you said), we only support an `UIImage` *or* a `UILabel`.

You still can achieve what you want by implementing a custom `ButtonBarItem`, please take a look at the `YoutubeExampleViewController` [in the Example project](https://github.com/xmartlabs/XLPagerTabStrip/blob/7f0ca677a40ae8eefe663e2761f7c24a0a706660/Example/Example/Youtube/YoutubeExampleViewController.swift#L41-L83) and the `YoutubeIconCell` cell.

Cheers

**Comment by Mina-R-Meshriky** [comment]
hi @santiagofm 
yah I actually did look at the youtube example, and I did everything like the example but I always get an 'NSUnknownKeyException', the steps i did are as follows:
1- create a Cocoa touch UICollectionViewCell class and its .xib file (let's call it `Cell`)
2- in the `Cell.xib` file: I inserted both the `ImageView` and the `Label` and put the Constraints
3- I connected outlets with `Cell.class` (and just before that I deleted the `awakFromNib` function created automatically)
4- then in the `MYExampleViewController`, I changed the inheritance from `ButtonBarPagerTabStripViewController` to `BasicButtonBarPagerTabStripViewController<Cell>` 
5- I started to add the functions:
     ` override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?) {
        super.init(nibName: nibNameOrNil, bundle: nibBundleOrNil)
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        
        buttonBarItemSpec = ButtonBarItemSpec.nibFile(nibName: "Cell", bundle: Bundle(for: Cell.self), width: { (cell: IndicatorInfo) -> CGFloat in
                return 55.0
        })
    }

override func configure(cell: Cell, for indicatorInfo: IndicatorInfo) {
        cell.iconImage.image = indicatorInfo.image?.withRenderingMode(.alwaysTemplate)
cell.iconImage.highlightedImage= indicatorInfo.highlightedImage?.withRenderingMode(.alwaysTemplate)
cell.label.text = indicatorInfo.title
    }`
6- it is worth mentioning that I created 3 ViewControllers in StoryBoard with storyBoardID's and instantiated them in the `MYExampleViewController` ... also I conformed to the `IndicatorInfoProvider`
7- I also added this line to the AppDelegate `let _ = MYExampleViewController(nibName: nil, bundle: nil)`

So what am I doing wrong

**Comment by santiagofm** [comment]
The error is because the vc is generic and the storyboard isn't able to find the class when instantiating it, it should get fixed with `let _ = MYExampleViewController(nibName: nil, bundle: nil)` in the AppDelegate as you said.
I don't see anything wrong with your code, you could try with `MYExampleViewController.load()` but i don't think it will make a difference.

Could you provide the code so we can take a look ?

Cheers

**Comment by Mina-R-Meshriky** [comment]
[CustomCellExample.zip](https://github.com/xmartlabs/XLPagerTabStrip/files/1004878/CustomCellExample.zip)

here it is a sample that contain the error:
While you're at it, can you explain how to show the highlighted picture on swipe

**Comment by santiagofm** [comment]
Hey @Mina-R-Meshriky !

The issue with the `Unknown class ...` is because your `ViewController` is the `initialViewController` so it actually gets instantiated before the `AppDelegate`'s `didFinishLaunchingWithOptions...` gets called.
As a workaround you could instantiate it and set as the `window`'s `rootViewController` yourself:
```swift
ViewController.load()
        
let storyboard = UIStoryboard(name: "Main", bundle: Bundle.main)
if let vc = storyboard.instantiateInitialViewController() {
    window?.rootViewController = vc
    window?.makeKeyAndVisible()
}
```
If it's not your `initialViewController` then you won't have this issue.

As for the highlighted image, you have to set the the image highlighted yourself and you can do it in the `changeCurrentIndexProgressive` block.

I've made a commit with those changes to your sample project's repo so you can take a look:
[CustomCellExample.zip](https://github.com/xmartlabs/XLPagerTabStrip/files/1004974/CustomCellExample.zip)

Cheers

**Comment by Mina-R-Meshriky** [comment]
wow!!! Really thanks, and yes it is not my first View Controller but I was testing my view first before integrating it ...

**Comment by Knkush** [comment]
Hi. Please can you help me. I want set two images in barButtonView first as a icon, and second as a separator, and also label. How I can set it?
