### ISSUE TITLE
Strange assignment in `moveToViewController` guard.

### ISSUE THREAD

**Issue by Skogetroll** [xmartlabs/XLPagerTabStrip#328]
```swift
open func moveToViewController(at index: Int, animated: Bool = true) {
  guard isViewLoaded && view.window != nil && currentIndex != index else {
    currentIndex = index // ← this line
    return
  }
  // other code
}
```

Can you explain why is this line needed there? 

It leads to current tab indicator being changed **all the time** _without guarantee that content will change_. So you may have indicator showing one tab being active (and `currentIndex` showing this tab being active), while content view controller that belongs to another tab.

**Comment by m-revetria** [comment]
Hi @Skogetroll,

That guard checks if the pager's view was loaded and you are trying to change the selected child controller. It allows you to change the child view controller that will be shown at the first time, before show it. So you can do something like:

```swift
let pagerViewController = YourPagerViewController()
pagerViewController.moveToViewController(at: 3)
present(pagerViewController)
```

Regards
