### ISSUE TITLE
Crash Issue in Cocoapods Version

### ISSUE THREAD

**Issue by mnhsoftskills** [xmartlabs/XLPagerTabStrip#33]
Cocoapods version crashes when using XLButtonBarPagerTabStripViewController due to unregistered collectionview cell.

Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'could not dequeue a view of kind: UICollectionElementKindCell with identifier Cell - must register a nib or a class for the identifier or connect a prototype cell in a storyboard'

Could not find the below line in the cocoapods version:
    [self.buttonBarView registerNib:[UINib nibWithNibName:@"ButtonCell" bundle:nil]  forCellWithReuseIdentifier:@"Cell"];

**Comment by mtnbarreto** [comment]
@mnhsoftskills Are you using `XLPagerTabStrip` as a dynamic framework ?

**Comment by mtnbarreto** [comment]
@mnhsoftskills you should register a cell to be used by the collection view like NavButtonBarExampleViewController does by adding this line:
   
` [self.buttonBarView registerNib:[UINib nibWithNibName:@"ButtonCell" bundle:[NSBundle bundleForClass:[self class]]]  forCellWithReuseIdentifier:@"Cell"];`

The registered cell must be a `XLButtonBarViewCell` or must extend from it. 

Regards

**Comment by OliverPearmain** [comment]
I have fixed this issue with this PR....

https://github.com/xmartlabs/XLPagerTabStrip/pull/71

**Comment by cdunkel** [comment]
What is the status of getting this PR merged back into the release version?
