### ISSUE TITLE
How to add multiple label to tab menu

### ISSUE THREAD

**Issue by sahabe1** [xmartlabs/XLPagerTabStrip#331]
Hi 
 I want to add label just above to page title can i do this.please see attachment

please help
![unnamed](https://cloud.githubusercontent.com/assets/1065015/23581431/a1234208-0139-11e7-90b6-bf1455597e21.png)

**Comment by santiagofm** [comment]
Hey @sahabe1 !

Yes, you can do that. You'll need create a custom cell for the `Button Bar` to use and you should be good to go.
Please take a look at the `YoutubeExampleViewController` in the Example project, there you can see how a different cell is set to the `Button Bar` in the `init?(coder aDecoder: NSCoder)` function and how those cells are configured via the `configure(cell: YoutubeIconCell, for indicatorInfo: IndicatorInfo)` function afterwards.

Please let me know if you need anything else !
Cheers

**Comment by sahabe1** [comment]
is it possible to change the tab title from child view controller or any tab pages

**Comment by santiagofm** [comment]
@sahabe1 You can do that yes. You can access the `PagerTabStripViewController` from it's children through the `parent` property, you just need to cast it.

Closing this issue because the original question is answered.
Cheers

**Comment by RohanJain70** [comment]
Hey hi @sahabe1 . I tried updating the title using below code in one of the Child view controller to update its own tab title 
`if let pagerTabStrip = self?.parent as? PagerTabStripViewController {
                        self?.itemInfo.title = "New Requests \(response.count)"
                        self?.indicatorInfo(for: pagerTabStrip)
 }`
But its not updating the title.

May i know how did you achieve the same.

**Comment by junweimah** [comment]
@sahabe1 Did you do it? 

How do I change the number from children?

I have this : 

> self.numberInBadge = 
> if let pagerTabStrip = self.parent as? PagerTabStripViewController {

>     // what to put here to update??

>     self.indicatorInfo(for: pagerTabStrip)
> }
