### ISSUE TITLE
Unknown class in interface builder file

### ISSUE THREAD

**Issue by tylermrolfe** [xmartlabs/XLPagerTabStrip#335]
If my parent view class subclasses `ButtonBarPagerTabStripViewController` everything runs fine. But when I follow the instructions to add images to the ButtonBarView and change the subclass to `BaseButtonBarPagerTabStripViewController<BarViewIconCell>` I get a crash and the log error states that the class is unknown. (BarViewIconCell is my class name for the original YoutubeIconCell)

I've checked stackoverflow on this issue and have followed every answer and it's still not fixed. And I've obviously quadruple checked to make sure the name in the story board file matches the swift file.

**Comment by m-revetria** [comment]
Hi @tylermrolfe,

Generic view controllers cannot be used in storyboards due to these classes are not visible to the objective-c runtime which is used to instantiate view controllers from storyboards.

**Comment by ahmedsafadii** [comment]
how did you fix it I got the same issue :(

**Comment by santiagofm** [comment]
Hey @ahmedsafadii !

Please open a new issue detailing the problem you are experiencing.

Cheers

**Comment by m-revetria** [comment]
@ahmedsafadii, this issue has not an easy solution, we would need to change the definition of that view controller to get rid of the generic implementation. That is something that we are not going to take care at this moment. We will be very glad if you can help with this :)

Right now, you cannot use `BaseButtonBarPagerTabStripViewController` in Storyboards, you have to create it programmatically and show it in the appropriate place within your app.

Regards

**Comment by santiagofm** [comment]
@tylermrolfe In the meantime as a workaround you can load the class to the ObjC runtime before the storyboard actually tries to use it, perhaps in the AppDelegat, like so:
```swift
YourClassThatInheritsFromBaseButtonBarPagerTabStripViewController.load()
```
