### ISSUE TITLE
Cell stays highlighted after changing to new page

### ISSUE THREAD

**Issue by ivanmih** [xmartlabs/XLPagerTabStrip#338]
There seems to be a bug with cells in the menus collection view. If i tap on different cells sometimes the old cells stays highlighted. If i change the view controller by swiping the cell gets to normal state.
This issue can be recreated by launching Example project in XLPagerTabStrip. I've encountered it specifically in the NavButton tab. Try scrolling to view2, click on it, then scroll back to view and after you click on it the view2 stays highlighted. It occurs under other combination also. In my project it occurs more often than in the example project, but i guess that the underlying issue is the same.

**Comment by xuzhengrong1** [comment]
have the same problem

**Comment by m-revetria** [comment]
Hey, thanks for the report. This has been recently fixed.
