### ISSUE TITLE
Datasource Assert

### ISSUE THREAD

**Issue by KashishGoel** [xmartlabs/XLPagerTabStrip#339]
App is crashing and prints the following in console:

fatal error: Sub-class must implement the PagerTabStripDataSource viewControllers(for:)

I have a class that is inheriting from ButtonBarPagerTabStripViewController. When super.viewdidload is called in this class the app crashes. Since this class inherits from PagerTabStripDataSourc I cant conform to the datasource in this class. Look at the crash results it seems that the exact line causing it to crash is `viewControllers = dataSource.viewControllers(for: self)` in `private func reloadViewControllers()` in `PagerTabStripViewController`

I'm using the latest update and on iOS 9

**Comment by fedeojeda95** [comment]
Hi @KashishGoel 

Are you implementing the method `func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController]` in your view controller that inherits `ButtonBarPagerTabStripViewController` ? This method should be overriden since it's the one that returns the view controller for each tab. 

Let us know if you could solve it! Best regards,

**Comment by sibinsanthosh** [comment]
hi same issue here any update ?
        assertionFailure("Sub-class must implement the PagerTabStripDataSource viewControllers(for:) method")

**Comment by thallurumeghana** [comment]
hi @fedeojeda95 

when I am overriding the
`override func viewControllersForPagerTabStrip(pagerTabStripController:PagerTabStripViewController) -> [UIViewController] {
        return [UserRegistrationViewController(),OrganizationRegistrationViewController()]
        `
it is throwing an  error  "Method does not override any method from its superclass" and I wrote that function in viewDidLoad()

**Comment by korsour** [comment]
Still the same issue here. And yes, it has
`override public func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController] `
