### ISSUE TITLE
Add a comman HeaderView Above all tabs

### ISSUE THREAD

**Issue by harry225** [xmartlabs/XLPagerTabStrip#34]
Need a comman headerview for all tabs. When user scrollup it can be go up like tableheader view.

**Comment by michaelEllisUy** [comment]
`XLPagerTabStrip` was not originally intended to support this kind of animation and this is not the main goal of the library. 

You can accomplish that using `XLPagerTabStrip` and another library of custom code written by yourself.

Regards
