### ISSUE TITLE
Interface Builder Designables Error

### ISSUE THREAD

**Issue by sehmus** [xmartlabs/XLPagerTabStrip#340]
Hello,
After integrating XLPagerTabStrip to my project, I'm getting interface builder errors. 

error: IB Designables: Failed to render and update auto layout status for UserProfileViewController (7sb-El-gf8): dlopen(XLPagerTabStrip.framework, 1): no suitable image found. Did find: XLPagerTabStrip.framework: required code signature missing for 'XLPagerTabStrip.framework'

Do you have any solution ?

**Comment by santiagofm** [comment]
Hey @sehmus !
Can you provide a sample project to reproduce this issue ?

**Comment by santiagofm** [comment]
Closing due to lack of response.

**Comment by anthonyroani** [comment]
Same problem here. I just updated my podfile and now have this issue.

**Comment by ChinmayDB** [comment]
@anthonyroani i got the same problem when i added a library in pod and did pod install. When i am Opening the Storyborad i am not able to see any elements. Did you got any solution ?

**Comment by AmrKafina** [comment]
Just ran into this issue. Not sure what the problem was, but deleting my project's "[Derived Data](https://stackoverflow.com/a/49124371/2022349)" folder and cleaning the project solved the issue for me.

**Comment by hupei1991** [comment]
Any solution or pr updates?

**Comment by khushDesai** [comment]
Facing Same issue 

![screen shot 2018-07-21 at 11 49 59 am](https://user-images.githubusercontent.com/29880773/43032760-3b1a02be-8cdc-11e8-9a02-69589705376b.png)


Any Solution for this?

**Comment by hupei1991** [comment]
Downgrade your cocoapod to version 1.4 and wait for the new update on the cocoapod.
