### ISSUE TITLE
Application crashed when push NavigationBarItem

### ISSUE THREAD

**Issue by b-i-hide** [xmartlabs/XLPagerTabStrip#342]
Hello!
I use ButtonBarPagerTabStripViewController in my app, and I also 
use NavigationBar in same VC.
The ButtonBar is just below the NavigationBar.

My problem is when I tap Navigation item, my application crashed. I don't have any idea, so I want your help. 
This is my console output.
```
XLPagerTabStrip was compiled with optimization - stepping may behave oddly; variables may not be available.
(lldb) 
```
Do you have any idea??
 XLPagerTabStrip: 7.0
Xcode: 8.21

**Comment by fedeojeda95** [comment]
Hi @b-i-hide 

Could you provide us with some code and all the console output in order to checkout what is the problem? The console output seems to not be related to the crash that you are currently facing. Please check out before if it may be due to a disconnected outlet.

Regards,

**Comment by santiagofm** [comment]
Closing due to lack of response.
