### ISSUE TITLE
Can not find buttonBarView

### ISSUE THREAD

**Issue by jerry-shao** [xmartlabs/XLPagerTabStrip#345]
![image](https://cloud.githubusercontent.com/assets/7830699/24430750/23cf990c-1410-11e7-8c6f-ad926ef250a0.png)

When I right click on the collection view and try to create a new reference outlet to the HomeViewController, it's not shown buttonBarView.

May I know what's the problem?

**Comment by m-revetria** [comment]
Hi @jerry-shao, `buttonBarView` is defined in the class `ButtonBarPagerTabStripViewController`.

In the IB you can open the Assistent Editor and navigate from your view controller till  `ButtonBarPagerTabStripViewController` and connect the outlet.

![button_bar_view_outlet](https://cloud.githubusercontent.com/assets/4791678/25635261/dffd4e68-2f53-11e7-89c7-251c21fc0b6e.gif)
