### ISSUE TITLE
How to adjust the width of the slider at the bottom

### ISSUE THREAD

**Issue by 974929538** [xmartlabs/XLPagerTabStrip#346]
<img width="371" alt="2017-03-29 6 07 56" src="https://cloud.githubusercontent.com/assets/19601875/24449887/580b13e0-14ab-11e7-8660-acf07b421689.png">
what should I do

**Comment by santiagofm** [comment]
Currently the selectedBar width is calculated based on the cell's width and the api doesn't provide a way to customize this. 
We have added this feature to our backlog and plan to implement it when we have some time. In the meantime you can take a look at #108 to figure out a workaround.

Thanks !
