### ISSUE TITLE
Is there any way that I can do this android view pager but with the Arrow indicator is up?

### ISSUE THREAD

**Issue by htarwara6245** [xmartlabs/XLPagerTabStrip#348]
http://stackoverflow.com/questions/34235068/custom-tab-indicatorwith-arrow-down-like-indicator

All I want is documentation for some customization on indicator. If anyone can provide full example,it will be appreciated

**Comment by santiagofm** [comment]
Hey @htarwara6245 ! 

Unfortunately, right now there is no way to customize the `ButtonBarView`'s `selectedBar` shape via the api, so you'll have to fork the project and do it yourself.

I'll add this as a task to our backlog but don't see it implemented in the near future, you are welcome to submit a PR with basic functionality to speed up things.

Cheers

**Comment by CarlinhaCamargo** [comment]
I've done something similar using the buttonBarView.selectedBar view. I've created my triangleView and add to selected bar view. Something like `buttonBarView.selectedBar.addSubview(triangleView)`
