### ISSUE TITLE
swift Don't work properly

### ISSUE THREAD

**Issue by wodetian** [xmartlabs/XLPagerTabStrip#35]
use `Xcode6.3` , `Swift1.2 ` And `CocoaPod`

#### This is my Podfile
````shell
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
platform :ios, '8.0'

def main_Pods
    pod 'XLPagerTabStrip'
end

target :JustGo do
   main_Pods
end
````

##### This is my code 

````swift
import UIKit
import XLPagerTabStrip

class SettingViewController: XLBarPagerTabStripViewController{
    
    override func viewDidLoad() {
        super.viewDidLoad()
        self.barView.selectedBar.backgroundColor = UIColor.orangeColor()
    }

    override func childViewControllersForPagerTabStripViewController(pagerTabStripViewController: XLPagerTabStripViewController!) -> [AnyObject]! {
        var viewCOntroller1 = UIViewController()
        viewCOntroller1.view.backgroundColor = UIColor.redColor()
        var viewCOntroller2 = UIViewController()
        viewCOntroller2.view.backgroundColor = UIColor.grayColor()
        var viewCOntroller3 = UIViewController()
        viewCOntroller3.view.backgroundColor = UIColor.purpleColor()
        return [viewCOntroller1,viewCOntroller2,viewCOntroller3]
    }
}
````

##### This is my StoryBoard screenshots 
<img alt="This is my StoryBoard screenshots" src="http://i3.tietuku.com/4e3033a88f13553f.jpg" width=300/>

##### The problems 
1.When coming into the page does not load the first ViewController 
2.When sliding load to success. But your schedule page but failed. 
<img alt="This is my StoryBoard screenshots" src="http://i1.tietuku.com/90d4d1530f156ccd.gif" width=300/>

**Comment by wodetian** [comment]
I don't know what happened, but I seems to solve the problem of......

**Comment by wodetian** [comment]
When I Push into another page, and then come back to this page when the problem solved

**Comment by michaelEllisUy** [comment]
Hey Paranoid,

 It actually works fine. You should adjust your constraints. 
 Please check out this mini project i made with your same example, but with the correct constraints: https://github.com/michaelEllisUy/XLPagerTabStripMiniExample

**Comment by Saleh-At** [comment]
Hey there
you can correct this prob:
Simple Introduction:

1. click on the UIScrollView (as Container)
2. uncheck Autoresize Subviews option.
