### ISSUE TITLE
I am using XLPagerTabStrip, can I incorporate SWRevealViewController

### ISSUE THREAD

**Issue by aferrerb** [xmartlabs/XLPagerTabStrip#350]
I want to use a sliding left menu in an app that is using XLPagerTabStrip. Is this possible? I was thinking of using SWRevealViewController. Has anyone tried this before? Perhaps not specifically using the SWRevealViewController library, but having a sliding menu while using XLPagerTabStrip?
Thanks

**Comment by ivanmih** [comment]
I did it. For now it functions quite nice. If you can`t manage yourself, i`ll try my best to help.
