### ISSUE TITLE
标题会有重用的bug

### ISSUE THREAD

**Issue by NinoWang** [xmartlabs/XLPagerTabStrip#353]
做下面的设置之后，当先选中一个选项，然后在滑到最后面选中一个新的选项后，再划回来，之前的oldCell的颜色不会及时改变
 oldCell?.label.textColor = UIColor.black
newCell?.label.textColor = Star_Orange

**Comment by NinoWang** [comment]
ButtonBarPagerTabStripViewController last selected tab is not properly deselected #343

**Comment by m-revetria** [comment]
Hi @NinoWang this was solved in this PR #359

**Comment by m-revetria** [comment]
Related issue #338
