### ISSUE TITLE
updateIndicator callback return wrong indexs

### ISSUE THREAD

**Issue by eyalc** [xmartlabs/XLPagerTabStrip#356]
It looks like the `updateIndicator` delegate callback return the wrong `toIndex` and `fromIndex` in some scenarios.
It can be easily reproduce using the Youtube example from the project, using the following steps:

**enter the Youtube Example -> tap on "Trending" icon -> tap on "Account" icon -> tap on "Home" icon**
you can see that the title is wrong, its "TRENDING" instead of "HOME"

(_the bug happens when you tap on the `ButtonBarView` buttons, don't use the swipe gesture._)

This is how it looks if i print the values of fromIndex/toIndex/currentIndex in the `updateIndicator` delegate callback (when `indexWasChanged=true`) for each step i described above:

> tap on "Trending" icon:
> log --> fromIndex: 0,    toIndex: 1,    currentIndex: 1 
> 
> tap on "Account" icon:
> log --> fromIndex: 1,    toIndex: 2,    currentIndex: 2
> 
> tap on "Home" icon:
> log --> fromIndex: 0,    toIndex: 1,    currentIndex: 1
> log --> fromIndex: 0,    toIndex: 1,    currentIndex: 0

as you can see the final `toIndex` is 1 instead of 0
(but the final `currentIndex` seems to be ok)

Env: Xcode 8.3, ios 9/10

**Comment by Etheriq** [comment]
I have the same problem

**Comment by santiagofm** [comment]
This issue is resolved in #360. I'll close this issue when we merge it.

Thanks!
