### ISSUE TITLE
Can't change tab if pager isn't visible

### ISSUE THREAD

**Issue by Dagogatc** [xmartlabs/XLPagerTabStrip#357]
I have an UITabBar, with a PagerTabStripViewController in one of it's tabs. After the pager is loaded and shown, I change to other tab inside the UITabBar and press a button that will trigger a moveToViewController to the pager. Then I return to the pager, but the tab didn't change.

**Comment by santiagofm** [comment]
Looks like the `currentIndex` gets updated correctly but the when the pager is shown the change does not take place. 
We'll work on a fix, thanks !
