### ISSUE TITLE
Application Crash on Last Tab after changing layout direction  

### ISSUE THREAD

**Issue by BaluNaik** [xmartlabs/XLPagerTabStrip#362]
[](https://github.com/xmartlabs/XLPagerTabStrip/issues/361)

Hi Team,

In order to fix my last requirement. Implemented this code 

Step1:  changing viewcontroller orders
```
 override func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {
        if Language.isArabic{
            return  [self.viewControllerForSegment(with: 3),self.viewControllerForSegment(with: 2),self.viewControllerForSegment(with: 1),self.viewControllerForSegment(with: 0)]
        }else{
            return [self.viewControllerForSegment(with: 0),self.viewControllerForSegment(with: 1),self.viewControllerForSegment(with: 2),self.viewControllerForSegment(with: 3)]
        }
    }
```
Step2: Recognize language changes
```
func languageDidChange(){
        self.updateUI()
}
```
Step3: Updating UI
 ```
func updateUI(){
        let index = self.viewControllers.count - self.currentIndex - 1
        self.reloadPagerTabStripView()
        self.moveToViewController(at: index, animated: true)
    }
```
Every thing fine upto here. 

Note1:  
   1). Application works fine on LTR (0,1,2,3 order)
   2). Application works fine on RTL (On the first launch)
I am getting a crash when changing from LTR to RTL and moving to first view controller(i mean to say, index at 0 when traveling from 3,2,1,0 ) 

"But When scrolling from last to the first view controller in Arabic layout getting crash"

***** Terminating app due to uncaught exception 'NSRangeException', reason: 'NSMutableRLEArray replaceObjectsInRange:withObject:length:: Out of bounds'
*** First throw call stack:
(0x18e1a2fd8 0x18cc04538 0x18e1a2f20 0x18eb9a7dc 0x18eb99ff8 0x10011c99c 0x100334570 0x10033618c 0x1942e9cd0 0x1942e9a40 0x1020a04a4 0x1020a15f0 0x1945e37f0 0x1942efce4 0x194480f28 0x194480c18 0x102c884fc 0x1913b2600 0x1913b24b0 0x18e40fdd4 0x18e139958 0x18e151adc 0x18e15127c 0x18e14ed90 0x18e07ed94 0x18fae8074 0x194337130 0x1003969f0 0x18d08d59c)
libc++abi.dylib: terminating with uncaught exception of type NSException**

- Environment: ButtonBarPagerTabStripViewController, Xcod-8.3 ,Swift 3.0
- Debug Breakpoint in following method

```
open func updateContent() {
      ...........................................
      ...........................................
        for (index, childController) in pagerViewControllers.enumerated() {
         /// In This Block
        }
       .........
       ......... 
    }
```

**Comment by BaluNaik** [comment]
Fixed.

**Comment by noura-rizk** [comment]
could you please tell me how did you solve it?

**Comment by BaluNaik** [comment]
On layout change reorder the controller list.

**Comment by noura-rizk** [comment]
Thanks for replying, I already did that. I've a pager too works fine in both direction but this issue only happens after changing language and reload pager with some new controls (array reversed each time)

Here's the exception.
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Invalid update: invalid number of items in section 0.  The number of items contained in an existing section after the update (4) must be equal to the number of items contained in that section before the update (5), plus or minus the number of items inserted or deleted from that section (2 inserted, 2 deleted) and plus or minus the number of items moved into or out of that section (0 moved in, 0 moved out).'

**Comment by BaluNaik** [comment]
Don't do array reverse...it doesn't works.

1. Create static methods for every controller to create an instance
2. return an array of new list (don't do reverse)



‌
