### ISSUE TITLE
self.parent returning nil

### ISSUE THREAD

**Issue by FaridHaddad** [xmartlabs/XLPagerTabStrip#364]
I am trying toi access self.parent (in a child VC) but the problem is that it is returning nil if the child VC is not the 1st one. For the 1st child VC (the one that loads the first) the return result is not nil.
How can i access it from the others ?

**Comment by FaridHaddad** [comment]
Nvm, i just accessed it from viewWillAppear and not viewDidLoad.
Thanks anyway.

**Comment by Piyush08** [comment]
> Nvm, i just accessed it from viewWillAppear and not viewDidLoad.
> Thanks anyway.

As a Author , please don't provide wrong answer before checking. I am also unable to get it from viewWillAppear.
