### ISSUE TITLE
Change containing view controller's frame (Y origin)

### ISSUE THREAD

**Issue by happiehappie** [xmartlabs/XLPagerTabStrip#366]
My current project is similar to [https://developer.apple.com/library/content/samplecode/NavBar/Introduction/Intro.html](url) (Extended Navigation Bar)

However, this pose a problem when I use SegmentedPagerTabStripViewController as the container view overlaps with my view below the navbar, because my current design positioned my segmented control at the extended view, hence rendering my segmented control untappable, is there any solution to this?

**Comment by santiagofm** [comment]
Hey @happiehappie ! 

If you are using a storyboard you are free to do whatever you want when comes it to positioning either the segmentedControl or the containerView, you just have to set the corresponding outlets. 

That said, i don't quite understand what you are trying to achieve, if you are trying to extend the navbar for the `SegmentedPagerTabStripViewController` or if you want the extended navbar in any of the contained viewcontrollers or something else. 

Could you provide some sample code ? Perhaps extending Apple's Extended Navigation Bar example to use XLPagerTabStrip.

**Comment by santiagofm** [comment]
I've set up this little sample project with what i think is what you are trying to achieve.
https://github.com/santiagofm/extendedNavBar-XLPagerTabStrip

**Comment by happiehappie** [comment]
Hey santiagofm, 

Thank you for your support, I solved it by moving my containerview's frame's y and - the height. Feel free to close this :)
