### ISSUE TITLE
can i change current view controller index from scrolled ButtonBarView page ?

### ISSUE THREAD

**Issue by alexwillrock** [xmartlabs/XLPagerTabStrip#370]
Hello, it's very cool control, but i have one problem, please help me.

detail:
i need next user case - user can drag ContainerView and ButtonBarView change current index synchronously. Okey, but if drag ButtonBarView, ContainerView not synchronously change current ViewController. Is it possible to make synchronous behavior to change ContainerView from dragging ContainerView ?
Thanks
XLPagerTabStrip 7.0.0, Xcode 8.3.1, iOS 9+

**Comment by santiagofm** [comment]
Hey @alexwillrock !

Correct me if i'm wrong, but you want the contained view controller to change when swiping on the `ButtonBarView` also ?

Cheers

**Comment by santiagofm** [comment]
Closing due to lack of response

**Comment by kikko088** [comment]
this is a feature that interest also to me, there is a way for scroll the container when you scroll the buttonBarView? I try to get the index of buttonBarView on changeCurrentIndexProgressive but I didn't find a way for do that...
