### ISSUE TITLE
Adding/Removing Tabs after a reload of data

### ISSUE THREAD

**Issue by miaza0** [xmartlabs/XLPagerTabStrip#372]
Hi,

Im using release 5.0.0 on iOS 8 and having some issues with adding/removing tabs after a reload of data from a server.

The first time I setup the tabs, everything works fine. But after calling the same function again to reload the tabs, It crashes with a nondescript error. Here's a code snippet of the function I use to reload the tabs

```
override func viewControllersForPagerTabStrip(pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {
        
        return subViewControllers
    }

func reloadData(
    self.subViewControllers.removeAll()

     if (containsData1) {

         //Setup subViewController1
        self.subViewControllers.append(subViewController1)
     } else {
         subViewController1 = nil
     }

     if (containsData2) {

        //Setup subViewController2
        self.subViewControllers.append(subViewController2)
     } else {
         subViewController2 = nil
      }

   self.reloadPagerTabStripView()
}
```

The sub viewControllers are a global variable. The viewControllers also have a function to call the reloadFunction in the parent tab viewController.

It crashes when self.reloadPagerTabStripView() is called. The specific line of code is

`viewControllers = dataSource.viewControllersForPagerTabStrip(self)`

in the PagerTabStripViewController file. The stacktrace doesn't tell much.

![screen shot 2017-05-10 at 3 32 46 am](https://cloud.githubusercontent.com/assets/3221390/25864066/67159e86-3531-11e7-97cb-0a01dc228e39.png)

Any help would be greatly appreciated, tearing my hair out 😆

**Comment by santiagofm** [comment]
Hey @miaza0 !

I think there's little we can do with the info provided, maybe you can send over a small sample project to reproduce the issue ? That code snippet looks ok to me.
You said this was done after retrieving some data from a server, have you tried executing the code on the main queue ? The `reloadPagerTabStripView` function does some ui stuff that should be executed on the main queue.

Cheers

**Comment by santiagofm** [comment]
Closing due to lack of response

**Comment by miaza0** [comment]
Hi santiagofm,

My sincere apologies for not getting back to you earlier and I greatly appreciate your quick reply before :)

I have come to discover that the cause of the problem was due to another library, a tableView pull to refresh.

The childViewController had a tableView which could refresh the tabs in the parentView.

```
tableView.dg_addPullToRefreshWithActionHandler({ [weak self] () -> Void in
            self.parentTabViewController.reload()
            
            }, loadingView: loadingView)
```

This caused it to crash upon reloading the tabs. However, when i got rid of  the [weak self] part it worked fine:

```
tableView.dg_addPullToRefreshWithActionHandler({ [] () -> Void in
            self.parentTabViewController.reload()
            
            }, loadingView: loadingView)
```

Perils of just using a library without understanding it haha. 

Thanks for your help again santiagofm, it'd be fantastic if you could provide an explanation of why this could be happening just for extra knowledge, but totally understand if this beyond your domain.
