### ISSUE TITLE
module compiled with swift 3.0.2 cannot be imported in swift 3.1

### ISSUE THREAD

**Issue by samcheuk** [xmartlabs/XLPagerTabStrip#381]
![screen shot 2017-05-23 at 3 23 32 pm](https://cloud.githubusercontent.com/assets/7778891/26342917/89d496ca-3fcc-11e7-9989-c724b9039f43.png)

Environment: 
- Xcode 8.3.2
- Swift 3.1

**Comment by kenchoong** [comment]
hey u have any solution on this??cause I also have this problem
