### ISSUE TITLE
SWRevealViewController and XLPagerTabStrip

### ISSUE THREAD

**Issue by ashishbrana** [xmartlabs/XLPagerTabStrip#382]
i combined SWRevealViewController and XLPagerTabStrip default navigation animation not working.

**Comment by santiagofm** [comment]
Hey @ashishbrana !
Would you mind sharing a sample project so we reproduce the issue ? Or at least elaborate more about the issue please.
Cheers

**Comment by ashishbrana** [comment]
Hi, Thanks
But i am not able to share code. 
 push and pop animation animation  on navigation not working.

**Comment by ivanmih** [comment]
@ashishbrana 
I managed to implement both of these libraries, and might be able to help you.
You don't need to share your original project, instead make a new one to show us what's the problem. 
It's really hard to understand what is the problem you're facing from one sentence.

**Comment by ashishbrana** [comment]
Hey, i found the solution.
Actually it was my mistake. :)

**Comment by santiagofm** [comment]
Ok, awesome !
Cheers

**Comment by dnawarrior** [comment]
Can you share the solution @ashishbrana
