### ISSUE TITLE
ButtonBarView's cell - selected color problem 

### ISSUE THREAD

**Issue by hoangelec** [xmartlabs/XLPagerTabStrip#385]
iOS: 10.3 
Device: iPhone 5c

Please see the video below: 
https://www.youtube.com/watch?v=t44Jk0wCM5Y&feature=youtu.be
Notice how the selected text color in ButtonBarView for the last cell (Subname 7) remain unchanged when I select other cell.

I guess it's a problem with reuse mechanism.

**Comment by santiagofm** [comment]
hey @hoangelec !
This issue is fixed on the master branch but we haven't released a version including it yet. Please point your pod to the master branch until we do that !
Cheers
