### ISSUE TITLE
SelectedTab text color is not changing when change tab programatically.

### ISSUE THREAD

**Issue by souravpalitrana** [xmartlabs/XLPagerTabStrip#389]
I used below code to change selected tab text color 
`changeCurrentIndexProgressive = { (oldCell: ButtonBarViewCell?, newCell: ButtonBarViewCell?, progressPercentage: CGFloat, changeCurrentIndex: Bool, animated: Bool) -> Void in
            guard changeCurrentIndex == true else { return }
           oldCell?.label.textColor = Utils.uicolorFromHex(Styles.COLOR_HOME_TAB_TEXT_UNSELECTED, alpha: 0.5) //UIColor(red: 138/255.0, green: 138/255.0, blue: 144/255.0, alpha: 1.0)
            oldCell?.label.font = UIFont.boldSystemFont(ofSize: 14.0)
            newCell?.label.textColor = UIColor.black
            newCell?.label.font = UIFont.boldSystemFont(ofSize: 14.0)
        }`

It is working when we change tab by swipe or clicking on the tab. But if we change the tab programmatically then above code is not calling as a result selected tab and previously selected tab text color (font) is not changing.
Can anyone tell me what I am doing wrong?

**Comment by johndpope** [comment]
this is a (unsupported/piece of crap) hack - needs redoing



let kUpdateButtonBarCell = NSNotification.Name("kUpdateButtonBarCell")

`changeCurrentIndexProgressive = { (oldCell: ButtonBarViewCell?, newCell: ButtonBarViewCell?, progressPercentage: CGFloat, changeCurrentIndex: Bool, animated: Bool) -> Void in guard changeCurrentIndex == true else { return } oldCell?.label.textColor = Utils.uicolorFromHex(Styles.COLOR_HOME_TAB_TEXT_UNSELECTED, alpha: 0.5) //UIColor(red: 138/255.0, green: 138/255.0, blue: 144/255.0, alpha: 1.0) oldCell?.label.font = UIFont.boldSystemFont(ofSize: 14.0) newCell?.label.textColor = UIColor.black newCell?.label.font = UIFont.boldSystemFont(ofSize: 14.0) 

Notificator.fireNotification(named: kUpdateButtonBarCell) //broadcast - this is to fix a problem where the cells aren't correctly updating the labels after they disappear offscreen

}`


extension ButtonBarViewCell{
    
    func listenForBackgroundChanges(){
        NotificationCenter.default.removeObserver(self, name: kUpdateButtonBarCell, object: nil)
        NotificationCenter.default.addObserver(forName:kUpdateButtonBarCell, object: nil, queue: OperationQueue.main, using: { (note) in
            //Logger.verbose("update cell")
            self.label.textColor = globalVariables.unselectedTextColor
            
        })
    }
}



the other alternative is to call reloadData
    
    func scrollViewDidEndDecelerating(_ scrollView: UIScrollView) {
        print("scrollViewDidEndDecelerating")
        shouldUpdateButtonBarView = true
        buttonBarView.reloadData()
        
    }

   func scrollViewDidEndDragging(_ scrollView: UIScrollView, willDecelerate decelerate: Bool) {
        print("scrollViewDidEndDragging")
        shouldUpdateButtonBarView = true
        buttonBarView.reloadData()
    }

**Comment by souravpalitrana** [comment]
After Selecting tab via delegate what I did is
'buttonBarView.reloadData()'
and it is working perfectly. Thank you very much for the support. :) 
Have a nice day.
