### ISSUE TITLE
iOS11 beta - PagerTabStripViewController crashes on virtualPageFor

### ISSUE THREAD

**Issue by Nikita2k** [xmartlabs/XLPagerTabStrip#393]
**Version**: iOS11 beta
Stack trace: 

> Crashed: com.apple.main-thread
> 0  XLPagerTabStrip                0x10467d7f0 PagerTabStripViewController.virtualPageFor(contentOffset : CGFloat) -> Int (PagerTabStripViewController.swift:216)
> 1  XLPagerTabStrip                0x10467f150 PagerTabStripViewController.updateContent() -> () (PagerTabStripViewController.swift:268)
> 2  XLPagerTabStrip                0x10468679c ButtonBarPagerTabStripViewController.viewDidLayoutSubviews() -> () (PagerTabStripViewController.swift:142)
> 3  XLPagerTabStrip                0x104686a38 @objc ButtonBarPagerTabStripViewController.viewDidLayoutSubviews() -> () (ButtonBarPagerTabStripViewController.swift)

**Comment by Akramhussain4** [comment]
@Nikita2k  Did you find the solution? I'm getting the same error
