### ISSUE TITLE
moveToViewController(at: index, animated: true) not off hightlight label

### ISSUE THREAD

**Issue by geekstars** [xmartlabs/XLPagerTabStrip#397]
![img_0133](https://user-images.githubusercontent.com/21117624/26936235-47b62e6a-4c98-11e7-93b7-5bdea132f1a8.PNG)

**Comment by geekstars** [comment]
my file
[file project.zip](https://github.com/xmartlabs/XLPagerTabStrip/files/1061468/file.project.zip)

**Comment by musbaalbaki** [comment]
@geekstars Try reloading the buttonBarView which is basically a collection view after calling moveToViewController(at: index, animated: true)

**Comment by geekstars** [comment]
Thank you @musbaalbaki
