### ISSUE TITLE
Crash when assigning image to tab

### ISSUE THREAD

**Issue by ezeinis** [xmartlabs/XLPagerTabStrip#404]
XLPagerTabStrip (7.0.0)
Xcode 8.3.2
iphone simulator

When i assign image to tab from the child controller it crashes with message "fatal error: unexpectedly found nil while unwrapping an Optional value". It seems that the ImageView is missing from the ButtonCell

how i assign the image:
`func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
return IndicatorInfo(title: CategoryManager.categories[catIndex].getName(), image: CategoryManager.categories[catIndex].getCatIcon(), highlightedImage: CategoryManager.categories[catIndex].getCatIcon())
}`

where it crashes

cell.imageView.image = image in ButtonBarPagerTabStripViewController

![screen shot 2017-06-23 at 12 47 02 pm](https://user-images.githubusercontent.com/19891292/27476618-16a8331a-5812-11e7-9a04-cb36f4ecee98.png)

**Comment by fedeojeda95** [comment]
This happens due to a missing outlet connection in the cell xib. It has been fixed in one of the latest commits. Please point to the latest commit in `master` branch in order to solve this! We are planning to release a new version as soon as we can.

Hope it helps! Regards,

**Comment by ezeinis** [comment]
Thank you for your response and for the fix!
