### ISSUE TITLE
How to get the index of the selected tab?

### ISSUE THREAD

**Issue by samarth220194** [xmartlabs/XLPagerTabStrip#405]
I know there is a var called as currentIndex to get the current index  of the view controller which is being loaded ,but which function is being called when i slide the tabs so that i can get the current index from that function

**Comment by ahmedsafadii** [comment]
`inherit class ButtonBarPagerTabStripViewController
`
and then use this 

```
    override func updateIndicator(for viewController: PagerTabStripViewController, fromIndex: Int, toIndex: Int, withProgressPercentage progressPercentage: CGFloat, indexWasChanged: Bool) {
        print(toIndex)
    }
```

**Comment by santiagofm** [comment]
Hey @samarth220194 !
You can do what @ahmedsafadii says but when working with a `ButtonBarPagerTabStripViewController` the preferred way would be to set the `changeCurrentIndex` or `changeCurrentIndexProgressive` blocks.
Cheers

**Comment by bobsira** [comment]
@santiagofm  can you give a code example. I'm having issues with this. I want to get the index of the tab that is selected
