### ISSUE TITLE
Using Youtube Example i am unable to create IBOutlet

### ISSUE THREAD

**Issue by khushDesai** [xmartlabs/XLPagerTabStrip#413]
Hello, i am using youtubeExample, and for this i have used following code
class MainVC: BaseButtonBarPagerTabStripViewController<ImageIconCell> 
now there is no error or warning but in storyboard i was unable to create IBOutlet 
Please Help.!

**Comment by santiagofm** [comment]
Hey @khushDesai !
This is an expected behavior as `BaseButtonBarPagerTabStripViewController` uses generics and interface builder can't handle that.
Cheers
