### ISSUE TITLE
moveToViewController not work

### ISSUE THREAD

**Issue by codwam** [xmartlabs/XLPagerTabStrip#414]
`
final class TestViewController: UIViewController {

    fileprivate lazy var pageViewController: ButtonBarPagerTabStripViewController = {
        let pageViewController = ButtonBarPagerTabStripViewController(containerViewControllers: self.containerViewControllers)
        return pageViewController
    }()

    override func viewDidLoad() {
        super.viewDidLoad()
        
        // Do any additional setup after loading the view.

        self.navigationItem.title = "Test"
        self.automaticallyAdjustsScrollViewInsets = false
        
        self.addChildViewController(self.pageViewController)
        self.view.addSubview(self.pageViewController.view)
        self.pageViewController.didMove(toParentViewController: self)
        // layout
        self.view.setNeedsUpdateConstraints()

        // FIXME: moveto not effect!!
          if self.selectedPageIndex != 0 {
              self.pageViewController.moveToViewController(at: self.selectedPageIndex)
          }
    }

    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        // This can work, but I didn't want to move in 'viewDidAppear'
//        if !self.didFirstMoveToSelectedIndex && self.selectedPageIndex != 0 {
//            self.pageViewController.moveToViewController(at: self.selectedPageIndex)         
//            self.didFirstMoveToSelectedIndex = true
        }
    }
        
    override func updateViewConstraints() {
        if !self.didSetupConstraints {
            self.pageViewController.view.snp.makeConstraints { (make) in
                make.top.equalTo(self.topLayoutGuide.snp.bottom)
                make.left.right.equalTo(self.view)
                make.bottom.equalTo(self.bottomLayoutGuide.snp.bottom)
            }
            
            self.didSetupConstraints = true
        }
        
        super.updateViewConstraints()
    }

}
`
Question: Why I move to in 

> viewDidLoad not work
but in 

> viewDidAppear can work!!

**Comment by sudafly** [comment]
This works for me:
self.moveToViewController(at: 1, animated: true)

**Comment by codwam** [comment]
No, cause I have a childViewController?
I have attention to the 'moveToViewController' which the 'view.window == nil', so it can't move.

**Comment by Dagogatc** [comment]
Try this pull request [XLPagerTabStrip#395](https://github.com/xmartlabs/XLPagerTabStrip/pull/395). It should fix this issue.

**Comment by codwam** [comment]
@Dagogatc 

`
        self.pageViewController.moveToViewController(at: self.selectedPageIndex, animate: true)
`
Also not working.

1. **animate = true**
`updateContent` method update `preCurrentIndex = currentIndex`
2. **animate = false**
In your pull request code:
`containerView.setContentOffset(CGPoint(x: pageOffsetForChild(at: subindex), y: 0), animated: animated)`
The `contentOffset` is right. But I print the containterView which `contentOffset` also `{0, 0}`.

`
po containerView!
<UIScrollView: 0x7a6b1a10; frame = (0 60; 320 508); clipsToBounds = YES; autoresize = W+H; gestureRecognizers = <NSArray: 0x7a6b8260>; layer = <CALayer: 0x7a1de050>; contentOffset: {0, 0}; contentSize: {0, 0}>
`
