### ISSUE TITLE
Unable to move to a different controller in viewDidLoad

### ISSUE THREAD

**Issue by Woodyjl** [xmartlabs/XLPagerTabStrip#416]
Hey,

I've been using ButtonBarPagerTabStripViewController with the latest release 7.0.0. And when calling moveToViewController(at: 1, animated: false) in my viewDidLoad it worked as intended. Now I wanted to add an image to the tabs, so I had to download the latest commits from master as mentioned in previous issue reports. After doing that, moveToViewController(at: 1, animated: false), does not function as intend.

Note: I did call moveToViewController(at: 1, animated: false) after super.viewDidLoad 

I attempted to find the problem and make quick fix, and it seems like precurrent index's value is changed before

override open func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        lastSize = containerView.bounds.size
        updateIfNeeded()
        let needToUpdateCurrentChild = preCurrentIndex != currentIndex
        if needToUpdateCurrentChild {
            moveToViewController(at: preCurrentIndex)
        }
        isViewAppearing = false
        childViewControllers.forEach { $0.endAppearanceTransition() }
    }

is called. 

I attempt just call moveToViewController(at: 1, animated: false) in my viewdidappear, however there is an unpleasing animation when doing that.

**Comment by Dagogatc** [comment]
@Woodyjl can you try this pull request [XLPagerTabStrip#395](https://github.com/xmartlabs/XLPagerTabStrip/pull/395)? It should fix this issue.

**Comment by Woodyjl** [comment]
@Dagogatc Thank you that fixed the problem, however because of another problem with spacing in bar button view that has appeared with the latest from master I just pulled 7.0.0 then added the missing image view and made the appropriate updates. Thanks again!
