### ISSUE TITLE
Gap between tab bar and child view controller.

### ISSUE THREAD

**Issue by Ariavm95** [xmartlabs/XLPagerTabStrip#418]
I'm using the last XLPagerTabStrip pod and xcode 8.3.3. I'm not sure if the bug comes from my code or XLPagerTabstrip code. I have a gap between tab bar and the view under the tab bar. I can fix it by changing constraints, but the real problem is when I click on tab items, it kind of shift the view up and fix the gap. However, if I swipe, it wouldn't shift it up.
![simulator screen shot jul 20 2017 1 38 20 am](https://user-images.githubusercontent.com/13060287/28408442-4eb95038-6cec-11e7-8224-115c1c628680.png)

**Comment by Kaakati** [comment]
Go to View Controller Attributes Insprector and **Uncheck Under top bars**

**Comment by serendipityfierce** [comment]
I unchecked **Adjust Scroll View Insets** because unchecking **Under Top Bars** makes the navigation bar look weird.

**Comment by pandeyambuj** [comment]
override public var scrollPercentage: CGFloat { containerView.contentOffset.y = 0.0 return super.scrollPercentage }

This worked for me on container viewcontroller.

https://github.com/xmartlabs/XLPagerTabStrip/issues/200

**Comment by abesmon** [comment]
It's good to mention, that you should disable "Adjust Scroll View Insets" on StripViewController not on its embed viewControllers. That wasnt clear to me, so maybe it helps someone
