### ISSUE TITLE
Assigning image to tab, followup.

### ISSUE THREAD

**Issue by davilaeric** [xmartlabs/XLPagerTabStrip#423]
Currently using pods - 'XLPagerTabStrip', '~> 7.0'  Xcode 8.0 swift 3

Currently experiencing a similar issue with setting the image as mentioned in a previous thread #404 
I was confused by the suggested solution being pointing to the latest commit in master branch. How exactly is this done? In my podfile I have it set as it is written above.

**Comment by santiagofm** [comment]
hey @davilaeric !
You can do that with `pod 'XLPagerTabStrip', :git => 'https://github.com/xmartlabs/XLPagerTabStrip.git', :branch => 'master'`
Cheers
