### ISSUE TITLE
UISearchBar not showing up

### ISSUE THREAD

**Issue by chickdan** [xmartlabs/XLPagerTabStrip#435]
XLPagerTabStrip: 7.0, Xcode 8.3.3 and iOS 10

When incorporating XLPagerTabStrip I cannot display a UISearchBar. In one of my collection views I instantiate a `UISearchBar()` and provide its settings. I then use `self.navigationItem.titleView = searchBar` to assign the search bar to the navigation bar. I have verified that it works without XLPagerTabStrip, but once I put the collectionView in the PagerTabStrip the search no longer appears.

I've tried `self.parent?.navigationItem.titleView = searchBar` since PagerTabStripViewController adds the view controllers as child views. But it still doesn't work.

**Comment by ismailtosun** [comment]
+1
