### ISSUE TITLE
Release the version 2.0 with Pod ?

### ISSUE THREAD

**Issue by christopherney** [xmartlabs/XLPagerTabStrip#44]
Hi,

Can you release the version 2.0 with cocoa pod ?

Thank.

**Comment by mastermyx** [comment]
My XLPager is not working anymore, is it a link with the new version?

**Comment by mtnbarreto** [comment]
@christopherney 
done!
https://github.com/xmartlabs/XLPagerTabStrip/releases/tag/v2.0.0

**Comment by christopherney** [comment]
Thank you !
