### ISSUE TITLE
iOS 11, XLPagerTabStrip v7.0.0 , Bug's titleView in TwitterPagerTabStripViewController mode

### ISSUE THREAD

**Issue by jkpang** [xmartlabs/XLPagerTabStrip#452]
TwitterPagerTabStripViewController mode, enter the second after the sub-controller, and then switch to other interface, and then switch back, the titleView offset

iOS11,0 and XLPagerTabStrip 7.0.0 environment
![simulator screen shot - iphone 6s - 2017-09-24 at 15 15 22](https://user-images.githubusercontent.com/17583451/30780461-cc5d0850-a0d0-11e7-927a-a8c954233dfe.png)

![2017-09-24 15_29_08](https://user-images.githubusercontent.com/17583451/30780428-2a3f001e-a0d0-11e7-8371-b8189ee24656.gif)

**Comment by allen-rahman** [comment]
[Try with my method.](https://github.com/xmartlabs/XLPagerTabStrip/issues/451)
