### ISSUE TITLE
[BUG] Bundle Loading

### ISSUE THREAD

**Issue by mlequeux** [xmartlabs/XLPagerTabStrip#453]
Hi,

I recently moved to static libraries in order to improve my app launch time, it's a new feature since Xcode 9 beta 4

```
New in Xcode 9 – Swift static libary support.
    - Added support for static library targets that contain Swift
```

However, there is a problem in the Bundle loading for this framework, the codes assumes the framework is at the top level, which is not always the case, especially when creating static libraries,

See the attached PR for a fix !

Thank you,
Martin

**Comment by mlequeux** [comment]
https://github.com/xmartlabs/XLPagerTabStrip/pull/454

**Comment by mtnbarreto** [comment]
👍  merged
