### ISSUE TITLE
How to Scroll To the Second Tab programmatically

### ISSUE THREAD

**Issue by unittesting0** [xmartlabs/XLPagerTabStrip#462]
Hi guys,

How can I scroll to the Second Tab programmatically?

Respect.

**Comment by ahmedsafadii** [comment]
inside viewdidappear use this

                self.moveToViewController(at: 1,animated: false)

**Comment by unittesting0** [comment]
Thank you very much @ahmedsafadii

**Comment by aabantariqmurtaza** [comment]
Never use the index which is already selected
else you would waste your time alot.
