### ISSUE TITLE
Update from swift 4 branch caused layout issue

### ISSUE THREAD

**Issue by pselok** [xmartlabs/XLPagerTabStrip#463]
Xcode 9.0, iOS 11.0.2
Everything was perfect with swift 4 branch, just updated to master and get this (screenshot). By the way it's not compiling in swift 4 language, if i choose swift 3.2 in build settings - everything is fine with compiling and layout.
![img_0661](https://user-images.githubusercontent.com/16443790/31242111-aa6a675a-aa0e-11e7-9bce-ddcc37fdf42a.jpg)

**Comment by happiehappie** [comment]
Would be great to explain your solution before closing it

**Comment by pselok** [comment]
I've just re-installed the pod, sorry for late response
