### ISSUE TITLE
containerView is not scrolling vertically.

### ISSUE THREAD

**Issue by anupamkgit** [xmartlabs/XLPagerTabStrip#469]
full frame of child view is not visible how to make  child view scrollable. I have designed all desigen in storyboard and connected scroll view to containerView when i move to child view i am not able to see bottom component of child view and its not scrollable how can I fix this issue? please suggest

**Comment by billyriantono** [comment]
hi @anupamkgit  are you have solve this issue ? i have same problem with you also :) thank you

**Comment by 240987** [comment]
Anyone have solution? I too have same issue

**Comment by Namdh1212** [comment]
I too have same issue

**Comment by anafinotti** [comment]
I just set the containerView equalWidth to the scrollview and it worked.

**Comment by GelarAulia** [comment]
> I just set the containerView equalWidth to the scrollview and it worked.

@anafinotti can you elaborate how to set containerView equalWidth to the scrollview?

also, @anupamkgit do you fixed this issue? I'm having the same problem.

**Comment by GelarAulia** [comment]
Nevermind I got it working. I just create a scroll view in my child view.

**Comment by imvasim313** [comment]
What you can do is remove the top level view. and put container-view and on top of it collection view. so the hierarchy will be like container view and on top of it collection view.
