### ISSUE TITLE
Animation when scrolling to new view controller is choppy

### ISSUE THREAD

**Issue by AnthonyMDev** [xmartlabs/XLPagerTabStrip#47]
The animation when scrolling to a new view controller seems choppy. Once you get 50% of the way to the next view controller, it snaps right to that view controller.

This feels odd to me. Is there any way to edit the animations to make the transition smoother?

**Comment by michaelEllisUy** [comment]
I've just fixed this issue! thanks for reporting it!

**Comment by AnthonyMDev** [comment]
I'll check out the new stuff shortly! Thanks for the fix!
Any chance we can get a new version of the Pod for this please?
