### ISSUE TITLE
ButtonBarPagerTabStripViewController - Trigger to switching the tab from Child 2 to Child1

### ISSUE THREAD

**Issue by hieptm89** [xmartlabs/XLPagerTabStrip#471]
I have an issue when switching the tab from Child 2 to Child1
IE: I want to go back to child 1 from child 2 after finishing an API call.
Child 1 has a lot of item like textfield, checkbox, image
Child 2 has a tableview list data
When I click on a record of Child 2 then switching to Child1 and fill data to Child 1.

I tried to call the method moveToViewControllerAtIndex:0 in didSelectRowAtIndexPath of tableViewList but it doesn't work.

> MyMainViewController *screen = [[MyMainViewController alloc] initWithNibName:@"MyMainViewController" bundle:nil];
    [screen moveToViewControllerAtIndex:0 animated:YES];

Please show me how to implement that method.

<img width="313" alt="screen shot 2017-10-19 at 2 53 16 pm" src="https://user-images.githubusercontent.com/32859553/31759972-4595e69a-b4dd-11e7-86ab-ef8573a06043.png">

**Comment by pschneider** [comment]
Probably because you create a new view controller instead of using the one your tabs are in. Did you try calling it on the `parent` property? Keep in mind that you may have to cast the parent to the correct Class Type before being able to call `moveToViewControllerAtIndex`

**Comment by hieptm89** [comment]
Thank you @pschneider so much.
It works when I calling the **parent** property.
