### ISSUE TITLE
buttonBarView not show in ios 10.3.3

### ISSUE THREAD

**Issue by huongtran84** [xmartlabs/XLPagerTabStrip#474]
in ios 11 iphone 6 , buttonbarview showing
![img_934e196d52e1-1](https://user-images.githubusercontent.com/4927097/31937363-633cd320-b8de-11e7-90a4-c67091d4283d.jpeg)

but in ios 10.3.3 iphone 5s
![img_0652](https://user-images.githubusercontent.com/4927097/31937401-7a83bf30-b8de-11e7-8a6b-8f9d1f4c7e52.JPG)

I am confusing with it.I am use xlpagertabstrip 8.0 xcode 9.0.
anyone can help me? thanks

**Comment by junweimah** [comment]
i am having this problem too. What is the solution?

**Comment by huongtran84** [comment]
for me.it is buttonbarview below containerview I changed buttonbarview above container view

**Comment by junweimah** [comment]
ok thanks ill try it out. So it actually support 5s with 10.3.3?

**Comment by junweimah** [comment]
but wait, my buttonbarview is already above container view.

**Comment by junweimah** [comment]
Hey i managed to show the buttonbarview, now there is a white space between that buttonbar and my tableview on the 5s, you have any idea?

**Comment by phyominthu** [comment]
@junweimah I'm having the same issue right now. ButtonBarView is visible on my **iOS 11.1 Simulator**, but not on my **iOS 10.3.3 iPhone 5S**. I don't have an actual device with iOS 11 so I'm not sure if this depends on OS version or not.

How did you solve the issue? Thanks.

**Comment by junweimah** [comment]
@phyominthu 

In your scene have your container view positioned above button bar view

something like this: 

![image](https://user-images.githubusercontent.com/21700014/33526156-b406b466-d877-11e7-81da-65fe1c32c53c.png)

**Comment by phyominthu** [comment]
Wow. It's working! Thank you so much @junweimah

**Comment by junweimah** [comment]
@phyominthu 

no problem. i think this is some kind of bug. hopefully people see this thread in the future when having the same problem

**Comment by phyominthu** [comment]
@junweimah and... how did you solve the white space above container view, which just appeared right now?

**Comment by junweimah** [comment]
@phyominthu 
Dont quite remember this one, try to play around with constraint. make sure your constraints are all set correctly, leaving no space in between

**Comment by phyominthu** [comment]
@junweimah The whitespace appears in container view if I scroll horizontally with my finger. The whitespace disappears if I tap on an item in ButtonBarView.

Tried resetting the constraints, but doesn't work :(

**Comment by phyominthu** [comment]
@junweimah Thanks. I found the solution for whitespace in #200

**Comment by junweimah** [comment]
@phyominthu 
great!
