### ISSUE TITLE
App crash in iOS 8.1

### ISSUE THREAD

**Issue by PH9** [xmartlabs/XLPagerTabStrip#487]
Xcode 9.1
XLPagerTabStrip 8.0, build with Carthage
Simulator: iPhone 4s with iOS 8.1

Console output:

> 2017-11-19 23:35:21.452 applicationName[87544:882431] Warning once only: Detected a case where constraints ambiguously suggest a height of zero for a tableview cell's content view. We're considering the collapse unintentional and using standard height instead.

And in
File name: PagerTabStripViewController.swift
Line: 105 reloadViewControllers()

> Thread 1: Fatal error: viewControllers(for:) should provide at least one child view controller

Other simulator just work fine.

**Comment by PH9** [comment]
Change sequence of setup tab bar to br more priority and it is work

**Comment by Arshad-iOSDeveloper** [comment]
Answer is not clear, please provide more details.
