### ISSUE TITLE
put image above title text ?

### ISSUE THREAD

**Issue by ajonno** [xmartlabs/XLPagerTabStrip#495]
thanks for providing this lib. works well for us.

is it possible in a ```ButtonBarPagerTabStripViewController``` , to place an image _above_ the title text ?

like this ?
![2017-12-04_17-22-13](https://user-images.githubusercontent.com/3005269/33538869-b9a1ed64-d917-11e7-9374-3ab3c4d404b2.png)

**Comment by ykws** [comment]
@ajonno Hi, Add Example Youtube with Label.
Best Regards!

![screen shot 2017-12-08 at 22 02 27](https://user-images.githubusercontent.com/5770480/33767064-876355aa-dc63-11e7-87e6-d09559708209.png)
