### ISSUE TITLE
iPhoneX safe area problem.

### ISSUE THREAD

**Issue by ShockUtility** [xmartlabs/XLPagerTabStrip#498]
There is a problem with the 'safe area' in landscape mode on iPhoneX.

Xcode 9.2(9C40b)
iOS 11.2
XLPagerTabStrip : 2017.12.06 download

<img width="863" alt="1" src="https://user-images.githubusercontent.com/657050/33692390-63f2c0e4-db30-11e7-891c-6807a5dcfdb7.png">

**Comment by brianb7590** [comment]
Seeing the same problem on a project using the library. Safe Area seems to be ignored when in Landscape.

**Comment by leetal** [comment]
Yes, this is a real issue. It seems like the cached size of the view is retained and not recalculated upon rotation on a device that respects safe are guides.

**Comment by artur7** [comment]
You can fix it by calling : `override func viewWillTransition(to size: CGSize, with coordinator: UIViewControllerTransitionCoordinator) {
        coordinator.animate(alongsideTransition: { (_) in
            
        }, completion: { _ in
            self.reloadPagerTabStripView()
        })
        
        super.viewWillTransition(to: size, with: coordinator)
    }`
in parent container View Controller

**Comment by DanielBalsalobre** [comment]
Solved!!!

`if let _ = childController.parent {
                    if #available(iOS 11.0, *) {
                        childController.view.frame = CGRect(x: offsetForChild(at: index) + view.safeAreaInsets.left, y: 0, width: view.bounds.width - (view.safeAreaInsets.left + view.safeAreaInsets.right), height: containerView.bounds.height)
                    } else {
                        childController.view.frame = CGRect(x: offsetForChild(at: index), y: 0, width: view.bounds.width, height: containerView.bounds.height)
                    }
                    childController.view.autoresizingMask = [.flexibleHeight, .flexibleWidth]
                }
                else {
                    childController.beginAppearanceTransition(true, animated: false)
                    addChildViewController(childController)
                    if #available(iOS 11.0, *) {
                        childController.view.frame = CGRect(x: offsetForChild(at: index) + view.safeAreaInsets.left, y: 0, width: view.bounds.width - (view.safeAreaInsets.left + view.safeAreaInsets.right), height: containerView.bounds.height)
                    } else {
                        // Fallback on earlier versions
                        childController.view.frame = CGRect(x: offsetForChild(at: index), y: 0, width: view.bounds.width, height: containerView.bounds.height)
                    }
                    childController.view.autoresizingMask = [.flexibleHeight, .flexibleWidth]
                    containerView.addSubview(childController.view)
                    childController.didMove(toParentViewController: self)
                    childController.endAppearanceTransition()
                }`

**Comment by ikesyo** [comment]
This is just an example problem. Safe area should be handled in each child (content) view controller (otherwise child view controller can't fill the background of entire screen). We can fix the example by updating `PostCell`. I'll address it.

**Comment by ikesyo** [comment]
Submitted #612.

**Comment by rene-dohan** [comment]
Why this still doesn't work for me ? The incorrect solution from DanielBalsalobre looks like works fine so I will use that probably. Maybe because I don't use storyboards , just using lib programmatically, maybe that is not addressed in this issue ??

**Comment by rene-dohan** [comment]
Or somethinng like this...

```
override open func updateContent() {
        super.updateContent()
        for (index, childController) in controllers.enumerated() {
            childController.view.frame = CGRect(x: offsetForChild(at: index) + view.safeAreaInsets.left,
                    y: 0, width: view.bounds.width - (view.safeAreaInsets.left + view.safeAreaInsets.right),
                    height: containerView.bounds.height)
        }
    }
```

**Comment by mengjang** [comment]
> Why this still doesn't work for me ? The incorrect solution from DanielBalsalobre looks like works fine so I will use that probably. Maybe because I don't use storyboards , just using lib programmatically, maybe that is not addressed in this issue ??

Doesn't work for me, either.  I don't use storyboards.

**Comment by antileks** [comment]
My solution (based on rene-dohan's answer): 

```
override open func updateContent() {
  super.updateContent()
        
  // Refresh safeArea constraints
  viewControllers[currentIndex].view.setNeedsUpdateConstraints()
}
```
