### ISSUE TITLE
Black line between navigationbar and XLPagerTabStrip

### ISSUE THREAD

**Issue by danielstorch** [xmartlabs/XLPagerTabStrip#502]
iOS version: 11.2
Xcode: 9.2
XLPagerTabStrip: 8.0.0

There is a black line between the `navigationbar` and the `XLPagerTabStrip` which i cant remove or change color of. Im not sure if it is the `navigationbar` or the `XLPagerTabStrip`. In views where i don't have XLPagerTabStrip implemented, the black line is not visible.

XLPagerTabStrip implementation:

```
class NewsTabViewController: ButtonBarPagerTabStripViewController{
    
    override func viewDidLoad() {
        
        settings.style.buttonBarBackgroundColor = Colors.Red
        settings.style.buttonBarItemBackgroundColor = .clear
        settings.style.selectedBarBackgroundColor = Colors.Red
        
        settings.style.selectedBarHeight = 0
        settings.style.buttonBarItemFont = .boldSystemFont(ofSize: 14)
        settings.style.buttonBarMinimumLineSpacing = 0
        settings.style.buttonBarItemsShouldFillAvailableWidth = true
        settings.style.buttonBarLeftContentInset = 0
        settings.style.buttonBarRightContentInset = 0
        
        pagerBehaviour = .progressive(skipIntermediateViewControllers: false, elasticIndicatorLimit: false)
        
        changeCurrentIndexProgressive = {(oldCell: ButtonBarViewCell?, newCell: ButtonBarViewCell?, progressPercentage: CGFloat, changeCurrentIndex: Bool, animated: Bool) -> Void in
            guard changeCurrentIndex == true else { return }
            oldCell?.label.textColor = Colors.White_Alpha
            newCell?.label.textColor = Colors.White
            
        }
        
        super.viewDidLoad()
    }
}
```

In the AppDelegate i change the appearance of the `navigationbar` like this 

```
UINavigationBar.appearance().barTintColor = Colors.Red
UINavigationBar.appearance().tintColor = Colors.White
UINavigationBar.appearance().titleTextAttributes = [NSAttributedStringKey.foregroundColor : Colors.White, NSAttributedStringKey.font : UIFont.systemFont(ofSize: 17.0)]
UINavigationBar.appearance().isTranslucent = false
UIApplication.shared.statusBarStyle = UIStatusBarStyle.lightContent
```

<img width="406" alt="bildschirmfoto 2017-12-10 um 23 40 12" src="https://user-images.githubusercontent.com/5611423/33810419-7c1b4386-de04-11e7-9620-6002b932b0c8.png">

**Comment by junweimah** [comment]
have you found a solution for this?

**Comment by danielstorch** [comment]
Nope. Do you gave the same problem?

**Comment by junweimah** [comment]
Yeah. I wanted to remove it but dont know how

**Comment by ducminh1012** [comment]
That's the shadow of the navigation bar.
You can remove by 2 lines:  ```self.navigationController?.navigationBar.setBackgroundImage(UIImage(named: ""), forBarMetrics: UIBarMetrics.Default)```
```self.navigationController?.navigationBar.shadowImage = UIImage(named: "")```

**Comment by danielstorch** [comment]
Thanks for the tip. Your code didn't rly fix it for us, but i knew what to search for.

This code fixed it. Calling this code in a "MainViewController" which most other controllers are inheriting from

```
let imageSize = CGSize(width: 1, height: 1)
let backgroundImage = UIImage.imageWithColor(Colors.Red, size: imageSize)        
self.navigationController?.navigationBar.setBackgroundImage(backgroundImage, for: .default)        
let shadowImage = UIImage.imageWithColor(Colors.Red, size: imageSize)        
self.navigationController?.navigationBar.shadowImage = shadowImage
```

**Comment by AlessioSpallino** [comment]
A more elegant way to eliminate the white line:

`override func viewWillAppear(_ animated: Bool) {
        super.viewWillAppear(animated)
        
        navigationController!.navigationBar.isHidden = false
        
        let transparentPixel = UIImage(named: "transparent")
        self.navigationController?.navigationBar.shadowImage = transparentPixel
        self.navigationController?.navigationBar.barTintColor = UIColor(red: 102/255, green: 57/255, blue: 183/255, alpha: 1.0)
        self.navigationController?.navigationBar.isTranslucent = false
        self.navigationController?.navigationBar.titleTextAttributes = [NSForegroundColorAttributeName : UIColor.white]
    }`
