### ISSUE TITLE
dynamic changing pagerTabStripChildViewControllers

### ISSUE THREAD

**Issue by br1anchen** [xmartlabs/XLPagerTabStrip#52]
I was trying to use `XLButtonBarPagerTabStripViewController` as extended ViewController,

using delegate method

```
- (NSArray *)childViewControllersForPagerTabStripViewController:(XLPagerTabStripViewController *)pagerTabStripViewController
```

to set `@property NSMutableArray *tabCtrlsArray` as return childViewControllers,

basic logic was one of the children view controller has sub detail view controller (under navigation controller) will trigger `XLButtonBarPagerTabStripViewController` to mutate `tabCtrlsArray`, then call `reloadPagerTabStripView` method to reload the contents.

However, `reloadPagerTabStripView` is not always changing the contents afterwards, which seems like some async issues.

But when I debug the process in `XLButtonBarPagerTabStripViewController`, the children view controllers seem changing correctly but not the view. And it happens randomly.

PS: In the sub detail view controller to get `XLButtonBarPagerTabStripViewController`:

```
PagerTabStripController *ptsCtrl = [self.storyboard instantiateViewControllerWithIdentifier:@"PagerTabStripCtrl"];
[ptsCtrl changeChildrenViewCtrls];
```

Is there any better way to mutate the `pagerTabStripChildViewControllers` in `XLPagerTabStripViewController`?

**Comment by htarwara6245** [comment]
@br1anchen,did you solve it out?I was doing the same thing,too.It was like google play store which page menu are changing dynamically.If you made it out,can you share me please?

**Comment by Urkman** [comment]
Any Solution for this?

**Comment by sina-kh** [comment]
My question, too!

**Comment by osrl** [comment]
+1

**Comment by htarwara6245** [comment]
Same here... Need help!!

http://stackoverflow.com/q/42338139/3378606

**Comment by andy1247008998** [comment]
Hello guys,

I'd like to share how I solve this problem. It's quite simple.

1. let newVC = self.storyboard.xxx
2. childList.append(newVC)  //or insert etc
3. self.reloadPagerTabStripView() //you will see that newVC
4. self.reloadInputViews() // I can't recall why wrote this line. Fix ButtonBarView synchronization problem?

**Comment by m-revetria** [comment]
Related issue #349
