### ISSUE TITLE
iPhone X layout issue after Full Screen Presented VC dismiss

### ISSUE THREAD

**Issue by bishalg** [xmartlabs/XLPagerTabStrip#524]
- XLPagerTabStrip  v8.0
- Xcode 9.2
- iOS 11.2

I have a case where the view controller needs to be presented as Over Full Screen

`self.mediaPlayerVC.modalPresentationStyle = UIModalPresentationOverFullScreen;`

but for the case of `UIModalPresentationFullScreen` there is no such issue as the view is reloaded.

I have delegate of the MediaVC on HomeVC and hence on close action 
`[mediaPlayerVC dismissViewControllerAnimated:true completion:nil];`

The issue is after the media Player is dismissed there is wearied layout issue on Home VC which is only present on iPhone X device. There is no layout issue on other iPhone Devices.

As shown below in red box there is extra space to the right of the view controller afte the dismissing the presented VC. Which also effects the previous child view controller in PagerTabStrip.

![iphonex clips](https://user-images.githubusercontent.com/805689/35472389-62ff4c50-0396-11e8-8b51-225a98d02d0a.png)

<img width="309" alt="iphone x - previous tabs" src="https://user-images.githubusercontent.com/805689/35472402-81677d02-0396-11e8-98ef-cab9ba196116.png">

After the scroll action the layout does snap to place but the supplementary view's title and scroll view indicator are still out of layout.

![iphone x indicator](https://user-images.githubusercontent.com/805689/35472418-e04b47e0-0396-11e8-8bd6-6f177e3ef7b8.png)

**Comment by danieldesouzadev** [comment]
I have the same problem :(

**Comment by danieldesouzadev** [comment]
To solve, I disabled the horizontal scroll

**Comment by bishalg** [comment]
@danieldesouzadev : can you share the code? 
Which scroll view? Child of View Controller ButtonBarPagerTabStripViewController ?
or the collection view's scroll?

**Comment by bishalg** [comment]
@danieldesouzadev : i have found another solution to the problem 
```
- (void)dismissMediaPlayer:(MediaVC *)mediPlayer {
    /// NOTE : As the cast media player is not full screen presentation it will casue view to reaload again
    /// if modalPresentationStyle = UIModalPresentationOverFullScreen is used no such issue exists but
    /// page controller layout will be disturbed
    dispatch_async(dispatch_get_main_queue(), ^{
        [mediPlayer dismissViewControllerAnimated:true completion:^{
            UIViewController *vc = [[UIViewController alloc] init];
            vc.hidesBottomBarWhenPushed = YES;
            [self.navigationController pushViewController:vc animated:NO];
            [self.navigationController popViewControllerAnimated:NO];
        }];
    });
}
```

Here the hack is to push the dummy vc into the navigation stack and pop again this will fix the layout issue.
