### ISSUE TITLE
No such module 'XLPagerTabStrip'

### ISSUE THREAD

**Issue by Jussiadev** [xmartlabs/XLPagerTabStrip#547]
i use tutorial https://medium.com/michaeladeyeri/how-to-implement-android-like-tab-layouts-in-ios-using-swift-3-578516c3aa9 and get error ` No such module 'XLPagerTabStrip'`

My Podfile

```
# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

target 'NewsTabs' do # Comment the next line if you're not using Swift and don't want to use dynamic frameworks use_frameworks!

pod 'XLPagerTabStrip', '~> 8.0'

end 
```

**Comment by prakasha-maravanthe** [comment]
I have the same issue:

For me this error appears only when I set the App's Deployment Target to 10.0 and try to Archive Product.
