### ISSUE TITLE
Plus Versions Layout Issues (fine on non-Plus devices)

### ISSUE THREAD

**Issue by djneely** [xmartlabs/XLPagerTabStrip#551]
Odd issue with Plus versions of phones.

- Environment: XLPagerTabStrip, Xcode and iOS version you are using.

XLPagerTabStrip 8.0.0 (Cocoapods)
Xcode  9.2
iOS 11.2
iPhone 8 Plus (only appears to show up in the Plus versions)

- In case of reporting errors, provide Xcode console output of stack trace or code compilation error.

No console log info to provide

- Any other additional detail such as example code that you think it would be useful to understand, reproduce and solve the problem.

Plus series issue? This works fine on the 6s, 7, 8, and X but not on the Plus versions of theses same phones (less any X Plus which doesn't exist yet)

We've got a basic CollectionView of images populating the first tab. On first load the collection view cells are appearing off of the screen on both sides. However, after scrolling they snap into place. See screen shots. If we take this same collection view and just push it onto the navigation stack to compare, the views look fine. And odd thing is this only seems to appear on the Plus versions of the phone and not their smaller counterparts.

For all of the views I have their constraints pinning their leading, trailing, top, bottom guides to the bottom. Loading everything from storyboard instances.

**First load**

![simulator screen shot - iphone 8 plus - 2018-03-14 at 15 19 44](https://user-images.githubusercontent.com/981157/37425900-68f975bc-279b-11e8-9da5-cd78806b8426.png)

**After touching to scroll**

![simulator screen shot - iphone 8 plus - 2018-03-14 at 15 19 51](https://user-images.githubusercontent.com/981157/37425956-9009470e-279b-11e8-9d63-44f330094a52.png)

**Same view loaded (first load) without using the Tabs.**

![simulator screen shot - iphone 8 plus - 2018-03-14 at 15 20 03](https://user-images.githubusercontent.com/981157/37425961-93df346a-279b-11e8-998d-90bb428e17dd.png)

I feel like this is something really goofy but racking my brain over it for a while now.

**Comment by djneely** [comment]
Meant to mention we're seeing this issue with UITableViews as well. On initial load of the view the table view is wider than it should be, but after a slight swipe it re-adjusts itself into its correct layout.

**Comment by djneely** [comment]
I want to apologize for submitting this as an issue. It appears one of the developers did some weird wonky wrapping of items within other items and thus constraints got all wonked out. I've since rebuilt the VC and containers and I have things working correctly.

**Comment by vaibhavsingla1996** [comment]
HI djneely
I know it's been a long time since you post the answer. I am facing a similar issue (On initial load of the view the table view is wider than it should be, but after a slight swipe it re-adjusts itself into its correct layout.) but not able to figure out by checking my views constraints. I have used safe area for every content View. I am not able to work out the issue yet.

**Comment by djneely** [comment]
@vaibhavsingla1996 its been a while since I've had to work with this code but from the looks of it we've got a few sections that helped us get past this. But ultimately we're initializing the collectionView all via code.

```swift
func setupCollectionView() {
        let layout = UICollectionViewFlowLayout.init()
        self.collectionView = UICollectionView.init(frame: CGRect(x: 0.0, y: 0.0, width: self.view.frame.width, height: self.view.frame.height), collectionViewLayout: layout)
        self.collectionView!.contentInset = UIEdgeInsets(top: 10, left: 10, bottom: 150, right: 10)
        self.collectionView!.alwaysBounceVertical = true
        self.collectionView!.delegate = self
        self.collectionView!.dataSource = self
        self.collectionView!.register(UINib(nibName: "CollectionViewCell", bundle: nil), forCellWithReuseIdentifier: CollectionViewCell.identifier)
        self.collectionView!.addSubview(self.refreshControl!)
        self.view.addSubview(self.collectionView!)
        
        // set collection view autolayout constraints to fill container view
        self.collectionView!.translatesAutoresizingMaskIntoConstraints = false
        self.collectionView!.leadingAnchor.constraint(equalTo: self.view.leadingAnchor).isActive = true
        self.collectionView!.trailingAnchor.constraint(equalTo: self.view.trailingAnchor).isActive = true
        self.collectionView!.topAnchor.constraint(equalTo: self.view.topAnchor).isActive = true
        self.collectionView!.bottomAnchor.constraint(equalTo: self.view.bottomAnchor).isActive = true
    }
```

The we're also prompting the collectionView to refresh its layout as well

```swift
override func viewWillLayoutSubviews() {
        super.viewWillLayoutSubviews()
        self.collectionView?.setNeedsDisplay()
        self.collectionView?.setNeedsLayout()
        self.collectionView?.layoutIfNeeded()
    }
```
Again, as you can tell by the date its been quite some time since we ran into this issue and then resolved it. I believe this is how we got past it.

Best of luck!
