### ISSUE TITLE
Version 8.0.1 now supports iOS 9.0+ and this is not documented

### ISSUE THREAD

**Issue by danielpetroianu** [xmartlabs/XLPagerTabStrip#562]
Current released version 8.0.1 has the minimum deployment target set to iSO 9.
In [README.md](https://github.com/xmartlabs/XLPagerTabStrip/blob/8.0.1/README.md#requirements) the Requirements specify iOS 8.0+.

@mtnbarreto Is the minimum deployment target a mistake, or the documentation was not updated?

My two cents: 
I consider changing minimum deployment target a braking change, so maybe increment the major/minor version and not the patch version

**Comment by mtnbarreto** [comment]
Hi @danielpetroianu , Seems it's a mistake. 
Podspec specification indicates 8.0. https://github.com/xmartlabs/XLPagerTabStrip/blob/master/XLPagerTabStrip.podspec#L10

Could you put it back to 8.0 in the Xcode project definition ?

**Comment by danielpetroianu** [comment]
sure, i'll make a pull request

**Comment by danielpetroianu** [comment]
made this pull request #566
