### ISSUE TITLE
swift header error  Cannot find interface declaration

### ISSUE THREAD

**Issue by ahmedAlmasri** [xmartlabs/XLPagerTabStrip#590]
Hi 

XLPagerTabStrip version 8.0.1 
Xcode version 9.4 
iOS version 11.4

this issue provide if using  myproject-swift.h 

error message  

>Cannot find interface declaration for 'ButtonBarPagerTabStripViewController', superclass of 'ParentViewController'

![screen shot 2018-07-11 at 9 42 04 am](https://user-images.githubusercontent.com/14888785/42554946-5dfa3d7a-84ef-11e8-9626-d4e5e8d4469f.png)

**Comment by Sanadbarjawi** [comment]
+1

**Comment by hardikdarji** [comment]
any solution for this?

**Comment by ahmedAlmasri** [comment]
@hardikdarji just add `#import "XLPagerTabStrip-Swift.h"` in your header
