### ISSUE TITLE
Swiping Tabs Works Great, But Clicking Causes an issue

### ISSUE THREAD

**Issue by osbash** [xmartlabs/XLPagerTabStrip#594]
Using: ButtonBarPagerTabStripViewController

I have two tabs and when swiping between the tabs, everything works as expected.

But for some reason, when I click / swipe to the RIGHT tab, then CLICK on the left tab:

The left tab's color changes correctly
The view shows correctly
The bar below the tab remains under the previously selected tab

**Comment by nikhil191090** [comment]
@osbash I am also getting this issue did u resolved it .???

**Comment by Ruman1234** [comment]
add this in viewdidload()
            buttonBarView.selectedBar.frame.origin.x = buttonBarView.frame.size.width + 1
and add this code
 override func viewDidAppear(_ animated: Bool) {

    }
    override func viewWillAppear(_ animated: Bool) {

            buttonBarView.selectedBar.frame.origin.x = buttonBarView.frame.size.width + 1

        }

    }

**Comment by kevinng** [comment]
Any solution found?

**Comment by mr-voleybolist** [comment]
Проблема все еще актуальна
