### ISSUE TITLE
Hi! I have a little problem.

### ISSUE THREAD

**Issue by xhzengAIB** [xmartlabs/XLPagerTabStrip#6]
@mtnbarreto 

When i insert some code in https://github.com/xmartlabs/XLPagerTabStrip/blob/master/XLPagerTabStrip/Demo/ChildViewController/TableChildExampleViewController.m#L32

```objc
- (void)tableView:(UITableView *)tableView didSelectRowAtIndexPath:(NSIndexPath *)indexPath {
 
     SameViewController *sameViewController = [[SameViewController alloc] init];
     [self presentViewController:sameViewController animated:YES completion:NULL];

}
```
but sameViewController InterfaceOrientations is UIInterfaceOrientationMaskLandscapeRight.

code :
```objc
- (NSUInteger) supportedInterfaceOrientations{
    return UIInterfaceOrientationMaskLandscapeRight;
}

- (BOOL)shouldAutorotateToInterfaceOrientation:(UIInterfaceOrientation)toInterfaceOrientation {
    return toInterfaceOrientation == UIInterfaceOrientationLandscapeRight;
}

```

the pager layout appear bug. 

Jack

**Comment by xhzengAIB** [comment]
normal:
![26d414f3-326a-40b6-a01f-788765448cc6](https://cloud.githubusercontent.com/assets/1969908/5738976/1f896302-9c2e-11e4-8224-2bc609840492.png)

bug:
![41b495bf-8e37-4d4e-8766-0464dc6a6940](https://cloud.githubusercontent.com/assets/1969908/5738981/2eeefe38-9c2e-11e4-8871-298e4c4fe72d.png)

**Comment by mtnbarreto** [comment]
@xhzengAIB thanks for the report.
it seems a border edge case. I will take a look when i get back from my vacations. Probably next week.
Regards

**Comment by xhzengAIB** [comment]
@mtnbarreto 
How do I solve?

**Comment by xhzengAIB** [comment]
@mtnbarreto 
I testing demo.
This bug appear iOS8 or later.

Jack

**Comment by mtnbarreto** [comment]
@xhzengAIB Sorry for the delay on the response. The issue seems to be fixed now. See my last commit https://github.com/xmartlabs/XLPagerTabStrip/commit/8a2efcd95f675f058be95ae58ee180dccde5d34e .

Regards

**Comment by xhzengAIB** [comment]
@mtnbarreto 
Thanks, The open source library is very good.

Jack

**Comment by xhzengAIB** [comment]
@mtnbarreto 
Can you release a version?

Jack

**Comment by mtnbarreto** [comment]
@xhzengAIB  I will by early next week.
