### ISSUE TITLE
Navigation bar transparent problems?

### ISSUE THREAD

**Issue by xhzengAIB** [xmartlabs/XLPagerTabStrip#60]
Hello! @mtnbarreto 

Here have a navigation bar transparent problems, 

such as I set
````objc
[[UINavigationBar appearance] setBarStyle: UIBarStyleBlack];
[[UINavigationBar appearance] setTranslucent: YES];
````
and i set The TableViewController like this:
````objc
self.edgesForExtendedLayout = UIRectEdgeAll;
self.automaticallyAdjustsScrollViewInsets = YES;
self.extendedLayoutIncludesOpaqueBars = NO;
````

The navigation bar but cannot see the background transparent.

Jack

**Comment by michaelEllisUy** [comment]
Hey Jack,
 I just did the exact same thing in the demo, changing some constraints and it worked for me.
 If you see closely you can see the background.

If you still have the same problem send an example please :)

![screen shot 2015-08-24 at 11 08 59 am](https://cloud.githubusercontent.com/assets/10197945/9442160/ac4005aa-4a50-11e5-89f3-f726cd00e334.png)
