### ISSUE TITLE
how to fixed always display selected bar

### ISSUE THREAD

**Issue by vanvu08t2** [xmartlabs/XLPagerTabStrip#610]
#
I want to show always selected bar same this picture. please give me how to fixed?

![screen shot 2018-09-02 at 6 04 49 pm](https://user-images.githubusercontent.com/22784076/44955617-58c4cd00-aee0-11e8-9d32-f12c7814519e.png)

**Comment by mtnbarreto** [comment]
`buttonBarItemSpec`  does it.

Take a look at the example project, specifically how we create the youtube tab button..

```swift
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)

        buttonBarItemSpec = ButtonBarItemSpec.nibFile(nibName: "YoutubeIconWithLabelCell", bundle: Bundle(for: YoutubeIconWithLabelCell.self), width: { _ in
                return 70.0
        })
    }
```
