### ISSUE TITLE
Selected bar tab color not changing

### ISSUE THREAD

**Issue by luminkhant** [xmartlabs/XLPagerTabStrip#615]
I am having a trouble changing selected bar color.
I try to change the tab color as the documentation says.
`settings.style.selectedBarBackgroundColor = .yellow`
But my selected tab underline color still being black.
Could u please fix that issue?

**Comment by mehdico** [comment]
I have the same problem.

**Comment by MyFatoorahHub** [comment]
You need to use selected bar parameter like that 
`buttonBarView.selectedBar.backgroundColor = .yellow`

**Comment by mehdico** [comment]
I found a solution : 
put all stylings before super.viewDidLoad()

like this :

```
override func viewDidLoad() {
        settings.style.selectedBarHeight = 3.0
        settings.style.buttonBarBackgroundColor = .white
        settings.style.buttonBarItemBackgroundColor = .white
        settings.style.buttonBarItemTitleColor = .red
        settings.style.selectedBarBackgroundColor = .red
        super.viewDidLoad()
}
```

**Comment by vladbarash** [comment]
@mehdico Thanks! That works for me

**Comment by luminkhant** [comment]
@mehdico  Thanks! That help me too

**Comment by AkilaMurugaiah** [comment]
buttonBarView.selectedBar.backgroundColor = UIColor.yellow
