### ISSUE TITLE
XCode 10 and Swift 4.2 fails to build

### ISSUE THREAD

**Issue by huayingxiong** [xmartlabs/XLPagerTabStrip#620]
Xcode10 fails to build . Whether there is an update plan

**Comment by platoputhur** [comment]
It would be awesome if someone replies to this thread. We would like to know if there is an update plan and  if so, its timeline.

**Comment by platoputhur** [comment]
BTW there is already pull request which fixes this issue: https://github.com/xmartlabs/XLPagerTabStrip/pull/617/commits/7b63bd0c01b01cd278a132d53fe73e17d439d4fa

So I guess they would do the merge as soon as it is tested.

**Comment by qsdnino** [comment]
Please release update for XCode 10 and swift 4.2 support...

**Comment by mats-claassen** [comment]
Hi all, just merged a PR that should fix this. Try out the master branch
