### ISSUE TITLE
White spaces in barButtonView

### ISSUE THREAD

**Issue by zahid119** [xmartlabs/XLPagerTabStrip#622]
I sometimes get white spaces on right side only.
![simulator screen shot - iphone 6 plus - 2018-09-21 at 17 30 29](https://user-images.githubusercontent.com/9412546/45881300-38dc4700-bdc4-11e8-85ec-0c6392e3f3f8.png)

**Comment by mtnbarreto** [comment]
you should set up the view constraints properly.  Follow example project to see how to do so.
