### ISSUE TITLE
Xcode 10, iOS 12

### ISSUE THREAD

**Issue by vamshikpadala** [xmartlabs/XLPagerTabStrip#624]
Hi,
When can we expect the new release that supports Xcode 10 and iOS 12?

**Comment by bradleyvandyk** [comment]
+1 to this, there is currently a scrollview issue afaik

**Comment by qsdnino** [comment]
(Xcode 10, iOS 12)++

**Comment by mats-claassen** [comment]
Use master branch for now until we release:
`pod 'XLPagerTabStrip', :git => 'https://github.com/xmartlabs/XLPagerTabStrip', :branch => 'master'`

**Comment by qsdnino** [comment]
> Use master branch for now until we release:
> `pod 'XLPagerTabStrip', :git => 'https://github.com/xmartlabs/XLPagerTabStrip', :branch => 'master'`

Thanks a lot!

**Comment by mats-claassen** [comment]
Released 8.1.0 for Swift 4.2 and Xcode 10
