### ISSUE TITLE
why build failed after pod update 

### ISSUE THREAD

**Issue by nizenyang** [xmartlabs/XLPagerTabStrip#631]
![image](https://user-images.githubusercontent.com/8390188/46712033-9952fb80-cc81-11e8-9d99-f806e03473b7.png)
![image](https://user-images.githubusercontent.com/8390188/46712038-9eb04600-cc81-11e8-9a4f-430b758aa590.png)

I can't convert to swift 4.2 because can't build failed
 xcode 10

**Comment by alexanderkhitev** [comment]
@nizenyang please use     `pod 'XLPagerTabStrip', :git => 'https://github.com/xmartlabs/XLPagerTabStrip.git', :branch => 'master'`

**Comment by Titzian** [comment]
Hey alex,
will there be a newer pod-version of this project or do we need to use the above mentioned line in our podfile to make it work?

**Comment by alexanderkhitev** [comment]
HI @Titzian ! I'm sorry I don't know this information because I'm not from core team

**Comment by alexanderkhitev** [comment]
@Titzian you can ask about it @m-revetria , @mats-claassen

**Comment by mats-claassen** [comment]
Just released version 8.1.0 for Swift 4.2. 🎉
