### ISSUE TITLE
need modification on selected button bar item

### ISSUE THREAD

**Issue by nikhil191090** [xmartlabs/XLPagerTabStrip#632]
hello i need button bar selected item style on above. i have added screenshot .. Please help
![7 category](https://user-images.githubusercontent.com/13807014/46718364-9d364c00-cc88-11e8-9899-ce182f209bcc.png)

**Comment by nikhil191090** [comment]
@mtnbarreto Please Help me. I am kind of stuck here

**Comment by Mahesh160393** [comment]
@mtnbarreto  i have same issue please help

**Comment by khush004** [comment]
settings.style.selectedBarVerticalAlignment = .top

**Comment by nikhil191090** [comment]
@khush004 Thank you so much. it worked 👍
