### ISSUE TITLE
Move to second child VC from first child VC on button click

### ISSUE THREAD

**Issue by kunaltyagi26** [xmartlabs/XLPagerTabStrip#635]
Hi,

Actually my requirement is to show second child VC from first child VC on the button click. I have gone through the docs as well as issues but wasn't able to get help from them. Any help will be appreciated. Thanks.

**Comment by kmmpaliza** [comment]
1. Create a var that equals to PagerTabStripViewController().
2. Then set that var inside the indicatorInfo. Like this:

func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        pagerStrip = pagerTabStripController
        return itemInfo
    }

3. Inside the action method:
     pagerStrip.moveToViewController(at: 1, animated: true)

**Comment by luisrodrigo** [comment]
@kmmpaliza I want to move to third view controller using moveToViewController(at: index), but does not work. It happen with any index which pass
