### ISSUE TITLE
Custom Tableview crash

### ISSUE THREAD

**Issue by surajglokhande** [xmartlabs/XLPagerTabStrip#641]
1. Drag and drop tableview in view controller.
2. create tableview outlet
3. conform delegate and datasource.
3. but when try to reload tableview in viewdidload or in other function. or conform delegate and datasource in viewdidload tableview crash.
show me this error
Fatal error: Unexpectedly found nil while unwrapping an Optional value.

**Comment by ToniNgethe** [comment]
And how do you label the tab titles using your method @kmmpaliza ?

**Comment by kmmpaliza** [comment]
@ToniNgethe In your tab controller class.

class TAB1: UIViewController, IndicatorInfoProvider {
    
    var itemInfo: IndicatorInfo = "TITLE 1"
    var pagerStrip = PagerTabStripViewController()
   
    // MARK: - XLPagerTabStrip
    func indicatorInfo(for pagerTabStripController: PagerTabStripViewController) -> IndicatorInfo {
        pagerStrip = pagerTabStripController
        return itemInfo
    }
    override func viewDidLoad() {
        super.viewDidLoad()
    }
}

**Comment by mtnbarreto** [comment]
Please follow the example project that contains many examples on how to customize the library.
