### ISSUE TITLE
Unable to simultaneously satisfy constraints

### ISSUE THREAD

**Issue by sphairo** [xmartlabs/XLPagerTabStrip#657]
I am using xCode 9.4 and version XLPagerTabStrip -> 8.0.0, when i rotate iphone device in my console appears: Unable to simultaneously satisfy constraints.
	Probably at least one of the constraints in the following list is one you don't want.

Then my app crash :(

**Comment by mtnbarreto** [comment]
Could you elaborate more on which are the constraints that causes the issue? 
I tested the example app and it works properly. Please review the constraints you added to your child view cotnrollers.
