### ISSUE TITLE
How can i update title of barview?

### ISSUE THREAD

**Issue by ttoggaiman** [xmartlabs/XLPagerTabStrip#669]
Xcode 10.1 XLPagerTabStrip

I have 4 tab

tab1 . tab2.  tab3. tab4

case1.
if current index is tab1  

      if let pagerTabStrip = self.parent as? ButtonBarPagerTabStripViewController {
            
           pagerTabStrip.buttonBarView.reloadData()
           
    }

this code is work perfectly

case2. 
if current index is tab3  but i want to update title of tab1 

     if let pagerTabStrip = self.parent as? ButtonBarPagerTabStripViewController {
            
           pagerTabStrip.buttonBarView.reloadData()
           
    }
this code didn't work . 

how can i update bar title from  another tab

**Comment by abdallahnh** [comment]
I have same issue i need to use search that return different results and i need to update the pages title like:
Items(5) ---- Stuff(2) ---- Elec(10)
while items, stuff, elec are my pages

thanks.

**Comment by mtnbarreto** [comment]
Have you tried using `reloadPagerTabStripView()`? 
It will ask you for the new view controllers and tabinfo again then you can move to desired view controller if needed. 

Example app shows how to use it.

**Comment by mtnbarreto** [comment]
```swift
    open override func reloadPagerTabStripView() {
        super.reloadPagerTabStripView()
        guard isViewLoaded else { return }
        buttonBarView.reloadData()
        cachedCellWidths = calculateWidths()
        buttonBarView.moveTo(index: currentIndex, animated: false, swipeDirection: .none, pagerScroll: .yes)
    }
```
