### ISSUE TITLE
xlPagerTabStrip add view above tabs in parent view

### ISSUE THREAD

**Issue by salahrzzaz** [xmartlabs/XLPagerTabStrip#670]
hello,
I developed xlPagerTabStrip and working fine but have issue
- in the screenshot attached there is an orange line between tabs

  settings.style.buttonBarBackgroundColor = .white
        settings.style.buttonBarItemBackgroundColor = .white
        settings.style.selectedBarBackgroundColor = purpleInspireColor
        settings.style.buttonBarItemFont = .boldSystemFont(ofSize: 14)
        settings.style.selectedBarHeight = 2.0
        settings.style.buttonBarMinimumLineSpacing = 0
        settings.style.buttonBarItemTitleColor = .black
        settings.style.buttonBarItemsShouldFillAvailiableWidth = true
        settings.style.buttonBarLeftContentInset = 0
        settings.style.buttonBarRightContentInset = 0
        changeCurrentIndexProgressive = { [weak self] (oldCell: ButtonBarViewCell?, newCell: ButtonBarViewCell?, progressPercentage: CGFloat, changeCurrentIndex: Bool, animated: Bool) -> Void in
            guard changeCurrentIndex == true else { return }
            oldCell?.label.textColor = .black
            newCell?.label.textColor = self?.purpleInspireColor
        }
        
        buttonBarView.frame.origin.y = buttonBarView.frame.origin.y + 100

![issue](https://user-images.githubusercontent.com/45657738/49580264-31eeba80-f957-11e8-9c73-d064bb31aa89.jpg)

**Comment by nwaseem** [comment]
i had the same issue 
Please ensure the buttonBarView from storyboard is connected to its proper outlet

**Comment by mtnbarreto** [comment]
If the `buttonBarView` is not properly connected the library creates one that has the background color set to .orange. So if this is what you want you will have to change its background color.
