### ISSUE TITLE
GSMessage's showMessage function for toast not appearing in XLPagerTabStrip?

### ISSUE THREAD

**Issue by varalakshmi090** [xmartlabs/XLPagerTabStrip#671]
I am using XLPagerTabStrip and I have two child view inside it. In the child view I am using showMessage function to print the toast for the error messages but the toast is not shown in the view.

```swift
if ( debit_amount > availBal_Amount )
{
    self.showMessage("NO_SUFFICIENT_BAL", type: .error, options: [.position(.bottom),.textNumberOfLines(0)])
}

This the showMessage function:

open func showMessage(_ text: String,
                      type: GSMessageType,
                      options: [GSMessageOption]? = nil) {
    GSMessage.showMessageAddedTo(text: text, type: type, options: options, inView: view, inViewController: self)    }

```

only in XLPagerTabStrip view showMessage() is not working.

Please help me in solving the issue.

**Comment by mtnbarreto** [comment]
Please enter in contact with GSMessage maintainers, XLPagerTabStrip does not do anything special apart from using UIKit sdk.

Have you tried showing the mesage from the child parentController?
