### ISSUE TITLE
XLPagerTabStrip creates two instances of first ViewController

### ISSUE THREAD

**Issue by krptia** [xmartlabs/XLPagerTabStrip#689]
XLPagerTabStrip creates two instances of a ViewController

After capturing memory graph, it shows that 2 instances are active of the first view controller that is given to the  `viewControllers(for pagerTabStripController` function.

For example, in the following case, the ** firstViewController** gets generated 2 times. 

`override public func viewControllers(for pagerTabStripController: PagerTabStripViewController) -> [UIViewController] {
        return [firstViewController, secondViewController]
    }`

**Comment by Alexookah** [comment]
i am having the same problem. how did you solve it @krptia ?

**Comment by krptia** [comment]
I’ll get home in 2 days, I’ll inform you. But as far as I remember, I think I called some functions in the viewDidLoad / viewDidAppear which caused it. If you’ve written something in those parts of the code, inspect it!
