### ISSUE TITLE
How to use images as tab instead of title?

### ISSUE THREAD

**Issue by macpraveen** [xmartlabs/XLPagerTabStrip#70]
I would like to use images as tab instead of title in XLButtonBarPagerTabStripViewController. Please guide in achieving this.

**Comment by dbpatel219** [comment]
Would also love to use this,  i'm trying to understand the youtube example but keeping getting the following error:

`Unknown class YoutubeExampleViewController in Interface Builder file.`

I've looked up the error and made sure in IB my Module is set to Current and explicitly tried setting it to the project.  I'm not sure what is going on.  

Awesome work on this project and would love to get images working.

**Comment by m-revetria** [comment]
Hi, the class `YoutubeExampleViewController` is not included when you install the library as a pod. You can copy it directly to your project if you want.
