### ISSUE TITLE
Containerview content changes y position when scrolled

### ISSUE THREAD

**Issue by CianApple** [xmartlabs/XLPagerTabStrip#72]
![screen shot 2015-09-04 at 5 40 56 pm](https://cloud.githubusercontent.com/assets/5582957/9683270/27cceb1e-532c-11e5-91b6-c4d63138ab6a.png)
![screen shot 2015-09-04 at 5 41 06 pm](https://cloud.githubusercontent.com/assets/5582957/9683274/2d0f79e8-532c-11e5-9189-e0983551e4d2.png)

Hi

Am using your control. Everything is working fine when I touch the buttons in the collection view. But when i use gesture to scroll, it moves down. Why is that? When I select button again, it comes back up.

**Comment by lixiaoyu** [comment]
I occurred that case  occasionally too

**Comment by o0starshine0o** [comment]
I have fix this bug below:
https://github.com/xmartlabs/XLPagerTabStrip/issues/69

**Comment by mtnbarreto** [comment]
Look at issue #69 for a solution
