### ISSUE TITLE
Position Of the bar

### ISSUE THREAD

**Issue by DhruvTekchandani** [xmartlabs/XLPagerTabStrip#720]
![IMG_1559](https://user-images.githubusercontent.com/32982268/58246151-aef0dd80-7d99-11e9-968a-f8f804716982.PNG)
Hey guys, so I'm current facing this issue. I tried searching for it everywhere but no luck.

As shown in the pic, I'm trying to get the bar to be in the grey area but it keeps sticking to the nav bar. I have applied constraints but it doesn't seem to be doing the trick..

Any idea on what exactly I am doing wrong and how I can bring the bar down to the gray area?

**Comment by DhruvTekchandani** [comment]
Incase anyone is struggling with the same thing. There are 2 things you need to do.

1) ensure that you ctrl + right click from the current view controller to the scroll view
<img width="671" alt="Screen Shot 2019-05-23 at 11 15 10 PM" src="https://user-images.githubusercontent.com/32982268/58255604-b8397480-7db0-11e9-8891-e4be6f152feb.png">

2) Ensure that the container view is connected
<img width="726" alt="Screen Shot 2019-05-23 at 11 15 19 PM" src="https://user-images.githubusercontent.com/32982268/58255638-cab3ae00-7db0-11e9-9a04-219599917083.png">

3) create a collection view as mentioned and delete the cell. Then do the following. Also, make sure you have assigned the right class to the collection view
<img width="734" alt="Screen Shot 2019-05-23 at 11 15 29 PM" src="https://user-images.githubusercontent.com/32982268/58255674-db642400-7db0-11e9-8a7f-f335c54a3eca.png">

4) & Finally, make sure buttonBarView is connected. 
<img width="808" alt="Screen Shot 2019-05-23 at 11 15 35 PM" src="https://user-images.githubusercontent.com/32982268/58255741-fe8ed380-7db0-11e9-97b7-6f104ae01435.png">

Once you have done all this then you can apply your constraints as you do and position it on the place you want it to be

Final image
![IMG_0492](https://user-images.githubusercontent.com/32982268/58255837-36961680-7db1-11e9-8a0d-816c606219e5.PNG)


Hope this helps!

Im closing this as it has been solved. 
Feel free to re-open is neccessary.

**Comment by hamidptb** [comment]
Thanks a lot

**Comment by meshileya** [comment]
How can one get this done programmatically, please?
