### ISSUE TITLE
XLButtonBarView cell misalignment

### ISSUE THREAD

**Issue by catsynth** [xmartlabs/XLPagerTabStrip#73]
Hi there.  I am having trouble getting the cells in my XLButtonBarView to properly align.  The first one seems to be placed higher no matter what I do, and the indicator plus subsequent cells fall into the correct place.

Interestingly, I have another instance of XLButtonBarView elsewhere in the app which works fine, but can't seem to determine any difference between them, or why this instance has this problem.

The UIViewController is derived from XLButtonBarPagerTabStripViewController.

Please advise, and let me know if you need any additional details.  I have attached some example images (the cells are red to highlight the issue).

![ios simulator screen shot sep 5 2015 10 26 05 am](https://cloud.githubusercontent.com/assets/8483574/9700550/aa5e96b0-53bb-11e5-8b2c-4c545fa92f64.png)
![ios simulator screen shot sep 5 2015 10 26 02 am](https://cloud.githubusercontent.com/assets/8483574/9700552/aa60fdec-53bb-11e5-81c8-263577e9126b.png)
![ios simulator screen shot sep 5 2015 10 25 47 am](https://cloud.githubusercontent.com/assets/8483574/9700551/aa5faa46-53bb-11e5-9cb6-8bb21e72d084.png)

**Comment by RockyLin** [comment]
same problem....maybe it's a bug caused by embedding tableview inside scrollview....

**Comment by mtnbarreto** [comment]
Which is the library version you are using?
@catsynth Could you please check if you still have the trouble using repository master branch code?

If nothing works, please upload a repository so i can reproduce the the issue.

**Comment by mtnbarreto** [comment]
It should no longer happens in version 4.0.0.
