### ISSUE TITLE
Width issue for ButtonBarView with Label and Image

### ISSUE THREAD

**Issue by sz-ashik440** [xmartlabs/XLPagerTabStrip#737]
I am trying to implement XLPagerTabStrip just like YoutubeWithLabelExampleViewController from Example project. I can configure it right but issue is width become fixed as I have to set width of `buttonBarItemSpec`.

```
buttonBarItemSpec = ButtonBarItemSpec.nibFile(nibName: "YoutubeIconWithLabelCell", bundle: Bundle(for: YoutubeIconWithLabelCell.self), width: { _ in
        return 40.0
})
```

I also tried to set `settings.style.buttonBarItemsShouldFillAvailableWidth = true` and `settings.style.buttonBarItemLeftRightMargin = 0`, but still it won't resize with the label size and keep the cell size fixed(40.0). 

- version: XLPagerTabStrip (9.0.0)
- Xcode: 10.2.1
- iOS: 12.2
<img width="343" alt="Screenshot 2019-07-21 at 5 46 02 PM" src="https://user-images.githubusercontent.com/9111027/61590776-b0932200-abdf-11e9-9f46-013034b8cbbb.png">

**Comment by Tawfikk** [comment]
Anyone does fixed this bug ?

**Comment by NikitaHappilyUnmarried** [comment]
I m facing the same issue, have you fixed this?

**Comment by sz-ashik440** [comment]
I found a work-around. Override `sizeForItemAtIndexPath` of `UICollectionViewDelegateFlowLayout` and set your custom size for you Button Bar cell size.
```
override func collectionView(_ collectionView: UICollectionView, layout collectionViewLayout: UICollectionViewLayout, sizeForItemAtIndexPath indexPath: IndexPath) -> CGSize {
    return CGSize(width: <custom_width>, Height:<custom_height>)
}
```
PS: to get label size, you can use this extension for String
```
extension String {
    /// Get size for String
    /// - Parameters:
    ///   - font: used font for string
    ///   - spacing: kerning value for spacing
    /// - Returns: size require for text to shown
    func size(with font: UIFont?, spacing: Double = 0) -> CGSize {
        var attributes: [NSAttributedString.Key : Any] = font != nil ? [NSAttributedString.Key.font: font!] : [:]
        attributes[.kern] = spacing
        let textSize = self.size(withAttributes: attributes)
        return textSize
    }
}
```
