### ISSUE TITLE
How to make Collection View from storyboard?

### ISSUE THREAD

**Issue by priyansh1990** [xmartlabs/XLPagerTabStrip#76]
Can we make our UI from StoryBoard. How to make UICollectionView from storyBoard.

**Comment by RockyLin** [comment]
same problem. The Scrollview in the storyboard is connected to the super class, don't know how they did it...

**Comment by mtnbarreto** [comment]
First open the storyboard then select the relevant view controller. 
Then open assistant editor and using the drop down menu select the base pager view controller class as the image below shows.

<img width="1205" alt="screen shot 2016-01-08 at 12 08 44 am" src="https://cloud.githubusercontent.com/assets/1746532/12189410/1a6b35c0-b59c-11e5-8d73-f7b935e0d12e.png">

Finally connect the base view controller class outlets.
