### ISSUE TITLE
ButtonBar last page bar item is not displayed but still interactable

### ISSUE THREAD

**Issue by 4D4B** [xmartlabs/XLPagerTabStrip#79]
As per title.

The demo itself works fine, but even copying the demo over to a new project and this issue occurs.

**Comment by mtnbarreto** [comment]
@4D4B make sure your last child view controller conforms to `XLPagerTabStripViewControllerDelegate` and implements `-(NSString *)titleForPagerTabStripViewController:(XLPagerTabStripViewController *)pagerTabStripViewController`. Otherwise there will be no text in the last button.

Regards
