### ISSUE TITLE
the UIPageControl color can not change

### ISSUE THREAD

**Issue by holyen** [xmartlabs/XLPagerTabStrip#80]

**Comment by holyen** [comment]
how can i change the Indicator color

**Comment by darkbreed** [comment]
The delegate method does not work, but try this:

[self.buttonBarView.selectedBar setBackgroundColor:[UIColor whiteColor]];

**Comment by mtnbarreto** [comment]
@darkbreed :+1:

**Comment by Raymond26** [comment]
@darkbreed 's line should definitely be added to the main Readme.
