### ISSUE TITLE
Tapping on buttons in button bar has no effect.

### ISSUE THREAD

**Issue by tcalin** [xmartlabs/XLPagerTabStrip#81]
Hello everybody!
I am using the XLButtonBarPagerTabStripViewController variant. I might be missing something but the only way to navigate between child controllers is by swiping. Tapping on buttons has no effect.

**Comment by tcalin** [comment]
Problem dissapeared after using storyboard (I was doing everything from code).

**Comment by mtnbarreto** [comment]
:+1:

**Comment by abcde1499** [comment]
Hi, having the same problem here using storyboard :(

**Comment by abcde1499** [comment]
Sorry my bad. It was my own bug and it's not related
The library is totally good!
