### ISSUE TITLE
[HELP] buttonBarView be covered by navigationBar, and wired default color

### ISSUE THREAD

**Issue by hungwei0331** [xmartlabs/XLPagerTabStrip#828]
<img width="339" alt="Screen Shot 2021-07-05 at 1 14 41 AM" src="https://user-images.githubusercontent.com/10335229/124393760-8a181400-dd2e-11eb-83ca-8f0c1a98a691.png">

<img width="201" alt="Screen Shot 2021-07-05 at 1 08 02 AM" src="https://user-images.githubusercontent.com/10335229/124393763-8c7a6e00-dd2e-11eb-95a0-09c63f6aee8e.png">

I am sorry I know there has few same issus before,

but the solutions are several years ago,

I created the sample step by step like offical example,

but the bug still appear,  had try many ways but still could not resolve it,

the buttonBarView be covered by navigationBar

even I know I could correct it like below 

in viewDidload add, edgesForExtendedLayout = [] 

but this line will make tabBarr and navigationBar get strage color like the image below,

and this color can not be remove completely

<img width="335" alt="Screen Shot 2021-07-05 at 1 14 48 AM" src="https://user-images.githubusercontent.com/10335229/124393864-2a6e3880-dd2f-11eb-878d-d299bf8843cc.png">

also try modified buttonBarView.frame.origin.y,

but the scroll view seems like could not modified the y value as same way

hope someone could help me this question, thanks in advance for any reply

**Comment by wonjulee-ios** [comment]
navigationController?.navigationBar.isTranslucent = false

**Comment by hungwei0331** [comment]
> navigationController?.navigationBar.isTranslucent = false

thank you so much,
add both of line below in viewDidLoad works well for me

edgesForExtendedLayout = []
navigationController?.navigationBar.isTranslucent = false

**Comment by usmanabid94** [comment]
> > navigationController?.navigationBar.isTranslucent = false
> 
> thank you so much, add both of line below in viewDidLoad works well for me
> 
> edgesForExtendedLayout = [] navigationController?.navigationBar.isTranslucent = false

You are a saviour it worked completely fine. 
Thank you.
