### ISSUE TITLE
XLPage Navigation Overlap (Swift)

### ISSUE THREAD

**Issue by neaped** [xmartlabs/XLPagerTabStrip#84]
Environment: Swift 2.1  Xcode 7.1

I have created a working swift demo with tableview and container view. Both content are fine, but just have problem with the navigation bar

The navigation bar looks never been created by XLPagerTabStrip. The XLBarView just attach on the UIView directly

Here is storyboard setup and the view hierarchy

1st view:

Storyboard with tabbarcontroller and navigation controller:
![screen shot 2015-11-01 at 10 21 47 pm](https://cloud.githubusercontent.com/assets/3713305/10869425/3858de5c-80ea-11e5-8efa-fbdf10853dcc.png)
App View:
![screen shot 2015-11-01 at 10 22 06 pm](https://cloud.githubusercontent.com/assets/3713305/10869427/43cffb76-80ea-11e5-8982-1e033b3d89f2.png)
Hierarchy
![screen shot 2015-11-01 at 10 22 19 pm](https://cloud.githubusercontent.com/assets/3713305/10869429/5a36f55e-80ea-11e5-814a-9b354d0cb30c.png)

Can see the XLBarView is floating on the UIView but the default navigation bar just cover it

2nd view: 
Storyboard with just tabbarcontroller
![screen shot 2015-11-01 at 10 22 46 pm](https://cloud.githubusercontent.com/assets/3713305/10869435/9c41e4f4-80ea-11e5-9a3b-fb0208803f29.png)
App View:
![screen shot 2015-11-01 at 10 22 49 pm](https://cloud.githubusercontent.com/assets/3713305/10869437/a38857a2-80ea-11e5-8f88-d2500bea6663.png)
Hierarchy:
![screen shot 2015-11-01 at 10 49 06 pm](https://cloud.githubusercontent.com/assets/3713305/10869445/d3f0a9d0-80ea-11e5-83c1-e4f9ff488012.png)

**Comment by mtnbarreto** [comment]
@neaped 
As the example project shows you can set up the barView position by setting up the view using interface builder.  

1. Drag a UIView into your `XLBarPagerTabStripViewController` storyboard controller.
2. Set up its autolayout constraints.
3. Make sure the bar view class  is `XLBarView`.

Here is the outlet i'm talking about:
```obj-c
@interface XLBarPagerTabStripViewController : XLPagerTabStripViewController

@property (nonatomic) IBOutlet XLBarView * barView;

@end
```

**Comment by neaped** [comment]
@mtnbarreto  I didn't check OC example before, problem solved. Thanks for help
