### ISSUE TITLE
Swift Package Manager

### ISSUE THREAD

**Issue by erwanmace** [xmartlabs/XLPagerTabStrip#847]
Any chance to add the required package.swift so that we can install the library through Swift Package Manager?
This is the last package of my app for which I a, keeping Cocoa Pod

**Comment by askari01** [comment]
I created a fork to support SPM, but it will be good to have it here :)

**Comment by Climbatize** [comment]
Hi @erwanmace, I also created a SPM fork, upgrading support to XCode 11 (minimum required for SPM availability) and with a dependency to FXPageControl lib (a PR has been pushed to this repo too), which was copied in sources until now. You can check the diff here: https://github.com/xmartlabs/XLPagerTabStrip/compare/master...Climbatize:XLPagerTabStrip:master and use this repo in your SPM config: https://github.com/Climbatize/XLPagerTabStrip.git

**Comment by mats-claassen** [comment]
Hi all, SPM support has been added in 9.1.0!
