### ISSUE TITLE
How to change XLButtonBarViewCell Align Center in XLButtonBarView?

### ISSUE THREAD

**Issue by MinsungHuh** [xmartlabs/XLPagerTabStrip#89]
I used XLButtonBarPagerTabStripViewController into two child views.

but I can't align center to XLButtonBarViewCell ( child view title )

how to arrange to center my child titles? 

sorry my english skills....

**Comment by mtnbarreto** [comment]
@MinsungHuh,
thanks to @OliverPearmain now XLPagerTabStrip has a solution to it, take a look at the code snippet below. 
 ```obj-c
- (void)viewDidLoad {
    [super viewDidLoad];
    self.buttonBarView.shouldCellsFillAvailableWidth = YES;
...
```

it's only available on master branch for now.

**Comment by lazybetrayer** [comment]
I have the same problem.
I am using 5.0.0 swift version and have set `buttonBarItemsShouldFillAvailiableWidth` to true.
Bellow are the screenshots. 
It's ok when there are four titles. But when I add one more title, they are pushed to the left.
<img width="379" alt="2016-05-28 5 20 59" src="https://cloud.githubusercontent.com/assets/4188244/15626497/9c272b84-24f8-11e6-83e8-3a879bcc11d4.png">

<img width="377" alt="2016-05-28 5 21 07" src="https://cloud.githubusercontent.com/assets/4188244/15626498/9e2437d8-24f8-11e6-922b-6f5d693d130d.png">
