### ISSUE TITLE
Multiple tabs on an item stops the BarViews movement while swiping through controllers

### ISSUE THREAD

**Issue by Rawrcoon** [xmartlabs/XLPagerTabStrip#9]
> Ability to skip intermediate view controllers when tapped on a "tab".

If you tab bar items multiple times, the bar view gets locked and doesn't move while swiping through view controllers

**Comment by Rawrcoon** [comment]
i fixed this with the following changes. Don't know if it breaks on some other end now :)
```
-(void)pagerTabStripViewController:(XLPagerTabStripViewController *)pagerTabStripViewController updateIndicatorToViewController:(UIViewController *)toViewController fromViewController:(UIViewController *)fromViewController
{
//    if (self.shouldUpdateButtonBarView){
        NSUInteger newIndex = [self.pagerTabStripChildViewControllers indexOfObject:toViewController];
        XLPagerTabStripDirection direction = XLPagerTabStripDirectionLeft;
        if (newIndex < [self.pagerTabStripChildViewControllers indexOfObject:fromViewController]){
            direction = XLPagerTabStripDirectionRight;
        }
        [self.buttonBarView moveToIndex:newIndex animated:YES swipeDirection:direction];
//    }
}
```

**Comment by mtnbarreto** [comment]
@Rawrcoon 
When the library needs to skip view controllers it uses a helper array to be able to transition to the relevant view controller. This helper array doesn't represent the real order of child view controller, it's temporary array that put the view controller to be presented on the left or on the right of current view controller. 
Then the library make use of contentOffset UIScrollView to make the transition between view controllers (skiping intermediate view controllers) and when the transition finishes we enable the UI again. 

The transition takes half a second so i thought that it would not be a big deal. 

This is the [relevant part of the code](https://github.com/xmartlabs/XLPagerTabStrip/blob/master/XLPagerTabStrip/XL/Controllers/XLPagerTabStripViewController.m#L122) that does the trick.

Regards
