### ISSUE TITLE
Margin disappear

### ISSUE THREAD

**Issue by chlebta** [xmartlabs/XLPagerTabStrip#93]
I've tableview with left and right margin and using this library for the first VC the margin appear but once I change the margin disappear for the next VC.

![slice 1](https://cloud.githubusercontent.com/assets/1204608/11761426/8d7d1c98-a0c2-11e5-9d30-10892a8605b3.png)

**Comment by RockyLin** [comment]
shit happens...

**Comment by sdac** [comment]
might be related to https://github.com/sdac/XLPagerTabStrip/commit/572d975be2fc48103f6dc319c8db6fef61d4273f
try 
```
pod 'XLPagerTabStrip', :git => 'https://github.com/sdac/XLPagerTabStrip'
```

**Comment by mtnbarreto** [comment]
@monoqlo It seems that the issue was already fixed, could you check master branch code?
