### ISSUE TITLE
Reusable ChildViewControllers?

### ISSUE THREAD

**Issue by mumu2017** [xmartlabs/XLPagerTabStrip#98]
I want to use the XLPagerTabStrip to manage my editing page. And there will be a lot of child view controllers of the same class containing textviews, does XLPagerTabStrip support reusable childViewControllers? If not, if there are too many childViewControllers, will there be a memory problem?

**Comment by mtnbarreto** [comment]
@mumu2017 At the moment it does not support reusable view controllers but It would be a good feature. I'm gonna leave it open and see if someone else ask for the same feature.

Regarding the number of child view controllers the library supports without any memory issue, It depends on how much memory each child view controller consumes. Easy way to evaluate the performance is testing the real scenario by adding all these child view controllers (they are the same vc class based on what you said, so it should be easy to instantiate many of it).

**Comment by mtnbarreto** [comment]
@mumu2017  What about the pager performance having many vc? Have you tried it out?

**Comment by ivanmih** [comment]
@mumu2017 @mtnbarreto  I am also interested in this feature. Seems quite logical if we have several heavy view controllers. What do you think?
