### ISSUE TITLE
Change Selected Tab's Label color and font 

### ISSUE THREAD

**Issue by sunillohar** [xmartlabs/XLPagerTabStrip#99]
How to change the color and font of current / selected Tab's label ? according to Document 
There are two methods to change selection color, but I dont understand how to use it : 
@property (copy) void (^changeCurrentIndexProgressiveBlock)(XLButtonBarViewCell* oldCell, XLButtonBarViewCell *newCell, CGFloat progressPercentage, BOOL indexWasChanged, BOOL animated);
@property (copy) void (^changeCurrentIndexBlock)(XLButtonBarViewCell* oldCell, XLButtonBarViewCell *newCell, BOOL animated);

**Comment by sunillohar** [comment]
ok. i just got it worked. 
using following code : 

self.changeCurrentIndexBlock = (^void(XLButtonBarViewCell* oldCell, XLButtonBarViewCell *newCell, BOOL animated){
        oldCell.label.textColor =[UIColor whiteColor];
        newCell.label.textColor =[UIColor greenColor];
    });

**Comment by mtnbarreto** [comment]
@sunillohar great! here is the documentation https://github.com/xmartlabs/XLPagerTabStrip#how-to-change-the-selected-tab-xlbuttonbarviewcell-look-and-feel-based-on-the-selected-state
